// ================================================================================================
// produkt:20261010:assistenz-name-avatar — DIE TEXTE DER PERSÖNLICHEN ASSISTENZ.
// ================================================================================================
//
// Ersteinrichtung („Wie soll deine Assistenz heißen?"), „Meine Assistenz" in den persönlichen
// Einstellungen, die dreizehn Motive und die neutrale Bezeichnung, solange kein Name gespeichert ist.
// „Klara" steht hier bewusst nirgends: der Name ist persönliche Wahl, kein Produktname.
import type { Textmodul } from "./intern/pruefung";

export default {
  praefix: "assistenz.",
  legacySchluessel: [],
  de: {
    "assistenz.neutral.name": "Assistenz",
    "assistenz.neutral.titel": "Deine Assistenz",
    "assistenz.einrichtung.region": "Persönliche Assistenz einrichten",
    "assistenz.einrichtung.frage": "Wie soll deine Assistenz heißen?",
    "assistenz.einrichtung.kurz":
      "Gib ihr einen eigenen Namen und wähle eines von dreizehn Motiven – nur für dein Konto.",
    "assistenz.einrichtung.starten": "Jetzt einrichten",
    "assistenz.einrichtung.intro":
      "Gib deiner Assistenz einen Namen und wähle ein Motiv. Das gilt nur für dein Konto – Anmeldung, Rolle und die KI-Einstellungen deiner Organisation bleiben unverändert.",
    "assistenz.einrichtung.speichern": "Einrichtung speichern",
    "assistenz.einrichtung.spaeter": "Später",
    "assistenz.einrichtung.spaeterHinweis":
      "Die Einrichtung ist noch nicht abgeschlossen und wird dir bei der nächsten Anmeldung wieder angeboten.",
    "assistenz.einrichtung.fertig":
      "Eingerichtet – {{name}} begleitet dich ab jetzt. Ändern kannst du das jederzeit unter Einstellungen → Persönliche Einstellungen → Meine Assistenz.",
    "assistenz.einrichtung.schliessen": "Schließen",
    "assistenz.feld.name": "Name deiner Assistenz",
    "assistenz.feld.nameHilfe": "1 bis 40 Zeichen, frei wählbar. Der Name gilt nur für dich.",
    "assistenz.fehler.nameLeer": "Bitte gib einen Namen ein.",
    "assistenz.fehler.nameLang": "Der Name ist höchstens 40 Zeichen lang.",
    "assistenz.fehler.nameZeile": "Bitte eine Zeile Text ohne Zeilenumbrüche oder Steuerzeichen.",
    "assistenz.fehler.avatarLeer": "Bitte wähle ein Motiv.",
    "assistenz.fehler.zusammen":
      "Bitte die markierten Felder ergänzen – noch ist nichts gespeichert.",
    "assistenz.avatar.legende": "Avatar wählen",
    "assistenz.avatar.gruppe.ausdrucksstark": "Ausdrucksstark",
    "assistenz.avatar.gruppe.sachlich": "Sachlich",
    "assistenz.avatar.gewaehlt": "Ausgewählt",
    "assistenz.avatar.vorschau": "Vorschau: {{name}} als {{motiv}}",
    "assistenz.avatar.originalHinweis": "das bisherige orange Maskottchen",
    "assistenz.avatar.fehlt":
      "Das gespeicherte Motiv wird nicht mehr angeboten. Bis du ein neues wählst, steht hier eine neutrale Ersatzgrafik – dein Name bleibt erhalten.",
    "assistenz.avatar.bildFehlt": "Bild nicht verfügbar",
    "assistenz.avatar.ersatz": "Neutrale Ersatzgrafik",
    "assistenz.avatar.name.original": "Original",
    "assistenz.avatar.name.lichtwesen": "Lichtwesen",
    "assistenz.avatar.name.roboter": "Roboter",
    "assistenz.avatar.name.eule": "Eule",
    "assistenz.avatar.name.fuchs": "Fuchs",
    "assistenz.avatar.name.pinguin": "Pinguin",
    "assistenz.avatar.name.wolke": "Wolke",
    "assistenz.avatar.name.kompass": "Kompass",
    "assistenz.avatar.name.prisma": "Prisma",
    "assistenz.avatar.name.wissensbuch": "Wissensbuch",
    "assistenz.avatar.name.verbindungsknoten": "Verbindungsknoten",
    "assistenz.avatar.name.monolith": "Monolith",
    "assistenz.avatar.name.leuchtkreis": "Leuchtkreis",
    "assistenz.bewegung.label": "Bewegung der Figur reduzieren",
    "assistenz.bewegung.hilfe":
      "Schaltet die Animationen der Figur ab: Jeder Zustand bleibt als ruhiger Ausdruck und als Text sichtbar. Ist im System reduzierte Bewegung eingestellt, gilt sie ohnehin.",
    "assistenz.speichern.laeuft": "Wird gespeichert …",
    "assistenz.speichern.fehler":
      "Nicht gespeichert: {{grund}} Deine Eingabe bleibt stehen; gespeichert bleibt der bisherige Stand.",
    "assistenz.speichern.netz": "Der Server war nicht erreichbar.",
    "assistenz.speichern.wiederholen": "Erneut speichern",
    "assistenz.speichern.abbrechen": "Abbrechen",
    "assistenz.laden.fehler": "Das Assistenzprofil konnte gerade nicht gelesen werden.",
    "assistenz.laden.wiederholen": "Erneut laden",
    "assistenz.einstellungen.titel": "Meine Assistenz",
    "assistenz.einstellungen.intro":
      "Name und Motiv deiner persönlichen Assistenz – einzeln oder gemeinsam änderbar. Die Änderung gilt sofort in der geöffneten Assistenz und nur für dein Konto.",
    "assistenz.einstellungen.speichern": "Speichern",
    "assistenz.einstellungen.gespeichert": "Gespeichert: {{name}} mit dem Motiv „{{motiv}}“.",
    "assistenz.einstellungen.unveraendert": "Keine Änderung – es gibt nichts zu speichern.",
    "assistenz.einstellungen.abgebrochen": "Abgebrochen – es bleibt bei der bisherigen Auswahl.",
    "assistenz.einstellungen.offen": "Noch nicht eingerichtet",
    "assistenz.hilfe.oeffnen": "{{assistenz}} öffnen — Hilfe zu dieser Seite",
    "assistenz.zustand.bereit": "Bereit",
    "assistenz.zustand.warten": "Wartet auf die Antwort",
    "assistenz.zustand.nachdenken": "Verarbeitet die Anfrage",
    "assistenz.zustand.zuhoeren": "Hört zu",
    "assistenz.zustand.sprechen": "Liest vor",
    "assistenz.zustand.ratlos": "Rückfrage – bitte entscheiden",
    "assistenz.zustand.freude": "Erledigt",
    "assistenz.zustand.fehler": "Fehlgeschlagen – Grund und nächster Schritt im Gespräch",
    "assistenz.zustand.pause": "Pausiert",
    "assistenz.zustand.fehler_quelle":
      "Keine geprüfte Quelle gefunden – die Antwort hat keine belastbare Grundlage",
    "assistenz.zustand.fehler_eingabe": "Eine Angabe fehlt noch – der Hinweis steht daneben",
    "assistenz.vorschau.starten": "Zustände ansehen",
    "assistenz.vorschau.startenLabel": "Vorschau der Zustände von „{{motiv}}“ starten",
    "assistenz.vorschau.titel": "Vorschau: {{motiv}}",
    "assistenz.vorschau.hinweis":
      "Nur eine Vorschau – sie ändert weder deine Auswahl noch Gespräche, Aufgaben oder KI-Zustände.",
    "assistenz.vorschau.schritt": "Vorschau {{nr}} von {{gesamt}}: {{zustand}}",
    "assistenz.vorschau.ruhig": "Bewegung reduziert – jeder Zustand wird still gezeigt.",
    "assistenz.vorschau.beenden": "Vorschau beenden",
    "assistenz.vorschau.fertig": "Vorschau beendet – nichts wurde geändert.",
  },
  en: {
    "assistenz.neutral.name": "Assistant",
    "assistenz.neutral.titel": "Your assistant",
    "assistenz.einrichtung.region": "Set up your personal assistant",
    "assistenz.einrichtung.frage": "What should your assistant be called?",
    "assistenz.einrichtung.kurz":
      "Give it a name of your own and choose one of thirteen motifs – for your account only.",
    "assistenz.einrichtung.starten": "Set up now",
    "assistenz.einrichtung.intro":
      "Give your assistant a name and choose a motif. This only applies to your account – sign-in, role and your organisation's AI settings stay unchanged.",
    "assistenz.einrichtung.speichern": "Save setup",
    "assistenz.einrichtung.spaeter": "Later",
    "assistenz.einrichtung.spaeterHinweis":
      "Setup is not finished yet and will be offered again the next time you sign in.",
    "assistenz.einrichtung.fertig":
      "Set up – {{name}} is with you from now on. You can change this at any time under Settings → Personal settings → My assistant.",
    "assistenz.einrichtung.schliessen": "Close",
    "assistenz.feld.name": "Your assistant's name",
    "assistenz.feld.nameHilfe": "1 to 40 characters, freely chosen. The name only applies to you.",
    "assistenz.fehler.nameLeer": "Please enter a name.",
    "assistenz.fehler.nameLang": "The name can be at most 40 characters long.",
    "assistenz.fehler.nameZeile":
      "Please use one line of text without line breaks or control characters.",
    "assistenz.fehler.avatarLeer": "Please choose a motif.",
    "assistenz.fehler.zusammen": "Please complete the marked fields – nothing has been saved yet.",
    "assistenz.avatar.legende": "Choose an avatar",
    "assistenz.avatar.gruppe.ausdrucksstark": "Expressive",
    "assistenz.avatar.gruppe.sachlich": "Matter-of-fact",
    "assistenz.avatar.gewaehlt": "Selected",
    "assistenz.avatar.vorschau": "Preview: {{name}} as {{motiv}}",
    "assistenz.avatar.originalHinweis": "the existing orange mascot",
    "assistenz.avatar.fehlt":
      "The saved motif is no longer offered. Until you choose a new one, a neutral placeholder is shown – your name is kept.",
    "assistenz.avatar.bildFehlt": "Image not available",
    "assistenz.avatar.ersatz": "Neutral placeholder",
    "assistenz.avatar.name.original": "Original",
    "assistenz.avatar.name.lichtwesen": "Light being",
    "assistenz.avatar.name.roboter": "Robot",
    "assistenz.avatar.name.eule": "Owl",
    "assistenz.avatar.name.fuchs": "Fox",
    "assistenz.avatar.name.pinguin": "Penguin",
    "assistenz.avatar.name.wolke": "Cloud",
    "assistenz.avatar.name.kompass": "Compass",
    "assistenz.avatar.name.prisma": "Prism",
    "assistenz.avatar.name.wissensbuch": "Book of knowledge",
    "assistenz.avatar.name.verbindungsknoten": "Connection node",
    "assistenz.avatar.name.monolith": "Monolith",
    "assistenz.avatar.name.leuchtkreis": "Circle of light",
    "assistenz.bewegung.label": "Reduce the figure's motion",
    "assistenz.bewegung.hilfe":
      "Turns off the figure's animations: every state stays visible as a calm expression and as text. If reduced motion is set in your system, it applies anyway.",
    "assistenz.speichern.laeuft": "Saving …",
    "assistenz.speichern.fehler":
      "Not saved: {{grund}} Your input stays in place; the previously saved state is kept.",
    "assistenz.speichern.netz": "The server could not be reached.",
    "assistenz.speichern.wiederholen": "Save again",
    "assistenz.speichern.abbrechen": "Cancel",
    "assistenz.laden.fehler": "The assistant profile could not be read right now.",
    "assistenz.laden.wiederholen": "Load again",
    "assistenz.einstellungen.titel": "My assistant",
    "assistenz.einstellungen.intro":
      "Name and motif of your personal assistant – change them separately or together. The change applies immediately in the open assistant and only to your account.",
    "assistenz.einstellungen.speichern": "Save",
    "assistenz.einstellungen.gespeichert": "Saved: {{name}} with the motif “{{motiv}}”.",
    "assistenz.einstellungen.unveraendert": "No change – there is nothing to save.",
    "assistenz.einstellungen.abgebrochen": "Cancelled – the previous choice stays.",
    "assistenz.einstellungen.offen": "Not set up yet",
    "assistenz.hilfe.oeffnen": "Open {{assistenz}} — help for this page",
    "assistenz.zustand.bereit": "Ready",
    "assistenz.zustand.warten": "Waiting for the answer",
    "assistenz.zustand.nachdenken": "Processing the request",
    "assistenz.zustand.zuhoeren": "Listening",
    "assistenz.zustand.sprechen": "Reading aloud",
    "assistenz.zustand.ratlos": "Question – please decide",
    "assistenz.zustand.freude": "Done",
    "assistenz.zustand.fehler": "Failed – reason and next step in the conversation",
    "assistenz.zustand.pause": "Paused",
    "assistenz.zustand.fehler_quelle": "No checked source found – the answer has no reliable basis",
    "assistenz.zustand.fehler_eingabe":
      "Some information is still missing – see the note next to it",
    "assistenz.vorschau.starten": "View states",
    "assistenz.vorschau.startenLabel": "Start the state preview for “{{motiv}}”",
    "assistenz.vorschau.titel": "Preview: {{motiv}}",
    "assistenz.vorschau.hinweis":
      "Only a preview – it changes neither your choice nor conversations, tasks or AI states.",
    "assistenz.vorschau.schritt": "Preview {{nr}} of {{gesamt}}: {{zustand}}",
    "assistenz.vorschau.ruhig": "Reduced motion – each state is shown still.",
    "assistenz.vorschau.beenden": "End preview",
    "assistenz.vorschau.fertig": "Preview ended – nothing was changed.",
  },
  nl: {
    "assistenz.neutral.name": "Assistent",
    "assistenz.neutral.titel": "Jouw assistent",
    "assistenz.einrichtung.region": "Persoonlijke assistent instellen",
    "assistenz.einrichtung.frage": "Hoe moet je assistent heten?",
    "assistenz.einrichtung.kurz":
      "Geef een eigen naam en kies een van dertien motieven – alleen voor jouw account.",
    "assistenz.einrichtung.starten": "Nu instellen",
    "assistenz.einrichtung.intro":
      "Geef je assistent een naam en kies een motief. Dit geldt alleen voor jouw account – aanmelding, rol en de AI-instellingen van je organisatie blijven ongewijzigd.",
    "assistenz.einrichtung.speichern": "Instelling opslaan",
    "assistenz.einrichtung.spaeter": "Later",
    "assistenz.einrichtung.spaeterHinweis":
      "De instelling is nog niet afgerond en wordt bij je volgende aanmelding opnieuw aangeboden.",
    "assistenz.einrichtung.fertig":
      "Ingesteld – {{name}} begeleidt je vanaf nu. Je kunt dit altijd wijzigen via Instellingen → Persoonlijke instellingen → Mijn assistent.",
    "assistenz.einrichtung.schliessen": "Sluiten",
    "assistenz.feld.name": "Naam van je assistent",
    "assistenz.feld.nameHilfe": "1 tot 40 tekens, vrij te kiezen. De naam geldt alleen voor jou.",
    "assistenz.fehler.nameLeer": "Vul een naam in.",
    "assistenz.fehler.nameLang": "De naam is maximaal 40 tekens lang.",
    "assistenz.fehler.nameZeile": "Gebruik één regel tekst zonder regeleinden of stuurtekens.",
    "assistenz.fehler.avatarLeer": "Kies een motief.",
    "assistenz.fehler.zusammen": "Vul de gemarkeerde velden aan – er is nog niets opgeslagen.",
    "assistenz.avatar.legende": "Avatar kiezen",
    "assistenz.avatar.gruppe.ausdrucksstark": "Expressief",
    "assistenz.avatar.gruppe.sachlich": "Zakelijk",
    "assistenz.avatar.gewaehlt": "Gekozen",
    "assistenz.avatar.vorschau": "Voorbeeld: {{name}} als {{motiv}}",
    "assistenz.avatar.originalHinweis": "de bestaande oranje mascotte",
    "assistenz.avatar.fehlt":
      "Het opgeslagen motief wordt niet meer aangeboden. Tot je een nieuw kiest, staat hier een neutrale vervangende afbeelding – je naam blijft behouden.",
    "assistenz.avatar.bildFehlt": "Afbeelding niet beschikbaar",
    "assistenz.avatar.ersatz": "Neutrale vervangende afbeelding",
    "assistenz.avatar.name.original": "Origineel",
    "assistenz.avatar.name.lichtwesen": "Lichtwezen",
    "assistenz.avatar.name.roboter": "Robot",
    "assistenz.avatar.name.eule": "Uil",
    "assistenz.avatar.name.fuchs": "Vos",
    "assistenz.avatar.name.pinguin": "Pinguïn",
    "assistenz.avatar.name.wolke": "Wolk",
    "assistenz.avatar.name.kompass": "Kompas",
    "assistenz.avatar.name.prisma": "Prisma",
    "assistenz.avatar.name.wissensbuch": "Kennisboek",
    "assistenz.avatar.name.verbindungsknoten": "Verbindingsknoop",
    "assistenz.avatar.name.monolith": "Monoliet",
    "assistenz.avatar.name.leuchtkreis": "Lichtcirkel",
    "assistenz.bewegung.label": "Beweging van de figuur beperken",
    "assistenz.bewegung.hilfe":
      "Zet de animaties van de figuur uit: elke toestand blijft zichtbaar als rustige uitdrukking en als tekst. Is beperkte beweging in je systeem ingesteld, dan geldt die sowieso.",
    "assistenz.speichern.laeuft": "Wordt opgeslagen …",
    "assistenz.speichern.fehler":
      "Niet opgeslagen: {{grund}} Je invoer blijft staan; de eerder opgeslagen stand blijft behouden.",
    "assistenz.speichern.netz": "De server was niet bereikbaar.",
    "assistenz.speichern.wiederholen": "Opnieuw opslaan",
    "assistenz.speichern.abbrechen": "Annuleren",
    "assistenz.laden.fehler": "Het assistentprofiel kon nu niet worden gelezen.",
    "assistenz.laden.wiederholen": "Opnieuw laden",
    "assistenz.einstellungen.titel": "Mijn assistent",
    "assistenz.einstellungen.intro":
      "Naam en motief van je persoonlijke assistent – apart of samen te wijzigen. De wijziging geldt meteen in de geopende assistent en alleen voor jouw account.",
    "assistenz.einstellungen.speichern": "Opslaan",
    "assistenz.einstellungen.gespeichert": "Opgeslagen: {{name}} met het motief ‘{{motiv}}’.",
    "assistenz.einstellungen.unveraendert": "Geen wijziging – er is niets op te slaan.",
    "assistenz.einstellungen.abgebrochen": "Geannuleerd – de vorige keuze blijft.",
    "assistenz.einstellungen.offen": "Nog niet ingesteld",
    "assistenz.hilfe.oeffnen": "{{assistenz}} openen — hulp bij deze pagina",
    "assistenz.zustand.bereit": "Klaar",
    "assistenz.zustand.warten": "Wacht op het antwoord",
    "assistenz.zustand.nachdenken": "Verwerkt het verzoek",
    "assistenz.zustand.zuhoeren": "Luistert",
    "assistenz.zustand.sprechen": "Leest voor",
    "assistenz.zustand.ratlos": "Vraag – kies alstublieft",
    "assistenz.zustand.freude": "Gelukt",
    "assistenz.zustand.fehler": "Mislukt – reden en volgende stap in het gesprek",
    "assistenz.zustand.pause": "Gepauzeerd",
    "assistenz.zustand.fehler_quelle":
      "Geen gecontroleerde bron gevonden – het antwoord heeft geen betrouwbare basis",
    "assistenz.zustand.fehler_eingabe": "Er ontbreekt nog een gegeven – zie de aanwijzing ernaast",
    "assistenz.vorschau.starten": "Toestanden bekijken",
    "assistenz.vorschau.startenLabel": "Voorbeeld van de toestanden van ‘{{motiv}}’ starten",
    "assistenz.vorschau.titel": "Voorbeeld: {{motiv}}",
    "assistenz.vorschau.hinweis":
      "Alleen een voorbeeld – het wijzigt je keuze, gesprekken, taken of AI-toestanden niet.",
    "assistenz.vorschau.schritt": "Voorbeeld {{nr}} van {{gesamt}}: {{zustand}}",
    "assistenz.vorschau.ruhig": "Beperkte beweging – elke toestand wordt stil getoond.",
    "assistenz.vorschau.beenden": "Voorbeeld beëindigen",
    "assistenz.vorschau.fertig": "Voorbeeld beëindigd – er is niets gewijzigd.",
  },
} satisfies Textmodul;
