// ================================================================================================
// AUFNAHME 20260922 · GESAMT-AUDITPROTOKOLL — die Texte der Prüfspur (Aktionsnamen, Kettenexport).
// ================================================================================================
//
// Diese Schlüssel standen bis zur I18N-AUFTEILUNG im Grundbestand von `i18n.ts` (Lauf 3 der
// Aufnahme). Bei der Zusammenführung mit main liegt der Grundbestand in `woerterbuch/`, und neue
// Texte gehören in ein Textmodul. Die Namen bleiben UNVERÄNDERT: `audit.action.*` wird aus dem
// Aktionsnamen des Belegs abgeleitet (`ko.revalidated` → `audit.action.ko_revalidated`), die
// `adm.sich.*`-Schlüssel nennt die Verwalterseite. Deshalb stehen alle in `legacySchluessel`.
// Wortlaute Zeichen für Zeichen aus dem Stand vor der Zusammenführung übernommen.
//
// Verwalteransicht (Teil 3 der Aufnahme): die Spalten- und Detailansichtstexte des Prüfprotokolls
// sind neu und tragen deshalb das Präfix `auditprotokoll.`.
import type { Textmodul } from "./intern/pruefung";

export default {
  praefix: "auditprotokoll.",
  legacySchluessel: [
    "audit.action.ko_revalidated",
    "audit.action.library_export",
    "audit.action.audit_exported",
    "audit.action.conflict_created",
    "audit.action.conflict_auto_created",
    "audit.action.conflict_escalated",
    "audit.action.conflict_resolved",
    "audit.action.conflict_dismissed",
    "audit.action.conflict_second_opinion",
    "audit.action.conflict_participant_removed",
    "audit.action.conflict_auto_resolved",
    "audit.action.conflict_superseded",
    // Aufnahme gesamt-konfliktklassifikation (R-0252): die Einordnung als Regel/Sache/Version.
    "audit.action.conflict_classified",
    "audit.action.overlap_auto_created",
    "audit.action.overlap_in_progress",
    "audit.action.overlap_dismissed",
    "audit.action.overlap_kept_separate",
    "audit.action.overlap_linked_related",
    "audit.action.overlap_superseded",
    "audit.action.overlap_participant_removed",
    "audit.action.overlap_withdrawn_own",
    "audit.action.ko_change_rolled_back",
    "audit.action.user_created",
    "audit.action.ko_source_removed_in_origin",
    "audit.action.ko_source_restored_in_origin",
    "audit.action.ko_source_attachments_synced",
    "audit.action.ko_source_restriction_synced",
    "audit.action.output_lms_export",
    // produkt:20261009:admin-audit-verstaendlich (K2): die Kontovorgänge ohne Namen — die
    // Auth-Ansicht zeigte sie bisher roh, und die Humanisierung „user delete" ist kein Name.
    "audit.action.user_delete",
    "audit.action.user_password_reset",
    "audit.action.user_password_changed",
    "audit.action.user_password_reset_email",
    "audit.action.user_access_expired",
    "audit.action.user_access_expiry_unreadable",
    "audit.action.user_access_expiry_set",
    "audit.action.user_oidc_linked",
    "audit.action.user_oidc_linked_unverified",
    "adm.sich.export.button",
    "adm.sich.export.done",
    "adm.sich.qualityNote",
  ],
  de: {
    // §12.3: Re-Validierung, Bibliotheks- und Kettenexport.
    "audit.action.ko_revalidated": "Neu validiert (stimmt noch)",
    "audit.action.library_export": "Bibliothek exportiert",
    "audit.action.audit_exported": "Prüfprotokoll exportiert",
    // R-0766 (Runde 2): Konfliktbelege erscheinen in der Herkunftskette am Objekt.
    "audit.action.conflict_created": "Konflikt gemeldet",
    "audit.action.conflict_auto_created": "Konflikt automatisch erkannt",
    "audit.action.conflict_escalated": "Konflikt eskaliert",
    "audit.action.conflict_resolved": "Konflikt entschieden",
    "audit.action.conflict_dismissed": "Konflikt als Fehlalarm geschlossen",
    "audit.action.conflict_second_opinion": "Zweitmeinung zum Konflikt",
    "audit.action.conflict_participant_removed": "Konfliktbeteiligtes Objekt entfernt",
    "audit.action.conflict_auto_resolved": "Konflikt automatisch geschlossen",
    "audit.action.conflict_superseded": "Konflikt durch neue Fassung überholt",
    "audit.action.conflict_classified": "Konflikt eingeordnet (Art der Arbeit)",
    // R-0766 (Runde 3): Überschneidungsbelege und die Rücknahme einer Änderung.
    "audit.action.overlap_auto_created": "Überschneidung erkannt",
    "audit.action.overlap_in_progress": "Überschneidung in Bearbeitung",
    "audit.action.overlap_dismissed": "Überschneidung als Fehlalarm geschlossen",
    "audit.action.overlap_kept_separate": "Überschneidung: bewusst getrennt gelassen",
    "audit.action.overlap_linked_related": "Überschneidung: als verwandt verknüpft",
    "audit.action.overlap_superseded": "Überschneidung durch neue Fassung überholt",
    "audit.action.overlap_participant_removed": "Beteiligtes Objekt der Überschneidung entfernt",
    "audit.action.overlap_withdrawn_own": "Überschneidung durch Rücknahme geschlossen",
    "audit.action.ko_change_rolled_back": "Änderung zurückgenommen",
    // Aktionsabdeckung (Nacharbeit 2): die Kontoanlage hat einen eigenen Beleg.
    "audit.action.user_created": "Konto angelegt",
    // Verwalteransicht (Bens Befund Nacharbeit 5): die Herkunftsbelege aus dem Quellabgleich
    // (`KoService`, Confluence-Import) tragen das Objekt als Ziel und erscheinen in Prüfprotokoll
    // und Objektspur — ohne Namen stand dort die Humanisierung „ko source removed in origin“.
    "audit.action.ko_source_removed_in_origin": "Quelle im Ursprungssystem gelöscht",
    "audit.action.ko_source_restored_in_origin": "Quelle im Ursprungssystem wiederhergestellt",
    "audit.action.ko_source_attachments_synced": "Anhänge der Quelle abgeglichen",
    "audit.action.ko_source_restriction_synced": "Leseeinschränkung der Quelle abgeglichen",
    // Bens Befund Nacharbeit 7: der SCORM-Export (`lms-export-routes.ts`) — Prüfprotokoll und, über
    // `objekte[].koId`, die Spur jedes exportierten Objekts.
    "audit.action.output_lms_export": "Für Lernplattform exportiert (SCORM)",
    "audit.action.user_delete": "Konto gelöscht",
    "audit.action.user_password_reset": "Passwort zurückgesetzt",
    "audit.action.user_password_changed": "Passwort geändert",
    "audit.action.user_password_reset_email": "Link zum Zurücksetzen des Passworts verschickt",
    "audit.action.user_access_expired": "Zugang abgelaufen",
    "audit.action.user_access_expiry_unreadable": "Ablaufdatum des Zugangs nicht lesbar",
    "audit.action.user_access_expiry_set": "Ablaufdatum des Zugangs gesetzt",
    "audit.action.user_oidc_linked": "Mit SSO-Konto verknüpft",
    "audit.action.user_oidc_linked_unverified": "Mit SSO-Konto verknüpft (Adresse unbestätigt)",
    "adm.sich.export.button": "Kette exportieren",
    "adm.sich.export.done":
      "Export mit {{count}} Einträgen gespeichert. Kopf der Kette: Nr. {{seq}} · {{hash}}. Wer diesen Kopf außerhalb der Anlage ablegt, erkennt dort später, ob die Kette bis zu diesem Punkt neu gebildet wurde.",
    "adm.sich.qualityNote":
      "Das Protokoll hält fest, wer was wann erfasst, geändert, geprüft und freigegeben hat. Solche Nachweise erwarten Managementsysteme wie ISO 9001 (Qualität) oder ISO/IEC 27001 (Informationssicherheit) von dokumentierten Abläufen. Eine Zertifizierung ersetzt das Protokoll nicht, und KLARWERK sagt keine zu. Es dient der Nachvollziehbarkeit des Wissens, nicht der Leistungsbewertung von Personen.",
    // Verwalteransicht (N-0027): Spaltenköpfe der Protokolltabelle und die Detailansicht, in der
    // die technischen Kennungen stehen — ergänzend, nicht statt der Namen.
    "auditprotokoll.spalte.zeit": "Zeitpunkt",
    "auditprotokoll.spalte.technik": "Technische Angaben",
    "auditprotokoll.technik.anzeigen": "Kennungen anzeigen",
    "auditprotokoll.technik.nr": "Eintrag Nr.",
    "auditprotokoll.technik.akteur": "Kennung ausführendes Konto",
    "auditprotokoll.technik.konto": "Kennung betroffenes Konto",
    "auditprotokoll.technik.objekt": "Kennung betroffenes Objekt",
    "auditprotokoll.technik.hash": "Prüfwert (Hash)",
    "auditprotokoll.technik.hilfe":
      "Die Spalten nennen Zeitpunkt mit Zeitzone, Ereignis, ausführende und betroffene Person oder den betroffenen Beitrag und beim Rollenwechsel die Rolle vorher und nachher. Die technischen Angaben jedes Eintrags (Eintragsnummer, gespeicherter Zeitpunkt in UTC, Rohaktion, Kennungen der Konten oder des Objekts, Prüfwert) stehen ergänzend unter „Kennungen anzeigen“. Ein gelöschtes Konto bleibt mit dem Namen benannt, den das Protokoll beim Löschen oder bei einem früheren Rollenwechsel gespeichert hat. Ein Name, den der Eintrag selbst nicht gespeichert hat, trägt den Zusatz „heutiger Name“ oder „Name aus anderem Protokolleintrag“. „Konto nicht mehr vorhanden“ steht nur, wenn die Kette ein Konto mit dieser Kennung belegt; sonst heißt sie „Unbekannte Kennung“.",
    // produkt:20261009:admin-audit-verstaendlich (ADMIN-03): Seiten, Filter, Herkunft der Namen,
    // Rücklinks, Prüfzeitpunkt.
    "auditprotokoll.tabelle.seite": "{{shown}} Einträge, neueste zuerst",
    "auditprotokoll.technik.zeitpunkt": "Gespeicherter Zeitpunkt (UTC)",
    "auditprotokoll.technik.aktion": "Rohaktion",
    "auditprotokoll.technik.geschwaerzt": "Ohne Leserecht ausgeblendet",
    "auditprotokoll.akteur.dienst": "Dienstzugang",
    "auditprotokoll.detail.unbekannt": "Unbekannte Kennung – kein Konto belegt",
    "auditprotokoll.filter.personHinweis":
      "Name wählen oder eine Kennung eingeben – auch entfernte oder unbekannte Akteure",
    "auditprotokoll.name.heute": "heutiger Name, im Eintrag nicht gespeichert",
    "auditprotokoll.name.ausProtokoll": "Name aus anderem Protokolleintrag",
    "auditprotokoll.kurzkennung": "Kennung {{kurz}}…",
    "auditprotokoll.objekt.ohneTitel": "Beitrag ohne Titel",
    "auditprotokoll.pruefung.ok":
      "Integrität geprüft ✓ am {{zeitpunkt}} — {{count}} Einträge, Kette lückenlos",
    "auditprotokoll.pruefung.ohneZeitpunkt":
      "Prüfergebnis ohne Prüfzeitpunkt – das ist kein Nachweis. Bitte die Integrität erneut prüfen.",
    "auditprotokoll.hilfe.konten":
      "Eine reine Auskunft: die Einträge zu Konten und Anmeldung, neueste zuerst und seitenweise, in derselben Darstellung wie das Prüfprotokoll — Zeitpunkt mit Zeitzone, Vorgang, ausführende und betroffene Person. Kennungen und Rohaktion stehen unter „Kennungen anzeigen“. Eingrenzen lässt sich nach Person, Vorgang, Betroffenem und Zeitraum; die Filter stehen in der Adresse und bleiben beim Zurückgehen erhalten. Hier lässt sich nichts ändern und nichts löschen — die Liste ist das Ergebnis dessen, was anderswo getan wurde. Die vollständige, hash-verkettete Kette samt Prüfknopf steht unter „Sicherheit und Nachweise“ im Prüfprotokoll.",
    "auditprotokoll.export.geschwaerzt":
      "{{count}} Einträge betreffen Beiträge, die Sie nicht öffnen dürfen; ihre Titel und Inhalte sind in der Datei ausgeblendet.",
    "auditprotokoll.filter.titel": "Einträge eingrenzen",
    "auditprotokoll.filter.person": "Person",
    "auditprotokoll.filter.personAlle": "Alle Personen",
    "auditprotokoll.filter.aktion": "Vorgang",
    "auditprotokoll.filter.aktionAlle": "Alle Vorgänge",
    "auditprotokoll.filter.ziel": "Betroffen (Kennung)",
    "auditprotokoll.filter.zielPlatzhalter": "Kennung aus „Kennungen anzeigen“",
    "auditprotokoll.filter.von": "Von (Tag)",
    "auditprotokoll.filter.bis": "Bis einschließlich",
    "auditprotokoll.filter.anwenden": "Filter anwenden",
    "auditprotokoll.filter.zuruecksetzen": "Filter zurücksetzen",
    "auditprotokoll.filter.zeitraumFalsch":
      "Der Zeitraum endet vor seinem Beginn. Bitte „Bis“ auf denselben oder einen späteren Tag setzen.",
    "auditprotokoll.zeitzone": "Tage und Zeiten in der Zeitzone {{zone}}",
    "auditprotokoll.leer.gefiltert": "Für diese Filter gibt es keine Einträge.",
    "auditprotokoll.seite.navigation": "Seiten des Protokolls",
    "auditprotokoll.seite.aelter": "Ältere Einträge",
    "auditprotokoll.seite.neueste": "Zu den neuesten Einträgen",
    "auditprotokoll.seite.ende": "Keine älteren Einträge.",
  },
  en: {
    "audit.action.ko_revalidated": "Revalidated (still valid)",
    "audit.action.library_export": "Library exported",
    "audit.action.audit_exported": "Audit log exported",
    "audit.action.conflict_created": "Conflict reported",
    "audit.action.conflict_auto_created": "Conflict detected automatically",
    "audit.action.conflict_escalated": "Conflict escalated",
    "audit.action.conflict_resolved": "Conflict decided",
    "audit.action.conflict_dismissed": "Conflict closed as false alarm",
    "audit.action.conflict_second_opinion": "Second opinion on conflict",
    "audit.action.conflict_participant_removed": "Object involved in conflict removed",
    "audit.action.conflict_auto_resolved": "Conflict closed automatically",
    "audit.action.conflict_superseded": "Conflict superseded by a new version",
    "audit.action.conflict_classified": "Conflict classified (kind of work)",
    "audit.action.overlap_auto_created": "Overlap detected",
    "audit.action.overlap_in_progress": "Overlap in progress",
    "audit.action.overlap_dismissed": "Overlap closed as false alarm",
    "audit.action.overlap_kept_separate": "Overlap: deliberately kept separate",
    "audit.action.overlap_linked_related": "Overlap: linked as related",
    "audit.action.overlap_superseded": "Overlap superseded by a new version",
    "audit.action.overlap_participant_removed": "Object involved in overlap removed",
    "audit.action.overlap_withdrawn_own": "Overlap closed by withdrawal",
    "audit.action.ko_change_rolled_back": "Change rolled back",
    "audit.action.user_created": "Account created",
    "audit.action.ko_source_removed_in_origin": "Source deleted in the origin system",
    "audit.action.ko_source_restored_in_origin": "Source restored in the origin system",
    "audit.action.ko_source_attachments_synced": "Source attachments synchronised",
    "audit.action.ko_source_restriction_synced": "Source read restriction synchronised",
    "audit.action.output_lms_export": "Exported for learning platform (SCORM)",
    "audit.action.user_delete": "Account deleted",
    "audit.action.user_password_reset": "Password reset",
    "audit.action.user_password_changed": "Password changed",
    "audit.action.user_password_reset_email": "Password reset link sent",
    "audit.action.user_access_expired": "Access expired",
    "audit.action.user_access_expiry_unreadable": "Access expiry date unreadable",
    "audit.action.user_access_expiry_set": "Access expiry date set",
    "audit.action.user_oidc_linked": "Linked to SSO account",
    "audit.action.user_oidc_linked_unverified": "Linked to SSO account (address unverified)",
    "adm.sich.export.button": "Export chain",
    "adm.sich.export.done":
      "Export with {{count}} entries saved. Head of the chain: no. {{seq}} · {{hash}}. Whoever stores this head outside the installation can later tell there whether the chain up to this point was rebuilt.",
    "adm.sich.qualityNote":
      "The log records who captured, changed, reviewed and approved what, and when. Management systems such as ISO 9001 (quality) or ISO/IEC 27001 (information security) expect this kind of evidence from documented processes. The log does not replace a certification, and KLARWERK does not promise one. It serves the traceability of knowledge, not the performance assessment of people.",
    "auditprotokoll.spalte.zeit": "Time",
    "auditprotokoll.spalte.technik": "Technical details",
    "auditprotokoll.technik.anzeigen": "Show IDs",
    "auditprotokoll.technik.nr": "Entry no.",
    "auditprotokoll.technik.akteur": "ID of performing account",
    "auditprotokoll.technik.konto": "ID of affected account",
    "auditprotokoll.technik.objekt": "ID of affected object",
    "auditprotokoll.technik.hash": "Check value (hash)",
    "auditprotokoll.technik.hilfe":
      "The columns name the time with time zone, the event, the performing and the affected person or the affected article and, for a role change, the role before and after. The technical details of every entry (entry number, stored time in UTC, raw action, identifiers of the accounts or the object, check value) are available in addition under “Show IDs”. A deleted account stays named with the name the trail stored when it was deleted or at an earlier role change. A name that the entry itself did not store carries the note “current name” or “name from another log entry”. “Account no longer exists” is shown only if the trail records an account with this ID; otherwise it reads “Unknown ID”.",
    "auditprotokoll.tabelle.seite": "{{shown}} entries, newest first",
    "auditprotokoll.technik.zeitpunkt": "Stored time (UTC)",
    "auditprotokoll.technik.aktion": "Raw action",
    "auditprotokoll.technik.geschwaerzt": "Hidden without read permission",
    "auditprotokoll.akteur.dienst": "Service access",
    "auditprotokoll.detail.unbekannt": "Unknown ID – no account on record",
    "auditprotokoll.filter.personHinweis":
      "Pick a name or enter an ID – including removed or unknown actors",
    "auditprotokoll.name.heute": "current name, not stored in the entry",
    "auditprotokoll.name.ausProtokoll": "name from another log entry",
    "auditprotokoll.kurzkennung": "ID {{kurz}}…",
    "auditprotokoll.objekt.ohneTitel": "Article without title",
    "auditprotokoll.pruefung.ok":
      "Integrity verified ✓ on {{zeitpunkt}} — {{count}} entries, chain intact",
    "auditprotokoll.pruefung.ohneZeitpunkt":
      "Check result without a check time – this is not evidence. Please verify the integrity again.",
    "auditprotokoll.hilfe.konten":
      "Pure information: the entries about accounts and sign-in, newest first and page by page, in the same presentation as the audit trail — time with time zone, event, performing and affected person. Identifiers and the raw action are under “Show IDs”. You can narrow the list by person, event, affected item and period; the filters are kept in the address and survive going back. Nothing can be changed or deleted here — the list is the result of what was done elsewhere. The complete hash-chained trail including its verify button lives under “Security and evidence” in the audit trail.",
    "auditprotokoll.export.geschwaerzt":
      "{{count}} entries concern articles you may not open; their titles and contents are hidden in the file.",
    "auditprotokoll.filter.titel": "Narrow down entries",
    "auditprotokoll.filter.person": "Person",
    "auditprotokoll.filter.personAlle": "All people",
    "auditprotokoll.filter.aktion": "Event",
    "auditprotokoll.filter.aktionAlle": "All events",
    "auditprotokoll.filter.ziel": "Affected (ID)",
    "auditprotokoll.filter.zielPlatzhalter": "ID from “Show IDs”",
    "auditprotokoll.filter.von": "From (day)",
    "auditprotokoll.filter.bis": "Up to and including",
    "auditprotokoll.filter.anwenden": "Apply filters",
    "auditprotokoll.filter.zuruecksetzen": "Reset filters",
    "auditprotokoll.filter.zeitraumFalsch":
      "The period ends before it begins. Please set “Up to” to the same or a later day.",
    "auditprotokoll.zeitzone": "Days and times in the time zone {{zone}}",
    "auditprotokoll.leer.gefiltert": "There are no entries for these filters.",
    "auditprotokoll.seite.navigation": "Pages of the log",
    "auditprotokoll.seite.aelter": "Older entries",
    "auditprotokoll.seite.neueste": "Back to the newest entries",
    "auditprotokoll.seite.ende": "No older entries.",
  },
  nl: {
    "audit.action.ko_revalidated": "Opnieuw gevalideerd (klopt nog)",
    "audit.action.library_export": "Bibliotheek geëxporteerd",
    "audit.action.audit_exported": "Auditlog geëxporteerd",
    "audit.action.conflict_created": "Conflict gemeld",
    "audit.action.conflict_auto_created": "Conflict automatisch herkend",
    "audit.action.conflict_escalated": "Conflict geëscaleerd",
    "audit.action.conflict_resolved": "Conflict beslist",
    "audit.action.conflict_dismissed": "Conflict als vals alarm gesloten",
    "audit.action.conflict_second_opinion": "Tweede mening over conflict",
    "audit.action.conflict_participant_removed": "Bij conflict betrokken object verwijderd",
    "audit.action.conflict_auto_resolved": "Conflict automatisch gesloten",
    "audit.action.conflict_superseded": "Conflict achterhaald door nieuwe versie",
    "audit.action.conflict_classified": "Conflict ingedeeld (soort werk)",
    "audit.action.overlap_auto_created": "Overlap herkend",
    "audit.action.overlap_in_progress": "Overlap in behandeling",
    "audit.action.overlap_dismissed": "Overlap als vals alarm gesloten",
    "audit.action.overlap_kept_separate": "Overlap: bewust gescheiden gehouden",
    "audit.action.overlap_linked_related": "Overlap: als verwant gekoppeld",
    "audit.action.overlap_superseded": "Overlap achterhaald door nieuwe versie",
    "audit.action.overlap_participant_removed": "Bij overlap betrokken object verwijderd",
    "audit.action.overlap_withdrawn_own": "Overlap gesloten door intrekking",
    "audit.action.ko_change_rolled_back": "Wijziging teruggedraaid",
    "audit.action.user_created": "Account aangemaakt",
    "audit.action.ko_source_removed_in_origin": "Bron in het herkomstsysteem verwijderd",
    "audit.action.ko_source_restored_in_origin": "Bron in het herkomstsysteem hersteld",
    "audit.action.ko_source_attachments_synced": "Bijlagen van de bron bijgewerkt",
    "audit.action.ko_source_restriction_synced": "Leesbeperking van de bron bijgewerkt",
    "audit.action.output_lms_export": "Geëxporteerd voor leerplatform (SCORM)",
    "audit.action.user_delete": "Account verwijderd",
    "audit.action.user_password_reset": "Wachtwoord opnieuw ingesteld",
    "audit.action.user_password_changed": "Wachtwoord gewijzigd",
    "audit.action.user_password_reset_email":
      "Link om het wachtwoord opnieuw in te stellen verstuurd",
    "audit.action.user_access_expired": "Toegang verlopen",
    "audit.action.user_access_expiry_unreadable": "Vervaldatum van de toegang onleesbaar",
    "audit.action.user_access_expiry_set": "Vervaldatum van de toegang ingesteld",
    "audit.action.user_oidc_linked": "Gekoppeld aan SSO-account",
    "audit.action.user_oidc_linked_unverified": "Gekoppeld aan SSO-account (adres onbevestigd)",
    "adm.sich.export.button": "Keten exporteren",
    "adm.sich.export.done":
      "Export met {{count}} items opgeslagen. Kop van de keten: nr. {{seq}} · {{hash}}. Wie deze kop buiten de installatie bewaart, kan daar later zien of de keten tot dit punt opnieuw is opgebouwd.",
    "adm.sich.qualityNote":
      "Het logboek legt vast wie wat wanneer heeft vastgelegd, gewijzigd, gecontroleerd en vrijgegeven. Managementsystemen zoals ISO 9001 (kwaliteit) of ISO/IEC 27001 (informatiebeveiliging) verwachten zulk bewijs van gedocumenteerde processen. Het logboek vervangt geen certificering, en KLARWERK belooft er geen. Het dient de herleidbaarheid van kennis, niet de beoordeling van personen.",
    "auditprotokoll.spalte.zeit": "Tijdstip",
    "auditprotokoll.spalte.technik": "Technische gegevens",
    "auditprotokoll.technik.anzeigen": "ID's tonen",
    "auditprotokoll.technik.nr": "Vermelding nr.",
    "auditprotokoll.technik.akteur": "ID uitvoerend account",
    "auditprotokoll.technik.konto": "ID betrokken account",
    "auditprotokoll.technik.objekt": "ID betrokken object",
    "auditprotokoll.technik.hash": "Controlewaarde (hash)",
    "auditprotokoll.technik.hilfe":
      "De kolommen noemen het tijdstip met tijdzone, de gebeurtenis, de uitvoerende en de betrokken persoon of de betrokken bijdrage en bij een rolwijziging de rol daarvoor en daarna. De technische gegevens van elke vermelding (vermeldingsnummer, opgeslagen tijdstip in UTC, ruwe actie, kenmerken van de accounts of het object, controlewaarde) staan aanvullend onder „ID's tonen“. Een verwijderd account blijft benoemd met de naam die het protocol bij het verwijderen of bij een eerdere rolwijziging heeft opgeslagen. Een naam die de vermelding zelf niet heeft opgeslagen, krijgt de toevoeging „huidige naam” of „naam uit andere logvermelding”. „Account bestaat niet meer” staat er alleen als het logboek een account met deze ID vastlegt; anders heet ze „Onbekende ID”.",
    "auditprotokoll.tabelle.seite": "{{shown}} vermeldingen, nieuwste eerst",
    "auditprotokoll.technik.zeitpunkt": "Opgeslagen tijdstip (UTC)",
    "auditprotokoll.technik.aktion": "Ruwe actie",
    "auditprotokoll.technik.geschwaerzt": "Verborgen zonder leesrecht",
    "auditprotokoll.akteur.dienst": "Diensttoegang",
    "auditprotokoll.detail.unbekannt": "Onbekende ID – geen account vastgelegd",
    "auditprotokoll.filter.personHinweis":
      "Kies een naam of voer een ID in – ook verwijderde of onbekende actoren",
    "auditprotokoll.name.heute": "huidige naam, niet in de vermelding opgeslagen",
    "auditprotokoll.name.ausProtokoll": "naam uit andere logvermelding",
    "auditprotokoll.kurzkennung": "ID {{kurz}}…",
    "auditprotokoll.objekt.ohneTitel": "Bijdrage zonder titel",
    "auditprotokoll.pruefung.ok":
      "Integriteit gecontroleerd ✓ op {{zeitpunkt}} — {{count}} vermeldingen, keten sluitend",
    "auditprotokoll.pruefung.ohneZeitpunkt":
      "Controleresultaat zonder controletijdstip – dit is geen bewijs. Controleer de integriteit opnieuw.",
    "auditprotokoll.hilfe.konten":
      "Een zuivere inlichting: de regels over accounts en aanmelding, nieuwste eerst en per pagina, in dezelfde weergave als het controleprotocol — tijdstip met tijdzone, gebeurtenis, uitvoerende en betrokken persoon. Kenmerken en de ruwe actie staan onder „ID's tonen“. U kunt afbakenen op persoon, gebeurtenis, betrokkene en periode; de filters staan in het adres en blijven bij teruggaan behouden. Hier valt niets te wijzigen en niets te verwijderen — de lijst is het resultaat van wat elders is gedaan. De volledige, hash-geketende keten met haar controleknop staat onder „Veiligheid en bewijs“ in het controleprotocol.",
    "auditprotokoll.export.geschwaerzt":
      "{{count}} vermeldingen betreffen bijdragen die u niet mag openen; hun titels en inhoud zijn in het bestand verborgen.",
    "auditprotokoll.filter.titel": "Vermeldingen afbakenen",
    "auditprotokoll.filter.person": "Persoon",
    "auditprotokoll.filter.personAlle": "Alle personen",
    "auditprotokoll.filter.aktion": "Gebeurtenis",
    "auditprotokoll.filter.aktionAlle": "Alle gebeurtenissen",
    "auditprotokoll.filter.ziel": "Betrokken (ID)",
    "auditprotokoll.filter.zielPlatzhalter": "ID uit „ID's tonen“",
    "auditprotokoll.filter.von": "Van (dag)",
    "auditprotokoll.filter.bis": "Tot en met",
    "auditprotokoll.filter.anwenden": "Filters toepassen",
    "auditprotokoll.filter.zuruecksetzen": "Filters wissen",
    "auditprotokoll.filter.zeitraumFalsch":
      "De periode eindigt vóór het begin. Zet „Tot en met” op dezelfde of een latere dag.",
    "auditprotokoll.zeitzone": "Dagen en tijden in de tijdzone {{zone}}",
    "auditprotokoll.leer.gefiltert": "Er zijn geen vermeldingen voor deze filters.",
    "auditprotokoll.seite.navigation": "Pagina's van het logboek",
    "auditprotokoll.seite.aelter": "Oudere vermeldingen",
    "auditprotokoll.seite.neueste": "Naar de nieuwste vermeldingen",
    "auditprotokoll.seite.ende": "Geen oudere vermeldingen.",
  },
} satisfies Textmodul;
