// ================================================================================================
// INTERNER CHAT — die Texte der Seite `/chat`, der Gesprächsknöpfe an Artikel und Space, des
// Konto-Menüs und des Klara-Knopfs „Als Nachricht entwerfen".
// ================================================================================================
//
// Auftrag `produkt:20261007:interner-chat`. DE/EN/NL, weil der Textmodulvertrag jede Sprache der
// Oberfläche verlangt (docs/i18n-textmodule.md).
import type { Textmodul } from "./intern/pruefung";

export default {
  praefix: "chat.",
  legacySchluessel: [],
  de: {
    "chat.seite.titel": "Interner Chat",
    "chat.seite.lead":
      "Direkt-, Gruppen-, Space- und Artikelgespräche. Was du siehst, folgt deinen Rechten an Space und Artikel — auch nachträglich.",
    "chat.seite.laedt": "Gespräche werden geladen …",
    "chat.seite.fehler": "Dieses Gespräch gibt es nicht oder du darfst es nicht lesen.",
    "chat.seite.zurueck": "Alle Gespräche",
    "chat.liste.titel": "Gespräche",
    "chat.liste.leer": "Noch kein Gespräch, das du lesen darfst.",
    "chat.liste.anzahl": "{{anzahl}} Nachrichten",
    "chat.art.direkt": "Direkt",
    "chat.art.gruppe": "Gruppe",
    "chat.art.space": "Space",
    "chat.art.artikel": "Artikel",
    "chat.sichtbarkeit.persoenlich": "Persönlich",
    "chat.sichtbarkeit.geteilt": "Geteilt",
    "chat.neu.titel": "Neues Gespräch",
    "chat.neu.art": "Art",
    "chat.neu.person": "Person",
    "chat.neu.gruppenname": "Name der Gruppe",
    "chat.neu.mitglieder": "Mitglieder",
    "chat.neu.space": "Space",
    "chat.neu.keinSpace": "Kein Space, dessen Inhalte du lesen darfst.",
    "chat.neu.waehlen": "Bitte wählen",
    "chat.neu.oeffnen": "Gespräch öffnen",
    "chat.erwaehnungen.titel": "Erwähnungen",
    "chat.erwaehnungen.leer": "Niemand hat dich erwähnt.",
    "chat.erwaehnungen.eintrag": "{{wer}} in „{{gespraech}}“",
    "chat.gespraech.waehlen": "Wähle ein Gespräch oder beginne ein neues.",
    "chat.gespraech.teilnehmer": "Teilnehmende: {{namen}}",
    "chat.gespraech.zumArtikel": "Zum Artikel: {{titel}} · Fassung {{fassung}}",
    "chat.gespraech.zumSpace": "Zum Space: {{name}}",
    "chat.gespraech.leer": "Noch keine Nachricht.",
    "chat.verlauf.aeltere": "Ältere Nachrichten laden",
    "chat.ziel.titel": "Erwähnte Nachricht",
    "chat.ziel.fehlt": "Diese Nachricht ist nicht (mehr) verfügbar.",
    "chat.nachricht.ich": "Du",
    "chat.nachricht.unbekannt": "Unbekanntes Konto",
    "chat.nachricht.ausKlara": "Aus Klara übernommen",
    "chat.nachricht.erwaehnt": "Erwähnt: {{namen}}",
    "chat.nachricht.verweis": "Artikel: {{titel}} · Fassung {{fassung}}",
    "chat.nachricht.verweisGesperrt": "Verwiesener Artikel nicht verfügbar",
    "chat.nachricht.anhang": "Anhang: {{name}}",
    "chat.nachricht.anhangGesperrt": "Anhang nicht verfügbar",
    "chat.nachricht.ausschnitt": "Ausschnitt aus „{{quelle}}“",
    "chat.nachricht.ausschnittFassung": "Fassung {{fassung}}",
    "chat.nachricht.ausschnittFiktiv": "Fiktive Markierung aus der Klara-Vorschau",
    "chat.nachricht.ausschnittGesperrt":
      "Ausschnitt nicht verfügbar — du darfst die Quelle nicht (mehr) sehen.",
    "chat.nachricht.zurQuelle": "Zur Quelle",
    "chat.status.gesendet": "Gesendet",
    "chat.status.laeuft": "Wird gesendet …",
    "chat.status.fehlgeschlagen": "Nicht gesendet: {{grund}}",
    "chat.status.erneut": "Erneut senden",
    "chat.status.verwerfen": "Verwerfen",
    "chat.wissen.knopf": "In Wissen übernehmen",
    "chat.wissen.laeuft": "Wird übernommen …",
    "chat.wissen.erfolgt": "Von dir als persönlicher Entwurf übernommen",
    "chat.wissen.oeffnen": "Entwurf öffnen",
    "chat.wissen.fehler": "Die Übernahme ist nicht gelungen.",
    "chat.wissen.herkunftPersoenlich": "aus einer persönlichen Nachricht",
    "chat.wissen.herkunftGeteilt": "aus einer geteilten Nachricht",
    "chat.eingabe.label": "Nachricht",
    "chat.eingabe.platzhalter": "Nachricht schreiben …",
    "chat.eingabe.erwaehnen": "Person erwähnen",
    "chat.eingabe.erwaehnenWaehlen": "Erwähnen …",
    "chat.eingabe.entfernen": "Erwähnung entfernen: {{name}}",
    "chat.eingabe.anhaenge": "Anhänge des Artikels mitsenden",
    "chat.eingabe.senden": "Senden",
    "chat.eingabe.hinweisLinks":
      "Links auf Artikel (/wissen/…) zeigen jeder Person nur, was sie sehen darf.",
    "chat.klara.ausKlara": "Als Nachricht entwerfen",
    "chat.klara.titel": "Nachrichtenentwurf aus Klara",
    "chat.klara.hinweis":
      "Erst „Senden“ macht daraus eine Nachricht. Bis dahin geht nichts an andere.",
    "chat.klara.ziel": "An",
    "chat.klara.zielWaehlen": "Gespräch wählen",
    "chat.klara.keinZiel": "Noch kein Gespräch — beginne zuerst ein neues.",
    "chat.klara.empfaenger": "Empfänger: {{titel}} ({{art}} · {{sichtbarkeit}})",
    "chat.klara.keinEmpfaenger": "Noch kein Empfänger gewählt.",
    "chat.klara.text": "Text",
    "chat.klara.vorschlag": "Zur Markierung aus „{{quelle}}“:",
    "chat.klara.senden": "Senden",
    "chat.klara.verwerfen": "Verwerfen",
    "chat.klara.laeuft": "Wird gesendet …",
    "chat.klara.fehler": "Nicht gesendet: {{grund}}",
    "chat.klara.erneut": "Erneut senden",
    "chat.fehler.allgemein": "Das hat nicht geklappt.",
    "chat.fehler.netz": "Keine Verbindung zum Server.",
    "chat.fehler.erwaehnung": "Erwähnt werden kann nur, wer dieses Gespräch lesen darf.",
    "chat.fehler.verweis": "Ein verwiesener Artikel oder Anhang ist nicht verfügbar.",
    "chat.artikel.knopf": "Gespräch zu diesem Artikel",
    "chat.space.knopf": "Gespräch im Space",
    "chat.konto.menue": "Interner Chat",
  },
  en: {
    "chat.seite.titel": "Internal chat",
    "chat.seite.lead":
      "Direct, group, space and article conversations. What you see follows your rights to space and article — also later on.",
    "chat.seite.laedt": "Loading conversations …",
    "chat.seite.fehler": "This conversation does not exist or you may not read it.",
    "chat.seite.zurueck": "All conversations",
    "chat.liste.titel": "Conversations",
    "chat.liste.leer": "No conversation you may read yet.",
    "chat.liste.anzahl": "{{anzahl}} messages",
    "chat.art.direkt": "Direct",
    "chat.art.gruppe": "Group",
    "chat.art.space": "Space",
    "chat.art.artikel": "Article",
    "chat.sichtbarkeit.persoenlich": "Personal",
    "chat.sichtbarkeit.geteilt": "Shared",
    "chat.neu.titel": "New conversation",
    "chat.neu.art": "Type",
    "chat.neu.person": "Person",
    "chat.neu.gruppenname": "Group name",
    "chat.neu.mitglieder": "Members",
    "chat.neu.space": "Space",
    "chat.neu.keinSpace": "No space whose content you may read.",
    "chat.neu.waehlen": "Please choose",
    "chat.neu.oeffnen": "Open conversation",
    "chat.erwaehnungen.titel": "Mentions",
    "chat.erwaehnungen.leer": "Nobody has mentioned you.",
    "chat.erwaehnungen.eintrag": "{{wer}} in “{{gespraech}}”",
    "chat.gespraech.waehlen": "Choose a conversation or start a new one.",
    "chat.gespraech.teilnehmer": "Participants: {{namen}}",
    "chat.gespraech.zumArtikel": "To the article: {{titel}} · version {{fassung}}",
    "chat.gespraech.zumSpace": "To the space: {{name}}",
    "chat.gespraech.leer": "No message yet.",
    "chat.verlauf.aeltere": "Load older messages",
    "chat.ziel.titel": "Mentioned message",
    "chat.ziel.fehlt": "This message is not (or no longer) available.",
    "chat.nachricht.ich": "You",
    "chat.nachricht.unbekannt": "Unknown account",
    "chat.nachricht.ausKlara": "Taken from Klara",
    "chat.nachricht.erwaehnt": "Mentioned: {{namen}}",
    "chat.nachricht.verweis": "Article: {{titel}} · version {{fassung}}",
    "chat.nachricht.verweisGesperrt": "Referenced article not available",
    "chat.nachricht.anhang": "Attachment: {{name}}",
    "chat.nachricht.anhangGesperrt": "Attachment not available",
    "chat.nachricht.ausschnitt": "Excerpt from “{{quelle}}”",
    "chat.nachricht.ausschnittFassung": "Version {{fassung}}",
    "chat.nachricht.ausschnittFiktiv": "Fictional selection from the Klara preview",
    "chat.nachricht.ausschnittGesperrt":
      "Excerpt not available — you may not (or no longer) see the source.",
    "chat.nachricht.zurQuelle": "To the source",
    "chat.status.gesendet": "Sent",
    "chat.status.laeuft": "Sending …",
    "chat.status.fehlgeschlagen": "Not sent: {{grund}}",
    "chat.status.erneut": "Send again",
    "chat.status.verwerfen": "Discard",
    "chat.wissen.knopf": "Take into knowledge",
    "chat.wissen.laeuft": "Taking over …",
    "chat.wissen.erfolgt": "Taken over by you as a personal draft",
    "chat.wissen.oeffnen": "Open draft",
    "chat.wissen.fehler": "Taking over did not work.",
    "chat.wissen.herkunftPersoenlich": "from a personal message",
    "chat.wissen.herkunftGeteilt": "from a shared message",
    "chat.eingabe.label": "Message",
    "chat.eingabe.platzhalter": "Write a message …",
    "chat.eingabe.erwaehnen": "Mention a person",
    "chat.eingabe.erwaehnenWaehlen": "Mention …",
    "chat.eingabe.entfernen": "Remove mention: {{name}}",
    "chat.eingabe.anhaenge": "Send attachments of the article",
    "chat.eingabe.senden": "Send",
    "chat.eingabe.hinweisLinks":
      "Links to articles (/wissen/…) show each person only what they may see.",
    "chat.klara.ausKlara": "Draft as message",
    "chat.klara.titel": "Message draft from Klara",
    "chat.klara.hinweis":
      "Only “Send” turns this into a message. Until then nothing goes to others.",
    "chat.klara.ziel": "To",
    "chat.klara.zielWaehlen": "Choose conversation",
    "chat.klara.keinZiel": "No conversation yet — start a new one first.",
    "chat.klara.empfaenger": "Recipient: {{titel}} ({{art}} · {{sichtbarkeit}})",
    "chat.klara.keinEmpfaenger": "No recipient chosen yet.",
    "chat.klara.text": "Text",
    "chat.klara.vorschlag": "About the selection from “{{quelle}}”:",
    "chat.klara.senden": "Send",
    "chat.klara.verwerfen": "Discard",
    "chat.klara.laeuft": "Sending …",
    "chat.klara.fehler": "Not sent: {{grund}}",
    "chat.klara.erneut": "Send again",
    "chat.fehler.allgemein": "That did not work.",
    "chat.fehler.netz": "No connection to the server.",
    "chat.fehler.erwaehnung": "Only people who may read this conversation can be mentioned.",
    "chat.fehler.verweis": "A referenced article or attachment is not available.",
    "chat.artikel.knopf": "Conversation about this article",
    "chat.space.knopf": "Conversation in the space",
    "chat.konto.menue": "Internal chat",
  },
  nl: {
    "chat.seite.titel": "Interne chat",
    "chat.seite.lead":
      "Directe, groeps-, space- en artikelgesprekken. Wat je ziet, volgt je rechten op space en artikel — ook achteraf.",
    "chat.seite.laedt": "Gesprekken worden geladen …",
    "chat.seite.fehler": "Dit gesprek bestaat niet of je mag het niet lezen.",
    "chat.seite.zurueck": "Alle gesprekken",
    "chat.liste.titel": "Gesprekken",
    "chat.liste.leer": "Nog geen gesprek dat je mag lezen.",
    "chat.liste.anzahl": "{{anzahl}} berichten",
    "chat.art.direkt": "Direct",
    "chat.art.gruppe": "Groep",
    "chat.art.space": "Space",
    "chat.art.artikel": "Artikel",
    "chat.sichtbarkeit.persoenlich": "Persoonlijk",
    "chat.sichtbarkeit.geteilt": "Gedeeld",
    "chat.neu.titel": "Nieuw gesprek",
    "chat.neu.art": "Soort",
    "chat.neu.person": "Persoon",
    "chat.neu.gruppenname": "Naam van de groep",
    "chat.neu.mitglieder": "Leden",
    "chat.neu.space": "Space",
    "chat.neu.keinSpace": "Geen space waarvan je de inhoud mag lezen.",
    "chat.neu.waehlen": "Maak een keuze",
    "chat.neu.oeffnen": "Gesprek openen",
    "chat.erwaehnungen.titel": "Vermeldingen",
    "chat.erwaehnungen.leer": "Niemand heeft je vermeld.",
    "chat.erwaehnungen.eintrag": "{{wer}} in „{{gespraech}}”",
    "chat.gespraech.waehlen": "Kies een gesprek of begin een nieuw gesprek.",
    "chat.gespraech.teilnehmer": "Deelnemers: {{namen}}",
    "chat.gespraech.zumArtikel": "Naar het artikel: {{titel}} · versie {{fassung}}",
    "chat.gespraech.zumSpace": "Naar de space: {{name}}",
    "chat.gespraech.leer": "Nog geen bericht.",
    "chat.verlauf.aeltere": "Oudere berichten laden",
    "chat.ziel.titel": "Vermeld bericht",
    "chat.ziel.fehlt": "Dit bericht is niet (meer) beschikbaar.",
    "chat.nachricht.ich": "Jij",
    "chat.nachricht.unbekannt": "Onbekend account",
    "chat.nachricht.ausKlara": "Overgenomen uit Klara",
    "chat.nachricht.erwaehnt": "Vermeld: {{namen}}",
    "chat.nachricht.verweis": "Artikel: {{titel}} · versie {{fassung}}",
    "chat.nachricht.verweisGesperrt": "Verwezen artikel niet beschikbaar",
    "chat.nachricht.anhang": "Bijlage: {{name}}",
    "chat.nachricht.anhangGesperrt": "Bijlage niet beschikbaar",
    "chat.nachricht.ausschnitt": "Fragment uit „{{quelle}}”",
    "chat.nachricht.ausschnittFassung": "Versie {{fassung}}",
    "chat.nachricht.ausschnittFiktiv": "Fictieve markering uit de Klara-preview",
    "chat.nachricht.ausschnittGesperrt":
      "Fragment niet beschikbaar — je mag de bron niet (meer) zien.",
    "chat.nachricht.zurQuelle": "Naar de bron",
    "chat.status.gesendet": "Verzonden",
    "chat.status.laeuft": "Wordt verzonden …",
    "chat.status.fehlgeschlagen": "Niet verzonden: {{grund}}",
    "chat.status.erneut": "Opnieuw verzenden",
    "chat.status.verwerfen": "Verwerpen",
    "chat.wissen.knopf": "Overnemen in kennis",
    "chat.wissen.laeuft": "Wordt overgenomen …",
    "chat.wissen.erfolgt": "Door jou overgenomen als persoonlijk concept",
    "chat.wissen.oeffnen": "Concept openen",
    "chat.wissen.fehler": "Overnemen is niet gelukt.",
    "chat.wissen.herkunftPersoenlich": "uit een persoonlijk bericht",
    "chat.wissen.herkunftGeteilt": "uit een gedeeld bericht",
    "chat.eingabe.label": "Bericht",
    "chat.eingabe.platzhalter": "Bericht schrijven …",
    "chat.eingabe.erwaehnen": "Persoon vermelden",
    "chat.eingabe.erwaehnenWaehlen": "Vermelden …",
    "chat.eingabe.entfernen": "Vermelding verwijderen: {{name}}",
    "chat.eingabe.anhaenge": "Bijlagen van het artikel meesturen",
    "chat.eingabe.senden": "Verzenden",
    "chat.eingabe.hinweisLinks":
      "Links naar artikelen (/wissen/…) tonen iedereen alleen wat hij of zij mag zien.",
    "chat.klara.ausKlara": "Als bericht opstellen",
    "chat.klara.titel": "Berichtconcept uit Klara",
    "chat.klara.hinweis":
      "Pas „Verzenden” maakt hier een bericht van. Tot dan gaat er niets naar anderen.",
    "chat.klara.ziel": "Aan",
    "chat.klara.zielWaehlen": "Gesprek kiezen",
    "chat.klara.keinZiel": "Nog geen gesprek — begin eerst een nieuw gesprek.",
    "chat.klara.empfaenger": "Ontvanger: {{titel}} ({{art}} · {{sichtbarkeit}})",
    "chat.klara.keinEmpfaenger": "Nog geen ontvanger gekozen.",
    "chat.klara.text": "Tekst",
    "chat.klara.vorschlag": "Over de markering uit „{{quelle}}”:",
    "chat.klara.senden": "Verzenden",
    "chat.klara.verwerfen": "Verwerpen",
    "chat.klara.laeuft": "Wordt verzonden …",
    "chat.klara.fehler": "Niet verzonden: {{grund}}",
    "chat.klara.erneut": "Opnieuw verzenden",
    "chat.fehler.allgemein": "Dat is niet gelukt.",
    "chat.fehler.netz": "Geen verbinding met de server.",
    "chat.fehler.erwaehnung": "Alleen wie dit gesprek mag lezen, kan worden vermeld.",
    "chat.fehler.verweis": "Een verwezen artikel of bijlage is niet beschikbaar.",
    "chat.artikel.knopf": "Gesprek over dit artikel",
    "chat.space.knopf": "Gesprek in de space",
    "chat.konto.menue": "Interne chat",
  },
} satisfies Textmodul;
