// ================================================================================================
// BETROFFENENRECHTE · die Texte von „Meine Daten", Löschantrag und Verarbeitungsverzeichnis.
// ================================================================================================
//
// Die Texte sagen, was ein Antrag bewirkt und was NICHT: er löscht noch nichts, er wird zur Aufgabe
// der Verwaltung mit Frist; erledigt löscht er Konto und Anmeldesitzungen über den vorhandenen
// Löschweg — Beiträge, Kommentare und Protokollzeilen bleiben mit der Kennung stehen (das Umschreiben
// auf „ehemalige Person" ist ein gesonderter, offener Auftrag).
import type { Textmodul } from "./intern/pruefung";

export default {
  praefix: "datenschutz.",
  legacySchluessel: [],
  de: {
    "datenschutz.meineDaten.titel": "Meine Daten",
    "datenschutz.meineDaten.wert": "Ansehen und herunterladen",
    "datenschutz.meineDaten.herunterladen": "Alles herunterladen (JSON)",
    "datenschutz.meineDaten.laeuft": "Wird zusammengestellt …",
    "datenschutz.meineDaten.stand": "Stand {{zeit}}",
    "datenschutz.meineDaten.nichtAbrufbar": "nicht abrufbar",
    "datenschutz.meineDaten.nichtEnthalten": "Nicht in der Datei",
    "datenschutz.meineDaten.bereich.eigeneObjekte": "Eigene Wissensobjekte",
    "datenschutz.meineDaten.bereich.bearbeitungen": "Bearbeitete Fassungen",
    "datenschutz.meineDaten.bereich.kommentare": "Kommentare",
    "datenschutz.meineDaten.bereich.entwuerfe": "Entwürfe",
    "datenschutz.meineDaten.bereich.fragen": "Gestellte Fragen",
    "datenschutz.meineDaten.bereich.antworten": "Erhaltene Antworten",
    "datenschutz.meineDaten.bereich.bewertungen": "Bewertungen",
    "datenschutz.meineDaten.bereich.zuweisungen": "Prüfzuweisungen",
    "datenschutz.meineDaten.bereich.kenntnisnahmen": "Kenntnisnahmen",
    "datenschutz.meineDaten.bereich.anhaenge": "Hochgeladene Dateien",
    "datenschutz.meineDaten.bereich.lernpfade": "Lernpfade",
    "datenschutz.meineDaten.bereich.loeschantraege": "Löschanträge",
    "datenschutz.meineDaten.bereich.nachfolge": "Nachfolge bei Befristung",
    "datenschutz.meineDaten.bereich.protokoll": "Protokollzeilen",
    "datenschutz.meineDaten.bereich.kiLaeufe": "Angefragte KI-Läufe",
    "datenschutz.meineDaten.bereich.klaraSitzungen": "Klara-Sitzungen",
    "datenschutz.meineDaten.bereich.klaraZustimmungen": "Zustimmungen zur externen KI",
    "datenschutz.meineDaten.uebergabe": "Übergabe",
    "datenschutz.meineDaten.uebergabe.verantwortlich": "Verantwortete Wissensobjekte",
    "datenschutz.meineDaten.uebergabe.autor": "Als Autor geführt",
    "datenschutz.meineDaten.uebergabe.pruefung": "Offene Prüfzuweisungen",
    "datenschutz.meineDaten.uebergabe.fragen": "Zugewiesene offene Fragen",
    "datenschutz.meineDaten.uebergabe.nachfolge": "Nachfolge für neue Beiträge",
    "datenschutz.antrag.titel": "Konto löschen lassen",
    "datenschutz.antrag.wirkung":
      "Ein Antrag löscht noch nichts. Er geht als Aufgabe mit Frist an die Verwaltung. Wird er erledigt, werden dein Konto und deine Anmeldesitzungen gelöscht; Beiträge, Kommentare und Protokollzeilen bleiben mit deiner Kennung stehen.",
    "datenschutz.antrag.begruendung": "Begründung (optional)",
    "datenschutz.antrag.stellen": "Löschung beantragen",
    "datenschutz.antrag.laeuft": "Wird gesendet …",
    "datenschutz.antrag.offen": "Dein Antrag vom {{gestellt}} ist offen. Frist: {{frist}}.",
    "datenschutz.antrag.ueberfaellig": "Die Frist ist verstrichen.",
    "datenschutz.antrag.zurueckziehen": "Antrag zurückziehen",
    "datenschutz.antrag.verlauf": "Frühere Anträge",
    "datenschutz.status.offen": "Offen",
    "datenschutz.status.in_bearbeitung": "Wird gerade bearbeitet",
    "datenschutz.status.erledigt": "Erledigt",
    "datenschutz.status.abgelehnt": "Abgelehnt",
    "datenschutz.status.zurueckgezogen": "Zurückgezogen",
    "datenschutz.fehler.BEREITS_OFFEN": "Es gibt bereits einen offenen Antrag.",
    "datenschutz.fehler.NICHT_OFFEN": "Der Antrag ist nicht mehr offen.",
    "datenschutz.fehler.ZU_LANG": "Der Text ist zu lang.",
    "datenschutz.fehler.GRUND_FEHLT": "Eine Ablehnung braucht einen Grund.",
    "datenschutz.fehler.NICHT_HALTBAR":
      "Diese Instanz kann Anträge nicht dauerhaft speichern; deshalb wird nichts angenommen.",
    "datenschutz.fehler.LETZTER_ADMIN":
      "Das letzte unbefristete Verwalterkonto kann nicht gelöscht werden.",
    "datenschutz.fehler.allgemein": "Das hat nicht geklappt. Bitte erneut versuchen.",
    "datenschutz.verwaltung.antraege": "Löschanträge",
    "datenschutz.verwaltung.keine": "Keine Löschanträge.",
    "datenschutz.verwaltung.frist": "Frist {{datum}}",
    "datenschutz.verwaltung.ueberfaellig": "überfällig",
    "datenschutz.verwaltung.kontoWeg": "Konto nicht mehr vorhanden",
    "datenschutz.verwaltung.wirkung":
      "Erledigen löscht Konto und Anmeldesitzungen über den vorhandenen Löschweg. Verweise in Beiträgen, Bewertungen und Protokoll bleiben stehen.",
    "datenschutz.verwaltung.erledigen": "Konto löschen und erledigen",
    "datenschutz.verwaltung.abgebrochen": "Die Erledigung wurde abgebrochen.",
    "datenschutz.verwaltung.wiederaufnehmen": "Erledigung wieder aufnehmen",
    "datenschutz.verwaltung.bestaetigen": "Konto von {{name}} jetzt löschen?",
    "datenschutz.verwaltung.ja": "Ja, löschen",
    "datenschutz.verwaltung.abbrechen": "Abbrechen",
    "datenschutz.verwaltung.ablehnen": "Ablehnen",
    "datenschutz.verwaltung.grund": "Grund der Ablehnung",
    "datenschutz.verwaltung.ablehnenSenden": "Ablehnung speichern",
    "datenschutz.verwaltung.begruendung": "Begründung: {{text}}",
    "datenschutz.verwaltung.entscheidung": "{{status}} am {{datum}}",
    "datenschutz.verwaltung.auskunft": "Auskunft",
    "datenschutz.verwaltung.auskunftKonto": "Auskunft für ein Konto",
    "datenschutz.verwaltung.kontoWaehlen": "Konto wählen",
    "datenschutz.verwaltung.auskunftLaden": "Auskunft herunterladen",
    "datenschutz.verwaltung.verzeichnis": "Verarbeitungsverzeichnis",
    "datenschutz.verwaltung.verzeichnisJson": "Als JSON herunterladen",
    "datenschutz.verwaltung.verzeichnisMd": "Als Markdown herunterladen",
    "datenschutz.verwaltung.inventar": "Dateninventar",
    "datenschutz.verwaltung.bezug.ja": "personenbezogen",
    "datenschutz.verwaltung.bezug.moeglich": "Personenbezug möglich",
    "datenschutz.verwaltung.bezug.nein": "kein Personenbezug",
    "datenschutz.meldungArt": "Löschantrag",
    "datenschutz.meldung": "Löschantrag",
    "datenschutz.meldungUeberfaellig": "Löschantrag überfällig",
    "datenschutz.meldungFrist": "Frist {{datum}}",
  },
  en: {
    "datenschutz.meineDaten.titel": "My data",
    "datenschutz.meineDaten.wert": "View and download",
    "datenschutz.meineDaten.herunterladen": "Download everything (JSON)",
    "datenschutz.meineDaten.laeuft": "Compiling …",
    "datenschutz.meineDaten.stand": "As of {{zeit}}",
    "datenschutz.meineDaten.nichtAbrufbar": "not retrievable",
    "datenschutz.meineDaten.nichtEnthalten": "Not in the file",
    "datenschutz.meineDaten.bereich.eigeneObjekte": "Own knowledge objects",
    "datenschutz.meineDaten.bereich.bearbeitungen": "Edited versions",
    "datenschutz.meineDaten.bereich.kommentare": "Comments",
    "datenschutz.meineDaten.bereich.entwuerfe": "Drafts",
    "datenschutz.meineDaten.bereich.fragen": "Questions asked",
    "datenschutz.meineDaten.bereich.antworten": "Answers received",
    "datenschutz.meineDaten.bereich.bewertungen": "Ratings",
    "datenschutz.meineDaten.bereich.zuweisungen": "Review assignments",
    "datenschutz.meineDaten.bereich.kenntnisnahmen": "Acknowledgements",
    "datenschutz.meineDaten.bereich.anhaenge": "Uploaded files",
    "datenschutz.meineDaten.bereich.lernpfade": "Learning paths",
    "datenschutz.meineDaten.bereich.loeschantraege": "Deletion requests",
    "datenschutz.meineDaten.bereich.nachfolge": "Successor for time-limited access",
    "datenschutz.meineDaten.bereich.protokoll": "Log entries",
    "datenschutz.meineDaten.bereich.kiLaeufe": "AI runs you requested",
    "datenschutz.meineDaten.bereich.klaraSitzungen": "Klara sessions",
    "datenschutz.meineDaten.bereich.klaraZustimmungen": "Consents to external AI",
    "datenschutz.meineDaten.uebergabe": "Handover",
    "datenschutz.meineDaten.uebergabe.verantwortlich": "Knowledge objects you own",
    "datenschutz.meineDaten.uebergabe.autor": "Listed as author",
    "datenschutz.meineDaten.uebergabe.pruefung": "Open review assignments",
    "datenschutz.meineDaten.uebergabe.fragen": "Assigned open questions",
    "datenschutz.meineDaten.uebergabe.nachfolge": "Successor for new contributions",
    "datenschutz.antrag.titel": "Request account deletion",
    "datenschutz.antrag.wirkung":
      "A request does not delete anything yet. It goes to the administrators as a task with a deadline. Once completed, your account and your sign-in sessions are deleted; contributions, comments and log entries remain with your identifier.",
    "datenschutz.antrag.begruendung": "Reason (optional)",
    "datenschutz.antrag.stellen": "Request deletion",
    "datenschutz.antrag.laeuft": "Sending …",
    "datenschutz.antrag.offen": "Your request from {{gestellt}} is open. Deadline: {{frist}}.",
    "datenschutz.antrag.ueberfaellig": "The deadline has passed.",
    "datenschutz.antrag.zurueckziehen": "Withdraw request",
    "datenschutz.antrag.verlauf": "Earlier requests",
    "datenschutz.status.offen": "Open",
    "datenschutz.status.in_bearbeitung": "Being processed",
    "datenschutz.status.erledigt": "Completed",
    "datenschutz.status.abgelehnt": "Declined",
    "datenschutz.status.zurueckgezogen": "Withdrawn",
    "datenschutz.fehler.BEREITS_OFFEN": "There is already an open request.",
    "datenschutz.fehler.NICHT_OFFEN": "The request is no longer open.",
    "datenschutz.fehler.ZU_LANG": "The text is too long.",
    "datenschutz.fehler.GRUND_FEHLT": "Declining requires a reason.",
    "datenschutz.fehler.NICHT_HALTBAR":
      "This instance cannot store requests permanently; nothing is accepted.",
    "datenschutz.fehler.LETZTER_ADMIN":
      "The last unlimited administrator account cannot be deleted.",
    "datenschutz.fehler.allgemein": "That did not work. Please try again.",
    "datenschutz.verwaltung.antraege": "Deletion requests",
    "datenschutz.verwaltung.keine": "No deletion requests.",
    "datenschutz.verwaltung.frist": "Deadline {{datum}}",
    "datenschutz.verwaltung.ueberfaellig": "overdue",
    "datenschutz.verwaltung.kontoWeg": "Account no longer exists",
    "datenschutz.verwaltung.wirkung":
      "Completing deletes the account and its sign-in sessions through the existing deletion path. References in contributions, ratings and the log remain.",
    "datenschutz.verwaltung.erledigen": "Delete account and complete",
    "datenschutz.verwaltung.abgebrochen": "Completing was interrupted.",
    "datenschutz.verwaltung.wiederaufnehmen": "Resume completion",
    "datenschutz.verwaltung.bestaetigen": "Delete the account of {{name}} now?",
    "datenschutz.verwaltung.ja": "Yes, delete",
    "datenschutz.verwaltung.abbrechen": "Cancel",
    "datenschutz.verwaltung.ablehnen": "Decline",
    "datenschutz.verwaltung.grund": "Reason for declining",
    "datenschutz.verwaltung.ablehnenSenden": "Save decision",
    "datenschutz.verwaltung.begruendung": "Reason: {{text}}",
    "datenschutz.verwaltung.entscheidung": "{{status}} on {{datum}}",
    "datenschutz.verwaltung.auskunft": "Data report",
    "datenschutz.verwaltung.auskunftKonto": "Data report for an account",
    "datenschutz.verwaltung.kontoWaehlen": "Choose account",
    "datenschutz.verwaltung.auskunftLaden": "Download data report",
    "datenschutz.verwaltung.verzeichnis": "Record of processing activities",
    "datenschutz.verwaltung.verzeichnisJson": "Download as JSON",
    "datenschutz.verwaltung.verzeichnisMd": "Download as Markdown",
    "datenschutz.verwaltung.inventar": "Data inventory",
    "datenschutz.verwaltung.bezug.ja": "personal data",
    "datenschutz.verwaltung.bezug.moeglich": "personal data possible",
    "datenschutz.verwaltung.bezug.nein": "no personal data",
    "datenschutz.meldungArt": "Deletion request",
    "datenschutz.meldung": "Deletion request",
    "datenschutz.meldungUeberfaellig": "Deletion request overdue",
    "datenschutz.meldungFrist": "Deadline {{datum}}",
  },
  nl: {
    "datenschutz.meineDaten.titel": "Mijn gegevens",
    "datenschutz.meineDaten.wert": "Bekijken en downloaden",
    "datenschutz.meineDaten.herunterladen": "Alles downloaden (JSON)",
    "datenschutz.meineDaten.laeuft": "Wordt samengesteld …",
    "datenschutz.meineDaten.stand": "Stand van {{zeit}}",
    "datenschutz.meineDaten.nichtAbrufbar": "niet op te vragen",
    "datenschutz.meineDaten.nichtEnthalten": "Niet in het bestand",
    "datenschutz.meineDaten.bereich.eigeneObjekte": "Eigen kennisobjecten",
    "datenschutz.meineDaten.bereich.bearbeitungen": "Bewerkte versies",
    "datenschutz.meineDaten.bereich.kommentare": "Opmerkingen",
    "datenschutz.meineDaten.bereich.entwuerfe": "Concepten",
    "datenschutz.meineDaten.bereich.fragen": "Gestelde vragen",
    "datenschutz.meineDaten.bereich.antworten": "Ontvangen antwoorden",
    "datenschutz.meineDaten.bereich.bewertungen": "Beoordelingen",
    "datenschutz.meineDaten.bereich.zuweisungen": "Toegewezen controles",
    "datenschutz.meineDaten.bereich.kenntnisnahmen": "Kennisnames",
    "datenschutz.meineDaten.bereich.anhaenge": "Geüploade bestanden",
    "datenschutz.meineDaten.bereich.lernpfade": "Leerpaden",
    "datenschutz.meineDaten.bereich.loeschantraege": "Verwijderverzoeken",
    "datenschutz.meineDaten.bereich.nachfolge": "Opvolging bij tijdelijke toegang",
    "datenschutz.meineDaten.bereich.protokoll": "Logregels",
    "datenschutz.meineDaten.bereich.kiLaeufe": "Aangevraagde AI-runs",
    "datenschutz.meineDaten.bereich.klaraSitzungen": "Klara-sessies",
    "datenschutz.meineDaten.bereich.klaraZustimmungen": "Toestemmingen voor externe AI",
    "datenschutz.meineDaten.uebergabe": "Overdracht",
    "datenschutz.meineDaten.uebergabe.verantwortlich":
      "Kennisobjecten onder jouw verantwoordelijkheid",
    "datenschutz.meineDaten.uebergabe.autor": "Als auteur vermeld",
    "datenschutz.meineDaten.uebergabe.pruefung": "Open toegewezen controles",
    "datenschutz.meineDaten.uebergabe.fragen": "Toegewezen open vragen",
    "datenschutz.meineDaten.uebergabe.nachfolge": "Opvolger voor nieuwe bijdragen",
    "datenschutz.antrag.titel": "Account laten verwijderen",
    "datenschutz.antrag.wirkung":
      "Een verzoek verwijdert nog niets. Het gaat als taak met termijn naar de beheerders. Wordt het afgehandeld, dan worden je account en je aanmeldsessies verwijderd; bijdragen, opmerkingen en logregels blijven met je kenmerk staan.",
    "datenschutz.antrag.begruendung": "Toelichting (optioneel)",
    "datenschutz.antrag.stellen": "Verwijdering aanvragen",
    "datenschutz.antrag.laeuft": "Wordt verzonden …",
    "datenschutz.antrag.offen": "Je verzoek van {{gestellt}} is open. Termijn: {{frist}}.",
    "datenschutz.antrag.ueberfaellig": "De termijn is verstreken.",
    "datenschutz.antrag.zurueckziehen": "Verzoek intrekken",
    "datenschutz.antrag.verlauf": "Eerdere verzoeken",
    "datenschutz.status.offen": "Open",
    "datenschutz.status.in_bearbeitung": "Wordt verwerkt",
    "datenschutz.status.erledigt": "Afgehandeld",
    "datenschutz.status.abgelehnt": "Afgewezen",
    "datenschutz.status.zurueckgezogen": "Ingetrokken",
    "datenschutz.fehler.BEREITS_OFFEN": "Er is al een open verzoek.",
    "datenschutz.fehler.NICHT_OFFEN": "Het verzoek is niet meer open.",
    "datenschutz.fehler.ZU_LANG": "De tekst is te lang.",
    "datenschutz.fehler.GRUND_FEHLT": "Een afwijzing heeft een reden nodig.",
    "datenschutz.fehler.NICHT_HALTBAR":
      "Deze instantie kan verzoeken niet blijvend opslaan; daarom wordt niets aangenomen.",
    "datenschutz.fehler.LETZTER_ADMIN":
      "Het laatste onbeperkte beheerdersaccount kan niet worden verwijderd.",
    "datenschutz.fehler.allgemein": "Dat is niet gelukt. Probeer het opnieuw.",
    "datenschutz.verwaltung.antraege": "Verwijderverzoeken",
    "datenschutz.verwaltung.keine": "Geen verwijderverzoeken.",
    "datenschutz.verwaltung.frist": "Termijn {{datum}}",
    "datenschutz.verwaltung.ueberfaellig": "verlopen",
    "datenschutz.verwaltung.kontoWeg": "Account bestaat niet meer",
    "datenschutz.verwaltung.wirkung":
      "Afhandelen verwijdert account en aanmeldsessies via de bestaande verwijderroute. Verwijzingen in bijdragen, beoordelingen en het logboek blijven staan.",
    "datenschutz.verwaltung.erledigen": "Account verwijderen en afhandelen",
    "datenschutz.verwaltung.abgebrochen": "Het afhandelen is onderbroken.",
    "datenschutz.verwaltung.wiederaufnehmen": "Afhandeling hervatten",
    "datenschutz.verwaltung.bestaetigen": "Het account van {{name}} nu verwijderen?",
    "datenschutz.verwaltung.ja": "Ja, verwijderen",
    "datenschutz.verwaltung.abbrechen": "Annuleren",
    "datenschutz.verwaltung.ablehnen": "Afwijzen",
    "datenschutz.verwaltung.grund": "Reden van afwijzing",
    "datenschutz.verwaltung.ablehnenSenden": "Afwijzing opslaan",
    "datenschutz.verwaltung.begruendung": "Toelichting: {{text}}",
    "datenschutz.verwaltung.entscheidung": "{{status}} op {{datum}}",
    "datenschutz.verwaltung.auskunft": "Inzage",
    "datenschutz.verwaltung.auskunftKonto": "Inzage voor een account",
    "datenschutz.verwaltung.kontoWaehlen": "Account kiezen",
    "datenschutz.verwaltung.auskunftLaden": "Inzage downloaden",
    "datenschutz.verwaltung.verzeichnis": "Register van verwerkingsactiviteiten",
    "datenschutz.verwaltung.verzeichnisJson": "Downloaden als JSON",
    "datenschutz.verwaltung.verzeichnisMd": "Downloaden als Markdown",
    "datenschutz.verwaltung.inventar": "Gegevensinventaris",
    "datenschutz.verwaltung.bezug.ja": "persoonsgegevens",
    "datenschutz.verwaltung.bezug.moeglich": "persoonsgegevens mogelijk",
    "datenschutz.verwaltung.bezug.nein": "geen persoonsgegevens",
    "datenschutz.meldungArt": "Verwijderverzoek",
    "datenschutz.meldung": "Verwijderverzoek",
    "datenschutz.meldungUeberfaellig": "Verwijderverzoek verlopen",
    "datenschutz.meldungFrist": "Termijn {{datum}}",
  },
} satisfies Textmodul;
