// ================================================================================================
// WISSENSGÜLTIGKEIT, WIEDERVORLAGE UND FRISCHESIGNALE · DIE TEXTE DIESES AUFTRAGS.
// ================================================================================================
//
// WOHER SIE KOMMEN: aus `aufnahme:20260922:gesamt-wissen-frische` (Bibliothek „Mehr" → Belege und
// Kopplung, Reiter „Erneut"). Die Werte erklären, was der Server in `frische` ableitet
// (`services/knowledge-object/src/frische.ts`).
//
// `audit.action.ko_freshness_confirmed` ist ein ALTNAME: `lib/auditAction.ts` leitet ihn aus dem
// Protokollvorgang `ko.freshness-confirmed` ab, den `KoService.bestaetigeFrische` schreibt.
import type { Textmodul } from "./intern/pruefung";

export default {
  praefix: "frische.",
  legacySchluessel: ["audit.action.ko_freshness_confirmed"],
  de: {
    "audit.action.ko_freshness_confirmed": "Als weiterhin gültig bestätigt",
    "frische.stufeLabel": "Aktualität",
    "frische.stufe.frisch": "frisch",
    "frische.stufe.altert": "altert",
    "frische.stufe.faellig": "fällig",
    "frische.stufe.veraltet": "veraltet",
    "frische.haltbarBis": "Gesichert bis",
    "frische.haltbarUnbekannt": "unbekannt",
    "frische.verantwortlich": "Verantwortlich",
    "frische.verantwortlichErsatz": "(Autor, kein Verantwortlicher benannt)",
    "frische.schutzLabel": "Schutzbedarf",
    "frische.schutz.intern": "intern",
    "frische.schutz.vertraulich": "vertraulich",
    "frische.schutz.streng_vertraulich": "streng vertraulich",
    "frische.schutz.unbekannt": "unbekannt",
    "frische.betriebsmodellLabel": "Empfohlenes Betriebsmodell",
    "frische.betriebsmodell.freigegebene_ki": "freigegebene KI möglich",
    "frische.betriebsmodell.lokales_modell": "nur lokales Modell",
    "frische.betriebsmodell.ohne_ki": "ohne KI-Verarbeitung",
    "frische.inDokumente": "In erzeugte Dokumente",
    "frische.ja": "ja",
    "frische.nein": "nein",
    "frische.naechsterLabel": "Nächster Schritt",
    "frische.naechster.konflikt_klaeren": "Konflikt klären",
    "frische.naechster.validierung_abschliessen": "Prüfung abschließen",
    "frische.naechster.erneut_bestaetigen": "Erneut bestätigen",
    "frische.naechster.bald_bestaetigen": "Bald bestätigen — die Frist läuft ab",
    "frische.naechster.keiner": "nichts zu tun",
    "frische.nichtGesichert":
      "Die Haltbarkeit ist abgelaufen: in Antworten gilt dieses Wissen nicht mehr als gesichert, bis die verantwortliche Person es bestätigt.",
    "frische.letztesSignal": "Zuletzt bestätigt von {{name}} am {{datum}}",
    "frische.stimmtWeiterhin": "Stimmt weiterhin",
    "frische.stimmtWeiterhinHinweis":
      "Nach dem Anwenden bestätigen, dass es noch stimmt — ein Frische-Signal, keine neue Prüfung.",
    "frische.stimmtWeiterhinGespeichert": "Danke — als weiterhin gültig bestätigt.",
    "frische.erneutPruefen": "Erneute Prüfung anstoßen",
    "frische.erneutPruefenGespeichert": "Zur erneuten Prüfung vorgelegt (Reiter „Erneut“).",
    "frische.nachbarnMelden": "Anlage geändert — Nachbarn markieren",
    "frische.nachbarnMeldenHinweis":
      "Alle Objekte an den gekoppelten Anlagen werden mit „Stimmt das noch?“ markiert.",
    "frische.nachbarnGemeldet_one": "{{count}} Objekt zur erneuten Prüfung markiert.",
    "frische.nachbarnGemeldet_other": "{{count}} Objekte zur erneuten Prüfung markiert.",
    "frische.vorlageTitel": "Ihre ältesten geprüften Beiträge",
    "frische.vorlageHinweis":
      "Bitte prüfen, ob sie noch stimmen, und am Objekt mit „Stimmt weiterhin“ bestätigen.",
    "frische.vorlageLeer": "Keine geprüften Beiträge in Ihrer Verantwortung.",
  },
  en: {
    "audit.action.ko_freshness_confirmed": "Confirmed as still valid",
    "frische.stufeLabel": "Freshness",
    "frische.stufe.frisch": "fresh",
    "frische.stufe.altert": "ageing",
    "frische.stufe.faellig": "due",
    "frische.stufe.veraltet": "outdated",
    "frische.haltbarBis": "Assured until",
    "frische.haltbarUnbekannt": "unknown",
    "frische.verantwortlich": "Responsible",
    "frische.verantwortlichErsatz": "(author, no responsible person named)",
    "frische.schutzLabel": "Protection need",
    "frische.schutz.intern": "internal",
    "frische.schutz.vertraulich": "confidential",
    "frische.schutz.streng_vertraulich": "strictly confidential",
    "frische.schutz.unbekannt": "unknown",
    "frische.betriebsmodellLabel": "Recommended operating model",
    "frische.betriebsmodell.freigegebene_ki": "approved AI possible",
    "frische.betriebsmodell.lokales_modell": "local model only",
    "frische.betriebsmodell.ohne_ki": "no AI processing",
    "frische.inDokumente": "In generated documents",
    "frische.ja": "yes",
    "frische.nein": "no",
    "frische.naechsterLabel": "Next step",
    "frische.naechster.konflikt_klaeren": "Resolve conflict",
    "frische.naechster.validierung_abschliessen": "Finish review",
    "frische.naechster.erneut_bestaetigen": "Confirm again",
    "frische.naechster.bald_bestaetigen": "Confirm soon — the period is ending",
    "frische.naechster.keiner": "nothing to do",
    "frische.nichtGesichert":
      "The validity period has expired: answers no longer treat this knowledge as assured until the responsible person confirms it.",
    "frische.letztesSignal": "Last confirmed by {{name}} on {{datum}}",
    "frische.stimmtWeiterhin": "Still correct",
    "frische.stimmtWeiterhinHinweis":
      "After applying it, confirm that it is still correct — a freshness signal, not a new review.",
    "frische.stimmtWeiterhinGespeichert": "Thank you — confirmed as still valid.",
    "frische.erneutPruefen": "Request a new review",
    "frische.erneutPruefenGespeichert": "Submitted for a new review (tab “Again”).",
    "frische.nachbarnMelden": "Asset changed — mark neighbours",
    "frische.nachbarnMeldenHinweis":
      "All objects on the coupled assets are marked with “Is this still correct?”.",
    "frische.nachbarnGemeldet_one": "{{count}} object marked for a new review.",
    "frische.nachbarnGemeldet_other": "{{count}} objects marked for a new review.",
    "frische.vorlageTitel": "Your oldest reviewed contributions",
    "frische.vorlageHinweis":
      "Please check whether they are still correct and confirm on the object with “Still correct”.",
    "frische.vorlageLeer": "No reviewed contributions in your responsibility.",
  },
  nl: {
    "audit.action.ko_freshness_confirmed": "Bevestigd als nog geldig",
    "frische.stufeLabel": "Actualiteit",
    "frische.stufe.frisch": "vers",
    "frische.stufe.altert": "veroudert",
    "frische.stufe.faellig": "verlopen",
    "frische.stufe.veraltet": "verouderd",
    "frische.haltbarBis": "Geborgd tot",
    "frische.haltbarUnbekannt": "onbekend",
    "frische.verantwortlich": "Verantwoordelijk",
    "frische.verantwortlichErsatz": "(auteur, geen verantwoordelijke benoemd)",
    "frische.schutzLabel": "Beschermingsbehoefte",
    "frische.schutz.intern": "intern",
    "frische.schutz.vertraulich": "vertrouwelijk",
    "frische.schutz.streng_vertraulich": "strikt vertrouwelijk",
    "frische.schutz.unbekannt": "onbekend",
    "frische.betriebsmodellLabel": "Aanbevolen bedrijfsmodel",
    "frische.betriebsmodell.freigegebene_ki": "vrijgegeven AI mogelijk",
    "frische.betriebsmodell.lokales_modell": "alleen lokaal model",
    "frische.betriebsmodell.ohne_ki": "zonder AI-verwerking",
    "frische.inDokumente": "In gegenereerde documenten",
    "frische.ja": "ja",
    "frische.nein": "nee",
    "frische.naechsterLabel": "Volgende stap",
    "frische.naechster.konflikt_klaeren": "Conflict oplossen",
    "frische.naechster.validierung_abschliessen": "Controle afronden",
    "frische.naechster.erneut_bestaetigen": "Opnieuw bevestigen",
    "frische.naechster.bald_bestaetigen": "Binnenkort bevestigen — de termijn loopt af",
    "frische.naechster.keiner": "niets te doen",
    "frische.nichtGesichert":
      "De houdbaarheid is verlopen: in antwoorden geldt deze kennis niet meer als geborgd, totdat de verantwoordelijke persoon haar bevestigt.",
    "frische.letztesSignal": "Laatst bevestigd door {{name}} op {{datum}}",
    "frische.stimmtWeiterhin": "Klopt nog steeds",
    "frische.stimmtWeiterhinHinweis":
      "Bevestig na het toepassen dat het nog klopt — een actualiteitssignaal, geen nieuwe controle.",
    "frische.stimmtWeiterhinGespeichert": "Dank je — bevestigd als nog geldig.",
    "frische.erneutPruefen": "Nieuwe controle aanvragen",
    "frische.erneutPruefenGespeichert": "Voorgelegd voor een nieuwe controle (tabblad ‘Opnieuw’).",
    "frische.nachbarnMelden": "Installatie gewijzigd — buren markeren",
    "frische.nachbarnMeldenHinweis":
      "Alle objecten aan de gekoppelde installaties worden gemarkeerd met ‘Klopt dit nog?’.",
    "frische.nachbarnGemeldet_one": "{{count}} object gemarkeerd voor een nieuwe controle.",
    "frische.nachbarnGemeldet_other": "{{count}} objecten gemarkeerd voor een nieuwe controle.",
    "frische.vorlageTitel": "Uw oudste gecontroleerde bijdragen",
    "frische.vorlageHinweis":
      "Controleer of ze nog kloppen en bevestig bij het object met ‘Klopt nog steeds’.",
    "frische.vorlageLeer": "Geen gecontroleerde bijdragen onder uw verantwoordelijkheid.",
  },
} satisfies Textmodul;
