// ================================================================================================
// KLARA-VORSCHAU (Auftrag produkt:20261007:klara-vorschau) — die Texte der beweglichen Klara.
// ================================================================================================
//
// Klara als Figur über der ganzen Browseroberfläche: verschieben, andocken, verkleinern, Gespräch
// kompakt oder seitlich, Kontext der Seite, „Klara fragen“ an einer Markierung, Tutorial-Begleitung.
// ALLE Antworten dieser Vorschau sind VORGEFERTIGT — die Texte sagen das an jeder Antwort, an der
// Speicherung, an Erinnerung und Termin. Eine simulierte Antwort ist kein Nachweis echter KI.
//
// produkt:20261010:assistenz-name-avatar: kein fester Produktname mehr. `{{assistenz}}` ist der
// persönliche Name (neutral „Assistenz"), `{{assistenzTitel}}` der Name oder „Deine Assistenz" —
// gesetzt von `useAssistenzT` (`lib/assistenzProfil.ts`). Die Sätze kommen ohne Pronomen der Figur
// aus, weil der Name frei gewählt ist.
import type { Textmodul } from "./intern/pruefung";

export default {
  praefix: "klaravorschau.",
  legacySchluessel: [],
  de: {
    "klaravorschau.figur.label": "{{assistenz}} – Gespräch öffnen oder schließen",
    "klaravorschau.figur.tastatur":
      "Pfeiltasten verschieben {{assistenz}} (mit Umschalt in großen Schritten), Pos1 setzt die Figur zurück.",
    "klaravorschau.figur.verschoben": "{{assistenz}} verschoben.",
    "klaravorschau.figur.angedockt": "{{assistenz}} ist am {{rand}} Rand angedockt.",
    "klaravorschau.figur.zurueckgesetzt": "{{assistenz}} ist zurück am Startplatz.",
    "klaravorschau.figur.geparkt": "{{assistenz}} parkt an Absatz {{nr}}.",
    "klaravorschau.figur.ablegen": "Text hier ablegen – {{assistenz}} schaut ihn sich an",
    "klaravorschau.rand.links": "linken",
    "klaravorschau.rand.rechts": "rechten",
    "klaravorschau.status.ruhe": "Bereit",
    "klaravorschau.status.laeuft": "Anfrage läuft …",
    "klaravorschau.status.antwort": "Antwort bereit",
    "klaravorschau.status.entscheidung": "Entscheidung nötig",
    "klaravorschau.panel.titel": "{{assistenzTitel}}",
    "klaravorschau.panel.untertitel": "Vorschau · vorgefertigte Demo-Antworten",
    "klaravorschau.panel.demoHinweis":
      "Demo: Die Antworten von {{assistenz}} in dieser Vorschau sind vorgefertigt. Es arbeitet keine echte KI, und nichts wird dauerhaft gespeichert.",
    "klaravorschau.knopf.minimieren": "Verkleinern",
    "klaravorschau.knopf.schliessen": "Gespräch schließen",
    "klaravorschau.knopf.seitlich": "Seitlich anzeigen",
    "klaravorschau.knopf.kompakt": "Kompakt anzeigen",
    "klaravorschau.knopf.andocken": "Am Rand andocken",
    "klaravorschau.knopf.zuruecksetzen": "Position zurücksetzen",
    "klaravorschau.knopf.vollbild": "Vollbild",
    "klaravorschau.knopf.vollbildAus": "Vollbild beenden",
    "klaravorschau.knopf.beenden": "Vorschau beenden",
    "klaravorschau.knopf.parkenLoesen": "Parken aufheben",
    "klaravorschau.ort.label": "Du bist hier",
    "klaravorschau.ort.objekt": "Objekt",
    "klaravorschau.seite.uebersicht": "Vorschau der Assistenz",
    "klaravorschau.seite.artikel": "Artikel",
    "klaravorschau.seite.erfassung": "Erfassung",
    "klaravorschau.seite.fragen": "Fragen",
    "klaravorschau.seite.andere": "Klarwerk",
    "klaravorschau.objekt.uebersicht": "Übersicht der fiktiven Artikel",
    "klaravorschau.objekt.artikel": "„{{titel}}“",
    "klaravorschau.objekt.neuerEntwurf": "Neuer, noch unbenannter Entwurf",
    "klaravorschau.objekt.entwurf": "Entwurf „{{titel}}“",
    "klaravorschau.objekt.frage": "Frage „{{frage}}“",
    "klaravorschau.objekt.keineFrage": "Noch keine Frage eingegeben",
    "klaravorschau.objekt.keins": "Kein bestimmtes Objekt",
    "klaravorschau.auswahl.knopf": "{{assistenz}} fragen",
    "klaravorschau.auswahl.titel": "Markierter Ausschnitt",
    "klaravorschau.auswahl.herkunft": "Aus: {{seite}} · {{objekt}}",
    "klaravorschau.auswahl.absatz": "Absatz {{nr}}",
    "klaravorschau.auswahl.leer":
      "Markiere einen Text auf der Seite und wähle „{{assistenz}} fragen“ – oder ziehe ihn auf die Figur.",
    "klaravorschau.auswahl.andereSeite":
      "Dieser Ausschnitt gehört weiter zu {{seite}} ({{objekt}}), nicht zur aktuellen Seite.",
    "klaravorschau.auswahl.entfernen": "Ausschnitt entfernen",
    "klaravorschau.auswahl.zurHerkunft": "Zur Herkunft",
    "klaravorschau.aktion.label": "Was soll {{assistenz}} damit tun?",
    "klaravorschau.aktion.erklaeren": "Erklären",
    "klaravorschau.aktion.zusammenfassen": "Zusammenfassen",
    "klaravorschau.aktion.umformulieren": "Umformulieren",
    "klaravorschau.aktion.notiz": "Notizentwurf",
    "klaravorschau.anfrage.erklaeren": "Erkläre: „{{auszug}}“",
    "klaravorschau.anfrage.zusammenfassen": "Fasse zusammen: „{{auszug}}“",
    "klaravorschau.anfrage.umformulieren": "Formuliere um: „{{auszug}}“",
    "klaravorschau.anfrage.notiz": "Notizentwurf zu: „{{auszug}}“",
    "klaravorschau.antwort.kennzeichen": "Demo-Antwort · vorgefertigt",
    "klaravorschau.antwort.erklaerenAllgemein":
      "Der markierte Text beginnt mit „{{anfang}}“ und umfasst {{woerter}} Wörter. In einer echten Antwort würde {{assistenz}} ihn hier Satz für Satz erklären und die Quelle nennen – diese Vorschau zeigt nur den Ablauf.",
    "klaravorschau.antwort.zusammenfassenAllgemein": "Kurz gesagt: {{satz}}",
    "klaravorschau.antwort.umformulierenAllgemein": "Einfacher formuliert (Demo): {{text}}",
    "klaravorschau.antwort.notiz":
      "Ich habe einen Entwurf vorbereitet. Prüfe Inhalt und Rücklink – gespeichert wird nur zur Demo.",
    "klaravorschau.antwort.vorschlag":
      "Hier ist ein Vorschlag. Der Artikel ändert sich erst, wenn du ihn bewusst übernimmst.",
    "klaravorschau.antwort.frageArtikel":
      "Zu „{{frage}}“: Der Artikel „{{titel}}“ beschreibt {{kern}}",
    "klaravorschau.antwort.frageFragen":
      "Zu „{{frage}}“: Auf der Seite Fragen stellst du eine Frage an das geprüfte Firmenwissen und bekommst eine Antwort mit Quellen. Echte Antworten gibt nur das Fragefeld der Seite, nicht diese Vorschau.",
    "klaravorschau.antwort.frageErfassung":
      "Zu „{{frage}}“: In der Erfassung schreibst du Wissen auf – zuerst einen klaren Titel, dann den Text. Gespeichert wird dort als Entwurf; ich speichere hier nichts.",
    "klaravorschau.antwort.frageAndere": "Zu „{{frage}}“: Du bist auf {{seite}}. {{erklaerung}}",
    "klaravorschau.antwort.frageTutorial":
      "Zwischenfrage zu Schritt {{nr}} „{{titel}}“: {{erklaerung}} Das Tutorial wartet, bis du „Fortsetzen“ wählst.",
    "klaravorschau.vorschlag.titel": "Vorschlag zur Umformulierung",
    "klaravorschau.vorschlag.original": "Original",
    "klaravorschau.vorschlag.neu": "Vorschlag",
    "klaravorschau.vorschlag.uebernehmen": "In den Artikel übernehmen",
    "klaravorschau.vorschlag.verwerfen": "Verwerfen",
    "klaravorschau.vorschlag.uebernommen":
      "Übernommen: Absatz {{nr}} im Artikel ist geändert (nur in dieser Vorschau).",
    "klaravorschau.vorschlag.verworfen": "Verworfen – der Artikel bleibt unverändert.",
    "klaravorschau.vorschlag.nurArtikel":
      "Übernehmen geht nur bei Ausschnitten aus einem fiktiven Artikel.",
    "klaravorschau.entwurf.titel": "Entwurf",
    "klaravorschau.entwurf.art": "Art",
    "klaravorschau.entwurf.notiz": "Notiz",
    "klaravorschau.entwurf.aufgabe": "Aufgabe",
    "klaravorschau.entwurf.inhalt": "Inhalt",
    "klaravorschau.entwurf.ruecklink": "Zurück zum Artikel „{{titel}}“, Absatz {{nr}}",
    "klaravorschau.entwurf.ruecklinkSeite": "Zurück zu: {{seite}}",
    "klaravorschau.entwurf.erinnerung": "Erinnerung",
    "klaravorschau.entwurf.termin": "Termin",
    "klaravorschau.entwurf.demo": "Demo",
    "klaravorschau.entwurf.demoHinweis":
      "Demo: Erinnerung und Termin werden in keinen Kalender übertragen und lösen nichts aus.",
    "klaravorschau.entwurf.speichern": "Speichern (Demo)",
    "klaravorschau.entwurf.gespeichert":
      "Demo-Speicherung: nur in dieser Browser-Sitzung gemerkt, nicht im Wissensbestand gespeichert.",
    "klaravorschau.entwurf.verwerfen": "Entwurf verwerfen",
    "klaravorschau.verlauf.titel": "Verlauf",
    "klaravorschau.verlauf.leer": "Noch kein Gespräch.",
    "klaravorschau.verlauf.du": "Du",
    "klaravorschau.verlauf.klara": "{{assistenz}}",
    "klaravorschau.verlauf.auf": "auf {{seite}} · {{objekt}}",
    "klaravorschau.eingabe.label": "Frage an {{assistenz}}",
    "klaravorschau.eingabe.platzhalter": "Frag {{assistenz}} etwas …",
    "klaravorschau.eingabe.senden": "Senden",
    "klaravorschau.modus.label": "Hilfe zur Seite",
    "klaravorschau.modus.erklaere": "Erkläre mir das",
    "klaravorschau.modus.zeige": "Zeige mir den nächsten Schritt",
    "klaravorschau.modus.begleite": "Begleite die Durchführung",
    "klaravorschau.modus.erklaereSeite": "{{seite}}: {{erklaerung}}",
    "klaravorschau.modus.keinTutorial":
      "Für diese Seite gibt es kein Tutorial. Das siebenstufige Tutorial gibt es auf der Seite Fragen.",
    "klaravorschau.modus.zuFragen": "Zu Fragen wechseln",
    "klaravorschau.tutorial.titel": "Tutorial „Fragen“ mit {{assistenz}}",
    "klaravorschau.tutorial.schritt": "Schritt {{nr}} von {{gesamt}}: {{titel}}",
    "klaravorschau.tutorial.gerade": "Gerade gezeigt: {{teil}}",
    "klaravorschau.tutorial.flaeche": "die Fläche als Ganzes",
    "klaravorschau.tutorial.zeigt": "Ich zeige auf: {{teil}} ({{ort}}).",
    "klaravorschau.tutorial.ortEcht": "auf der echten Seite",
    "klaravorschau.tutorial.ortDemo": "in der Tutorial-Demo",
    "klaravorschau.tutorial.pause": "Pause",
    "klaravorschau.tutorial.fortsetzen": "Fortsetzen",
    "klaravorschau.tutorial.zurueck": "Zurück",
    "klaravorschau.tutorial.weiter": "Weiter",
    "klaravorschau.tutorial.laeuft": "Vorführung läuft",
    "klaravorschau.tutorial.steht": "Vorführung steht",
    "klaravorschau.tutorial.pausiert": "Pausiert bei Schritt {{nr}}: {{titel}}.",
    "klaravorschau.tutorial.fortgesetzt": "Weiter bei Schritt {{nr}}: {{titel}}.",
    "klaravorschau.tutorial.beendet": "Begleitung beendet.",
    "klaravorschau.tutorial.begleitungEnde": "Begleitung beenden",
    "klaravorschau.tutorial.fehlzielDemo":
      "„{{ziel}}“ ist auf der echten Seite gerade nicht zu sehen – es erscheint erst später im Ablauf. Ich zeige es dir deshalb in der Tutorial-Demo.",
    "klaravorschau.tutorial.fehlzielGanz":
      "„{{ziel}}“ ist gerade weder auf der Seite noch in der Demo zu sehen. Wähle „Zurück“ oder „Weiter“ – oder frag mich direkt.",
    "klaravorschau.tutorial.falschKlick":
      "Das war ein anderes Element. Gezeigt wird gerade: {{teil}}.",
    "klaravorschau.tutorial.wirdGeoeffnet": "Ich öffne das Tutorial „Fragen“ …",
    "klaravorschau.zeiger.label": "{{assistenz}} zeigt hierhin",
    "klaravorschau.vorschauseite.titel": "{{assistenzTitel}} zuerst ansehen",
    "klaravorschau.vorschauseite.kennzeichen": "Vorschau · fiktive Demodaten",
    "klaravorschau.vorschauseite.intro":
      "{{assistenz}} bewegt sich als Figur frei über die ganze Klarwerk-Oberfläche und erkennt, auf welcher Seite du bist und was du markiert hast. Im echten Betrieb beantwortet {{assistenz}} getippte Fragen über den Frageweg von Klarwerk und speichert das Gespräch unter deinem Konto; im Demo-Betrieb und bei den fiktiven Artikeln sind die Antworten vorgefertigt. Name und Motiv wählst du unter Einstellungen → Persönliche Einstellungen → Meine Assistenz.",
    "klaravorschau.vorschauseite.soGehts": "So probierst du es aus",
    "klaravorschau.vorschauseite.schritt1":
      "{{assistenz}} ziehen – mit Maus, Finger oder den Pfeiltasten. Nah am Rand dockt die Figur an.",
    "klaravorschau.vorschauseite.schritt2":
      "Einen Artikel öffnen, einen Absatz markieren und „{{assistenz}} fragen“ wählen.",
    "klaravorschau.vorschauseite.schritt3":
      "Zu Fragen wechseln und das Tutorial mit {{assistenz}} durchgehen – Zwischenfragen sind erlaubt.",
    "klaravorschau.vorschauseite.schritt4":
      "Einen Notizentwurf anlegen, {{assistenz}} verkleinern und wieder öffnen.",
    "klaravorschau.vorschauseite.artikel": "Fiktive Artikel",
    "klaravorschau.vorschauseite.oeffnen": "Artikel öffnen",
    "klaravorschau.vorschauseite.weiter": "Weiter in der Vorschau",
    "klaravorschau.vorschauseite.zuErfassung": "Zur Erfassung",
    "klaravorschau.vorschauseite.zuFragen": "Zu Fragen",
    "klaravorschau.vorschauseite.zurUebersicht": "Zur Übersicht",
    "klaravorschau.vorschauseite.geaendert": "durch Übernahme geändert",
    "klaravorschau.vorschauseite.gesten":
      "Kreative Gesten: Markierten Text auf {{assistenz}} ziehen – oder die Figur auf einen Absatz ziehen, dann parkt sie dort.",
    "klaravorschau.vorschauseite.unbekannt": "Diesen fiktiven Artikel gibt es nicht.",
    "klaravorschau.vorschauseite.sprachhinweis":
      "Die fiktiven Artikel sind nur auf Deutsch hinterlegt.",
  },
  en: {
    "klaravorschau.figur.label": "{{assistenz}} – open or close the conversation",
    "klaravorschau.figur.tastatur":
      "Arrow keys move {{assistenz}} (with Shift in larger steps), Home resets the figure.",
    "klaravorschau.figur.verschoben": "{{assistenz}} moved.",
    "klaravorschau.figur.angedockt": "{{assistenz}} is docked at the {{rand}} edge.",
    "klaravorschau.figur.zurueckgesetzt": "{{assistenz}} is back at the starting place.",
    "klaravorschau.figur.geparkt": "{{assistenz}} is parked at paragraph {{nr}}.",
    "klaravorschau.figur.ablegen": "Drop text here – {{assistenz}} will take a look",
    "klaravorschau.rand.links": "left",
    "klaravorschau.rand.rechts": "right",
    "klaravorschau.status.ruhe": "Ready",
    "klaravorschau.status.laeuft": "Request running …",
    "klaravorschau.status.antwort": "Answer ready",
    "klaravorschau.status.entscheidung": "Decision needed",
    "klaravorschau.panel.titel": "{{assistenzTitel}}",
    "klaravorschau.panel.untertitel": "Preview · prepared demo answers",
    "klaravorschau.panel.demoHinweis":
      "Demo: the answers of {{assistenz}} in this preview are prepared in advance. No real AI is involved, and nothing is stored permanently.",
    "klaravorschau.knopf.minimieren": "Minimise",
    "klaravorschau.knopf.schliessen": "Close conversation",
    "klaravorschau.knopf.seitlich": "Show at the side",
    "klaravorschau.knopf.kompakt": "Show compact",
    "klaravorschau.knopf.andocken": "Dock at the edge",
    "klaravorschau.knopf.zuruecksetzen": "Reset position",
    "klaravorschau.knopf.vollbild": "Full screen",
    "klaravorschau.knopf.vollbildAus": "Exit full screen",
    "klaravorschau.knopf.beenden": "End preview",
    "klaravorschau.knopf.parkenLoesen": "Unpark",
    "klaravorschau.ort.label": "You are here",
    "klaravorschau.ort.objekt": "Object",
    "klaravorschau.seite.uebersicht": "Assistant preview",
    "klaravorschau.seite.artikel": "Article",
    "klaravorschau.seite.erfassung": "Capture",
    "klaravorschau.seite.fragen": "Ask",
    "klaravorschau.seite.andere": "Klarwerk",
    "klaravorschau.objekt.uebersicht": "Overview of the fictional articles",
    "klaravorschau.objekt.artikel": "“{{titel}}”",
    "klaravorschau.objekt.neuerEntwurf": "New, still untitled draft",
    "klaravorschau.objekt.entwurf": "Draft “{{titel}}”",
    "klaravorschau.objekt.frage": "Question “{{frage}}”",
    "klaravorschau.objekt.keineFrage": "No question entered yet",
    "klaravorschau.objekt.keins": "No specific object",
    "klaravorschau.auswahl.knopf": "Ask {{assistenz}}",
    "klaravorschau.auswahl.titel": "Selected excerpt",
    "klaravorschau.auswahl.herkunft": "From: {{seite}} · {{objekt}}",
    "klaravorschau.auswahl.absatz": "paragraph {{nr}}",
    "klaravorschau.auswahl.leer":
      "Select some text on the page and choose “Ask {{assistenz}}” – or drag it onto the figure.",
    "klaravorschau.auswahl.andereSeite":
      "This excerpt still belongs to {{seite}} ({{objekt}}), not to the current page.",
    "klaravorschau.auswahl.entfernen": "Remove excerpt",
    "klaravorschau.auswahl.zurHerkunft": "Go to origin",
    "klaravorschau.aktion.label": "What should {{assistenz}} do with it?",
    "klaravorschau.aktion.erklaeren": "Explain",
    "klaravorschau.aktion.zusammenfassen": "Summarise",
    "klaravorschau.aktion.umformulieren": "Rephrase",
    "klaravorschau.aktion.notiz": "Note draft",
    "klaravorschau.anfrage.erklaeren": "Explain: “{{auszug}}”",
    "klaravorschau.anfrage.zusammenfassen": "Summarise: “{{auszug}}”",
    "klaravorschau.anfrage.umformulieren": "Rephrase: “{{auszug}}”",
    "klaravorschau.anfrage.notiz": "Note draft for: “{{auszug}}”",
    "klaravorschau.antwort.kennzeichen": "Demo answer · prepared",
    "klaravorschau.antwort.erklaerenAllgemein":
      "The selected text starts with “{{anfang}}” and has {{woerter}} words. In a real answer {{assistenz}} would explain it sentence by sentence and name the source – this preview only shows the flow.",
    "klaravorschau.antwort.zusammenfassenAllgemein": "In short: {{satz}}",
    "klaravorschau.antwort.umformulierenAllgemein": "Phrased more simply (demo): {{text}}",
    "klaravorschau.antwort.notiz":
      "I have prepared a draft. Check the content and the back link – saving is only a demo.",
    "klaravorschau.antwort.vorschlag":
      "Here is a suggestion. The article only changes once you deliberately apply it.",
    "klaravorschau.antwort.frageArtikel":
      "About “{{frage}}”: the article “{{titel}}” describes {{kern}}",
    "klaravorschau.antwort.frageFragen":
      "About “{{frage}}”: on the Ask page you put a question to the verified company knowledge and get an answer with sources. Only the page's question field gives real answers, not this preview.",
    "klaravorschau.antwort.frageErfassung":
      "About “{{frage}}”: in Capture you write down knowledge – first a clear title, then the text. It is saved there as a draft; I save nothing here.",
    "klaravorschau.antwort.frageAndere": "About “{{frage}}”: you are on {{seite}}. {{erklaerung}}",
    "klaravorschau.antwort.frageTutorial":
      "Interim question on step {{nr}} “{{titel}}”: {{erklaerung}} The tutorial waits until you choose “Continue”.",
    "klaravorschau.vorschlag.titel": "Rephrasing suggestion",
    "klaravorschau.vorschlag.original": "Original",
    "klaravorschau.vorschlag.neu": "Suggestion",
    "klaravorschau.vorschlag.uebernehmen": "Apply to the article",
    "klaravorschau.vorschlag.verwerfen": "Discard",
    "klaravorschau.vorschlag.uebernommen":
      "Applied: paragraph {{nr}} of the article has changed (only in this preview).",
    "klaravorschau.vorschlag.verworfen": "Discarded – the article stays unchanged.",
    "klaravorschau.vorschlag.nurArtikel":
      "Applying only works for excerpts from a fictional article.",
    "klaravorschau.entwurf.titel": "Draft",
    "klaravorschau.entwurf.art": "Type",
    "klaravorschau.entwurf.notiz": "Note",
    "klaravorschau.entwurf.aufgabe": "Task",
    "klaravorschau.entwurf.inhalt": "Content",
    "klaravorschau.entwurf.ruecklink": "Back to the article “{{titel}}”, paragraph {{nr}}",
    "klaravorschau.entwurf.ruecklinkSeite": "Back to: {{seite}}",
    "klaravorschau.entwurf.erinnerung": "Reminder",
    "klaravorschau.entwurf.termin": "Appointment",
    "klaravorschau.entwurf.demo": "Demo",
    "klaravorschau.entwurf.demoHinweis":
      "Demo: reminder and appointment are not transferred to any calendar and trigger nothing.",
    "klaravorschau.entwurf.speichern": "Save (demo)",
    "klaravorschau.entwurf.gespeichert":
      "Demo save: only remembered in this browser session, not stored in the knowledge base.",
    "klaravorschau.entwurf.verwerfen": "Discard draft",
    "klaravorschau.verlauf.titel": "History",
    "klaravorschau.verlauf.leer": "No conversation yet.",
    "klaravorschau.verlauf.du": "You",
    "klaravorschau.verlauf.klara": "{{assistenz}}",
    "klaravorschau.verlauf.auf": "on {{seite}} · {{objekt}}",
    "klaravorschau.eingabe.label": "Question for {{assistenz}}",
    "klaravorschau.eingabe.platzhalter": "Ask {{assistenz}} something …",
    "klaravorschau.eingabe.senden": "Send",
    "klaravorschau.modus.label": "Help for this page",
    "klaravorschau.modus.erklaere": "Explain this to me",
    "klaravorschau.modus.zeige": "Show me the next step",
    "klaravorschau.modus.begleite": "Guide me through it",
    "klaravorschau.modus.erklaereSeite": "{{seite}}: {{erklaerung}}",
    "klaravorschau.modus.keinTutorial":
      "There is no tutorial for this page. The seven-step tutorial is on the Ask page.",
    "klaravorschau.modus.zuFragen": "Go to Ask",
    "klaravorschau.tutorial.titel": "Tutorial “Ask” with {{assistenz}}",
    "klaravorschau.tutorial.schritt": "Step {{nr}} of {{gesamt}}: {{titel}}",
    "klaravorschau.tutorial.gerade": "Currently shown: {{teil}}",
    "klaravorschau.tutorial.flaeche": "the area as a whole",
    "klaravorschau.tutorial.zeigt": "I am pointing at: {{teil}} ({{ort}}).",
    "klaravorschau.tutorial.ortEcht": "on the real page",
    "klaravorschau.tutorial.ortDemo": "in the tutorial demo",
    "klaravorschau.tutorial.pause": "Pause",
    "klaravorschau.tutorial.fortsetzen": "Continue",
    "klaravorschau.tutorial.zurueck": "Back",
    "klaravorschau.tutorial.weiter": "Next",
    "klaravorschau.tutorial.laeuft": "Demonstration running",
    "klaravorschau.tutorial.steht": "Demonstration paused",
    "klaravorschau.tutorial.pausiert": "Paused at step {{nr}}: {{titel}}.",
    "klaravorschau.tutorial.fortgesetzt": "Continuing at step {{nr}}: {{titel}}.",
    "klaravorschau.tutorial.beendet": "Guidance ended.",
    "klaravorschau.tutorial.begleitungEnde": "End guidance",
    "klaravorschau.tutorial.fehlzielDemo":
      "“{{ziel}}” is not visible on the real page right now – it only appears later in the flow. So I am showing it to you in the tutorial demo.",
    "klaravorschau.tutorial.fehlzielGanz":
      "“{{ziel}}” is currently visible neither on the page nor in the demo. Choose “Back” or “Next” – or ask me directly.",
    "klaravorschau.tutorial.falschKlick":
      "That was a different element. Currently shown: {{teil}}.",
    "klaravorschau.tutorial.wirdGeoeffnet": "Opening the tutorial “Ask” …",
    "klaravorschau.zeiger.label": "{{assistenz}} is pointing here",
    "klaravorschau.vorschauseite.titel": "See {{assistenzTitel}} first",
    "klaravorschau.vorschauseite.kennzeichen": "Preview · fictional demo data",
    "klaravorschau.vorschauseite.intro":
      "{{assistenz}} moves as a figure freely across the whole Klarwerk interface and recognises which page you are on and what you have selected. In live mode {{assistenz}} answers typed questions through Klarwerk's question path and saves the conversation under your account; in demo mode and for the fictional articles the answers are prepared in advance. You choose the name and motif under Settings → Personal settings → My assistant.",
    "klaravorschau.vorschauseite.soGehts": "How to try it",
    "klaravorschau.vorschauseite.schritt1":
      "Drag {{assistenz}} – with the mouse, a finger or the arrow keys. Close to the edge the figure docks.",
    "klaravorschau.vorschauseite.schritt2":
      "Open an article, select a paragraph and choose “Ask {{assistenz}}”.",
    "klaravorschau.vorschauseite.schritt3":
      "Switch to Ask and go through the tutorial with {{assistenz}} – interim questions are welcome.",
    "klaravorschau.vorschauseite.schritt4":
      "Create a note draft, minimise {{assistenz}} and open the figure again.",
    "klaravorschau.vorschauseite.artikel": "Fictional articles",
    "klaravorschau.vorschauseite.oeffnen": "Open article",
    "klaravorschau.vorschauseite.weiter": "Continue in the preview",
    "klaravorschau.vorschauseite.zuErfassung": "To Capture",
    "klaravorschau.vorschauseite.zuFragen": "To Ask",
    "klaravorschau.vorschauseite.zurUebersicht": "To the overview",
    "klaravorschau.vorschauseite.geaendert": "changed by applying a suggestion",
    "klaravorschau.vorschauseite.gesten":
      "Creative gestures: drag selected text onto {{assistenz}} – or drag the figure onto a paragraph and it parks there.",
    "klaravorschau.vorschauseite.unbekannt": "This fictional article does not exist.",
    "klaravorschau.vorschauseite.sprachhinweis":
      "The fictional articles are only available in German.",
  },
  nl: {
    "klaravorschau.figur.label": "{{assistenz}} – gesprek openen of sluiten",
    "klaravorschau.figur.tastatur":
      "Pijltjestoetsen verplaatsen {{assistenz}} (met Shift in grote stappen), Home zet de figuur terug.",
    "klaravorschau.figur.verschoben": "{{assistenz}} verplaatst.",
    "klaravorschau.figur.angedockt": "{{assistenz}} is aan de {{rand}} rand vastgezet.",
    "klaravorschau.figur.zurueckgesetzt": "{{assistenz}} staat weer op de startplek.",
    "klaravorschau.figur.geparkt": "{{assistenz}} staat geparkeerd bij alinea {{nr}}.",
    "klaravorschau.figur.ablegen": "Tekst hier neerzetten – {{assistenz}} bekijkt hem",
    "klaravorschau.rand.links": "linker",
    "klaravorschau.rand.rechts": "rechter",
    "klaravorschau.status.ruhe": "Klaar",
    "klaravorschau.status.laeuft": "Verzoek loopt …",
    "klaravorschau.status.antwort": "Antwoord klaar",
    "klaravorschau.status.entscheidung": "Beslissing nodig",
    "klaravorschau.panel.titel": "{{assistenzTitel}}",
    "klaravorschau.panel.untertitel": "Voorvertoning · voorbereide demo-antwoorden",
    "klaravorschau.panel.demoHinweis":
      "Demo: de antwoorden van {{assistenz}} in deze voorvertoning zijn vooraf gemaakt. Er werkt geen echte AI en niets wordt blijvend opgeslagen.",
    "klaravorschau.knopf.minimieren": "Verkleinen",
    "klaravorschau.knopf.schliessen": "Gesprek sluiten",
    "klaravorschau.knopf.seitlich": "Aan de zijkant tonen",
    "klaravorschau.knopf.kompakt": "Compact tonen",
    "klaravorschau.knopf.andocken": "Aan de rand vastzetten",
    "klaravorschau.knopf.zuruecksetzen": "Positie terugzetten",
    "klaravorschau.knopf.vollbild": "Volledig scherm",
    "klaravorschau.knopf.vollbildAus": "Volledig scherm verlaten",
    "klaravorschau.knopf.beenden": "Voorvertoning beëindigen",
    "klaravorschau.knopf.parkenLoesen": "Parkeren opheffen",
    "klaravorschau.ort.label": "Je bent hier",
    "klaravorschau.ort.objekt": "Object",
    "klaravorschau.seite.uebersicht": "Voorvertoning van de assistent",
    "klaravorschau.seite.artikel": "Artikel",
    "klaravorschau.seite.erfassung": "Vastleggen",
    "klaravorschau.seite.fragen": "Vragen",
    "klaravorschau.seite.andere": "Klarwerk",
    "klaravorschau.objekt.uebersicht": "Overzicht van de fictieve artikelen",
    "klaravorschau.objekt.artikel": "‘{{titel}}’",
    "klaravorschau.objekt.neuerEntwurf": "Nieuw, nog naamloos concept",
    "klaravorschau.objekt.entwurf": "Concept ‘{{titel}}’",
    "klaravorschau.objekt.frage": "Vraag ‘{{frage}}’",
    "klaravorschau.objekt.keineFrage": "Nog geen vraag ingevoerd",
    "klaravorschau.objekt.keins": "Geen bepaald object",
    "klaravorschau.auswahl.knopf": "{{assistenz}} vragen",
    "klaravorschau.auswahl.titel": "Gemarkeerd fragment",
    "klaravorschau.auswahl.herkunft": "Uit: {{seite}} · {{objekt}}",
    "klaravorschau.auswahl.absatz": "alinea {{nr}}",
    "klaravorschau.auswahl.leer":
      "Markeer tekst op de pagina en kies ‘{{assistenz}} vragen’ – of sleep hem naar de figuur.",
    "klaravorschau.auswahl.andereSeite":
      "Dit fragment hoort nog steeds bij {{seite}} ({{objekt}}), niet bij de huidige pagina.",
    "klaravorschau.auswahl.entfernen": "Fragment verwijderen",
    "klaravorschau.auswahl.zurHerkunft": "Naar de herkomst",
    "klaravorschau.aktion.label": "Wat moet {{assistenz}} ermee doen?",
    "klaravorschau.aktion.erklaeren": "Uitleggen",
    "klaravorschau.aktion.zusammenfassen": "Samenvatten",
    "klaravorschau.aktion.umformulieren": "Herformuleren",
    "klaravorschau.aktion.notiz": "Notitieconcept",
    "klaravorschau.anfrage.erklaeren": "Leg uit: ‘{{auszug}}’",
    "klaravorschau.anfrage.zusammenfassen": "Vat samen: ‘{{auszug}}’",
    "klaravorschau.anfrage.umformulieren": "Herformuleer: ‘{{auszug}}’",
    "klaravorschau.anfrage.notiz": "Notitieconcept bij: ‘{{auszug}}’",
    "klaravorschau.antwort.kennzeichen": "Demo-antwoord · voorbereid",
    "klaravorschau.antwort.erklaerenAllgemein":
      "De gemarkeerde tekst begint met ‘{{anfang}}’ en telt {{woerter}} woorden. In een echt antwoord zou {{assistenz}} hem hier zin voor zin uitleggen en de bron noemen – deze voorvertoning toont alleen het verloop.",
    "klaravorschau.antwort.zusammenfassenAllgemein": "Kort gezegd: {{satz}}",
    "klaravorschau.antwort.umformulierenAllgemein": "Eenvoudiger geformuleerd (demo): {{text}}",
    "klaravorschau.antwort.notiz":
      "Ik heb een concept voorbereid. Controleer inhoud en terugkoppeling – opslaan is alleen een demo.",
    "klaravorschau.antwort.vorschlag":
      "Hier is een voorstel. Het artikel verandert pas als je het bewust overneemt.",
    "klaravorschau.antwort.frageArtikel":
      "Over ‘{{frage}}’: het artikel ‘{{titel}}’ beschrijft {{kern}}",
    "klaravorschau.antwort.frageFragen":
      "Over ‘{{frage}}’: op de pagina Vragen stel je een vraag aan de gecontroleerde bedrijfskennis en krijg je een antwoord met bronnen. Alleen het vraagveld van de pagina geeft echte antwoorden, niet deze voorvertoning.",
    "klaravorschau.antwort.frageErfassung":
      "Over ‘{{frage}}’: bij Vastleggen schrijf je kennis op – eerst een duidelijke titel, dan de tekst. Daar wordt het als concept opgeslagen; ik sla hier niets op.",
    "klaravorschau.antwort.frageAndere": "Over ‘{{frage}}’: je bent op {{seite}}. {{erklaerung}}",
    "klaravorschau.antwort.frageTutorial":
      "Tussenvraag bij stap {{nr}} ‘{{titel}}’: {{erklaerung}} De tutorial wacht tot je ‘Verdergaan’ kiest.",
    "klaravorschau.vorschlag.titel": "Voorstel voor herformulering",
    "klaravorschau.vorschlag.original": "Origineel",
    "klaravorschau.vorschlag.neu": "Voorstel",
    "klaravorschau.vorschlag.uebernehmen": "In het artikel overnemen",
    "klaravorschau.vorschlag.verwerfen": "Verwerpen",
    "klaravorschau.vorschlag.uebernommen":
      "Overgenomen: alinea {{nr}} van het artikel is gewijzigd (alleen in deze voorvertoning).",
    "klaravorschau.vorschlag.verworfen": "Verworpen – het artikel blijft ongewijzigd.",
    "klaravorschau.vorschlag.nurArtikel":
      "Overnemen kan alleen bij fragmenten uit een fictief artikel.",
    "klaravorschau.entwurf.titel": "Concept",
    "klaravorschau.entwurf.art": "Soort",
    "klaravorschau.entwurf.notiz": "Notitie",
    "klaravorschau.entwurf.aufgabe": "Taak",
    "klaravorschau.entwurf.inhalt": "Inhoud",
    "klaravorschau.entwurf.ruecklink": "Terug naar het artikel ‘{{titel}}’, alinea {{nr}}",
    "klaravorschau.entwurf.ruecklinkSeite": "Terug naar: {{seite}}",
    "klaravorschau.entwurf.erinnerung": "Herinnering",
    "klaravorschau.entwurf.termin": "Afspraak",
    "klaravorschau.entwurf.demo": "Demo",
    "klaravorschau.entwurf.demoHinweis":
      "Demo: herinnering en afspraak worden niet naar een agenda overgezet en activeren niets.",
    "klaravorschau.entwurf.speichern": "Opslaan (demo)",
    "klaravorschau.entwurf.gespeichert":
      "Demo-opslag: alleen in deze browsersessie onthouden, niet in de kennisbank opgeslagen.",
    "klaravorschau.entwurf.verwerfen": "Concept verwerpen",
    "klaravorschau.verlauf.titel": "Verloop",
    "klaravorschau.verlauf.leer": "Nog geen gesprek.",
    "klaravorschau.verlauf.du": "Jij",
    "klaravorschau.verlauf.klara": "{{assistenz}}",
    "klaravorschau.verlauf.auf": "op {{seite}} · {{objekt}}",
    "klaravorschau.eingabe.label": "Vraag aan {{assistenz}}",
    "klaravorschau.eingabe.platzhalter": "Vraag {{assistenz}} iets …",
    "klaravorschau.eingabe.senden": "Versturen",
    "klaravorschau.modus.label": "Hulp bij deze pagina",
    "klaravorschau.modus.erklaere": "Leg me dit uit",
    "klaravorschau.modus.zeige": "Toon me de volgende stap",
    "klaravorschau.modus.begleite": "Begeleid de uitvoering",
    "klaravorschau.modus.erklaereSeite": "{{seite}}: {{erklaerung}}",
    "klaravorschau.modus.keinTutorial":
      "Voor deze pagina is er geen tutorial. De tutorial in zeven stappen staat op de pagina Vragen.",
    "klaravorschau.modus.zuFragen": "Naar Vragen",
    "klaravorschau.tutorial.titel": "Tutorial ‘Vragen’ met {{assistenz}}",
    "klaravorschau.tutorial.schritt": "Stap {{nr}} van {{gesamt}}: {{titel}}",
    "klaravorschau.tutorial.gerade": "Nu getoond: {{teil}}",
    "klaravorschau.tutorial.flaeche": "het vlak als geheel",
    "klaravorschau.tutorial.zeigt": "Ik wijs naar: {{teil}} ({{ort}}).",
    "klaravorschau.tutorial.ortEcht": "op de echte pagina",
    "klaravorschau.tutorial.ortDemo": "in de tutorialdemo",
    "klaravorschau.tutorial.pause": "Pauze",
    "klaravorschau.tutorial.fortsetzen": "Verdergaan",
    "klaravorschau.tutorial.zurueck": "Terug",
    "klaravorschau.tutorial.weiter": "Volgende",
    "klaravorschau.tutorial.laeuft": "Demonstratie loopt",
    "klaravorschau.tutorial.steht": "Demonstratie staat stil",
    "klaravorschau.tutorial.pausiert": "Gepauzeerd bij stap {{nr}}: {{titel}}.",
    "klaravorschau.tutorial.fortgesetzt": "Verder bij stap {{nr}}: {{titel}}.",
    "klaravorschau.tutorial.beendet": "Begeleiding beëindigd.",
    "klaravorschau.tutorial.begleitungEnde": "Begeleiding beëindigen",
    "klaravorschau.tutorial.fehlzielDemo":
      "‘{{ziel}}’ is op de echte pagina nu niet te zien – het verschijnt pas later. Daarom toon ik het je in de tutorialdemo.",
    "klaravorschau.tutorial.fehlzielGanz":
      "‘{{ziel}}’ is nu niet op de pagina en niet in de demo te zien. Kies ‘Terug’ of ‘Volgende’ – of vraag het mij direct.",
    "klaravorschau.tutorial.falschKlick": "Dat was een ander element. Nu getoond: {{teil}}.",
    "klaravorschau.tutorial.wirdGeoeffnet": "Ik open de tutorial ‘Vragen’ …",
    "klaravorschau.zeiger.label": "{{assistenz}} wijst hierheen",
    "klaravorschau.vorschauseite.titel": "{{assistenzTitel}} eerst bekijken",
    "klaravorschau.vorschauseite.kennzeichen": "Voorvertoning · fictieve demogegevens",
    "klaravorschau.vorschauseite.intro":
      "{{assistenz}} beweegt als figuur vrij over de hele Klarwerk-omgeving en herkent op welke pagina je bent en wat je hebt gemarkeerd. In de echte modus beantwoordt {{assistenz}} getypte vragen via de vraagroute van Klarwerk en slaat het gesprek op onder je account; in de demomodus en bij de fictieve artikelen zijn de antwoorden voorbereid. Naam en motief kies je via Instellingen → Persoonlijke instellingen → Mijn assistent.",
    "klaravorschau.vorschauseite.soGehts": "Zo probeer je het uit",
    "klaravorschau.vorschauseite.schritt1":
      "Sleep {{assistenz}} – met muis, vinger of pijltjestoetsen. Dicht bij de rand zet de figuur zich vast.",
    "klaravorschau.vorschauseite.schritt2":
      "Open een artikel, markeer een alinea en kies ‘{{assistenz}} vragen’.",
    "klaravorschau.vorschauseite.schritt3":
      "Ga naar Vragen en doorloop de tutorial met {{assistenz}} – tussenvragen mogen.",
    "klaravorschau.vorschauseite.schritt4":
      "Maak een notitieconcept, verklein {{assistenz}} en open de figuur opnieuw.",
    "klaravorschau.vorschauseite.artikel": "Fictieve artikelen",
    "klaravorschau.vorschauseite.oeffnen": "Artikel openen",
    "klaravorschau.vorschauseite.weiter": "Verder in de voorvertoning",
    "klaravorschau.vorschauseite.zuErfassung": "Naar Vastleggen",
    "klaravorschau.vorschauseite.zuFragen": "Naar Vragen",
    "klaravorschau.vorschauseite.zurUebersicht": "Naar het overzicht",
    "klaravorschau.vorschauseite.geaendert": "gewijzigd door overname",
    "klaravorschau.vorschauseite.gesten":
      "Creatieve gebaren: sleep gemarkeerde tekst naar {{assistenz}} – of sleep de figuur naar een alinea, dan parkeert die daar.",
    "klaravorschau.vorschauseite.unbekannt": "Dit fictieve artikel bestaat niet.",
    "klaravorschau.vorschauseite.sprachhinweis":
      "De fictieve artikelen zijn alleen in het Duits beschikbaar.",
  },
} satisfies Textmodul;
