// ================================================================================================
// LÜCKENVORGANG · produkt:20261010:wissenskreislauf-schliessen — von der unbeantworteten Frage bis
// zur geprüften Antwort und Rückmeldung.
// ================================================================================================
//
// Die Texte beschreiben den TATSÄCHLICHEN Stand eines Vorgangs (Server: services/ask/src/
// gap-vorgang.ts). Sie versprechen keine Frist und keine Antwort. „Gelöst" steht nur da, wo der
// Server einen fachlich freigegebenen, heute nutzbaren Wissenseintrag festgehalten hat; eine
// administrative Rücknahme heißt ausdrücklich nicht „gelöst".
import type { Textmodul } from "./intern/pruefung";

export default {
  praefix: "lueckenvorgang.",
  legacySchluessel: [],
  de: {
    "lueckenvorgang.oeffnen": "Vorgang",
    "lueckenvorgang.einklappen": "Vorgang einklappen",
    "lueckenvorgang.titel": "Vorgang dieser Frage",
    "lueckenvorgang.laden": "Vorgang wird geladen …",
    "lueckenvorgang.nichtBeteiligt":
      "Diesen Vorgang sehen nur die Fragenden, die zuständige Person und Verwaltende.",
    "lueckenvorgang.fehler": "Der Vorgang konnte nicht geladen werden.",
    "lueckenvorgang.aktionFehler": "Der Schritt wurde nicht ausgeführt.",
    "lueckenvorgang.stand": "Stand",
    "lueckenvorgang.naechster": "Nächster Schritt",
    "lueckenvorgang.fragende": "Gestellt von {{count}} Person(en)",
    "lueckenvorgang.phase.ohne_zustaendigkeit":
      "Keine Fachzuständigkeit — die Frage liegt bei niemandem",
    "lueckenvorgang.phase.zustaendigkeit_nicht_verfuegbar":
      "Die zuständige Person ist nicht mehr verfügbar",
    "lueckenvorgang.phase.rueckfrage_offen": "Rückfrage an die Fragenden offen",
    "lueckenvorgang.phase.in_bearbeitung": "In Bearbeitung durch die zuständige Person",
    "lueckenvorgang.phase.in_fachpruefung": "Antwortentwurf in der Fachprüfung",
    "lueckenvorgang.phase.bereit_zum_abschluss":
      "Fachprüfung bestanden — der fachliche Abschluss steht aus",
    "lueckenvorgang.phase.geloest": "Fachlich gelöst",
    "lueckenvorgang.phase.zurueckgenommen":
      "Administrativ zurückgenommen — keine fachliche Antwort",
    "lueckenvorgang.phase.geschlossen_ohne_nachweis":
      "Geschlossen ohne festgehaltenen Abschluss (Altbestand)",
    "lueckenvorgang.schritt.zustaendigkeit_uebergeben":
      "An eine berechtigte Fachzuständigkeit übergeben",
    "lueckenvorgang.schritt.zustaendigkeit_zuordnen": "Eine Fachzuständigkeit zuordnen",
    "lueckenvorgang.schritt.neu_zuordnen": "Neu zuordnen",
    "lueckenvorgang.schritt.rueckfrage_beantworten": "Die Rückfrage beantworten",
    "lueckenvorgang.schritt.antwort_auf_rueckfrage_abwarten":
      "Auf die Antwort der Fragenden warten",
    "lueckenvorgang.schritt.antwortentwurf_erfassen":
      "Antwort erfassen und den eingereichten Eintrag verknüpfen",
    "lueckenvorgang.schritt.fachpruefung_abwarten":
      "Die vorgeschriebene Fachprüfung des Eintrags abwarten",
    "lueckenvorgang.schritt.fachlich_abschliessen": "Fachlich abschließen",
    "lueckenvorgang.schritt.bearbeitung_abwarten": "Nichts zu tun — die Bearbeitung läuft",
    "lueckenvorgang.schritt.ergebnis_lesen": "Das Ergebnis lesen",
    "lueckenvorgang.schritt.erneut_fragen": "Bei Bedarf neu fragen",
    "lueckenvorgang.schritt.keiner": "Kein Schritt offen",
    "lueckenvorgang.rolle.fragend": "Du hast gefragt",
    "lueckenvorgang.rolle.zustaendig": "Du bist zuständig",
    "lueckenvorgang.rolle.verwaltend": "Du verwaltest",
    "lueckenvorgang.zustaendig": "Zuständig",
    "lueckenvorgang.zustaendigNiemand": "niemand",
    "lueckenvorgang.zustaendigNichtVerfuegbar": "nicht mehr verfügbar",
    "lueckenvorgang.verlauf": "Verlauf der Zuständigkeit",
    "lueckenvorgang.verlauf.zuordnung": "zugeordnet an {{name}}",
    "lueckenvorgang.verlauf.uebergabe": "übergeben an {{name}}",
    "lueckenvorgang.verlauf.neuzuordnung": "neu zugeordnet an {{name}}",
    "lueckenvorgang.uebergeben": "An Fachzuständigkeit übergeben",
    "lueckenvorgang.uebergebenWaehlen": "Person wählen",
    "lueckenvorgang.uebergebenHinweis":
      "Angenommen werden nur Personen mit freigegebenem Konto und Erfassungsrecht.",
    "lueckenvorgang.rueckfrage": "Rückfrage",
    "lueckenvorgang.rueckfrageOffen": "offen",
    "lueckenvorgang.rueckfrageBeantwortet": "beantwortet",
    "lueckenvorgang.rueckfrageStellen": "Rückfrage an die Fragenden",
    "lueckenvorgang.rueckfrageSenden": "Rückfrage senden",
    "lueckenvorgang.rueckfrageAntwort": "Antwort an die zuständige Person",
    "lueckenvorgang.rueckfrageAntwortSenden": "Antwort senden",
    "lueckenvorgang.rueckfrageVonMir": "von dir beantwortet",
    "lueckenvorgang.entwurf": "Antwortentwurf",
    "lueckenvorgang.entwurfErfassen": "Antwort erfassen",
    "lueckenvorgang.entwurfVerknuepfen": "Eingereichten Eintrag verknüpfen",
    "lueckenvorgang.entwurfNichtZugaenglich":
      "Der verknüpfte Eintrag ist für dich nicht zugänglich.",
    "lueckenvorgang.ergebnis": "Ergebnis",
    "lueckenvorgang.ergebnisOeffnen": "Wissenseintrag öffnen",
    "lueckenvorgang.ergebnisNichtZugaenglich":
      "Das Ergebnis ist für dich derzeit nicht zugänglich.",
    "lueckenvorgang.nichtNutzbar": "Trägt derzeit nicht als Ergebnis",
    "lueckenvorgang.nutzbar": "Fachlich freigegeben, gültig und für dich nutzbar",
    "lueckenvorgang.eintrag.fassung": "Fassung {{v}}",
    "lueckenvorgang.eintrag.pruefung":
      "Fachprüfung: {{gruen}} von {{benoetigt}} Bewertungen, {{rot}} rot",
    "lueckenvorgang.eintrag.pruefungUnbekannt": "Fachprüfung: nicht feststellbar",
    "lueckenvorgang.eintrag.eigentuemer": "Verantwortlich: {{name}}",
    "lueckenvorgang.eintrag.sichtbarkeit": "Sichtbarkeit: {{stufe}}",
    "lueckenvorgang.eintrag.space": "an einen Space gebunden",
    "lueckenvorgang.eintrag.quellen": "Quellen: {{count}}",
    "lueckenvorgang.grund.nicht_vorhanden": "Eintrag nicht vorhanden",
    "lueckenvorgang.grund.kein_zugriff": "kein Zugriff",
    "lueckenvorgang.grund.nicht_freigegeben": "noch nicht fachlich freigegeben",
    "lueckenvorgang.grund.bewertungen_fehlen": "vorgeschriebene Bewertungen fehlen",
    "lueckenvorgang.grund.negative_bewertung": "durch eine negative Bewertung gesperrt",
    "lueckenvorgang.grund.abgelaufen": "Gültigkeit abgelaufen",
    "lueckenvorgang.grund.quarantaene": "in Schutzdaten-Quarantäne",
    "lueckenvorgang.grund.pruefstand_unbekannt": "Prüfstand nicht feststellbar",
    "lueckenvorgang.abschliessen": "Fachlich abschließen",
    "lueckenvorgang.abschliessenHinweis":
      "Schließt nur mit einem fachlich freigegebenen, gültigen Eintrag in seiner aktuellen Fassung.",
    "lueckenvorgang.abschluss.fachlich": "Fachlich gelöst am {{datum}} mit Fassung {{v}}",
    "lueckenvorgang.abschluss.administrativ":
      "Administrativ zurückgenommen am {{datum}}: {{grund}}. Das ist keine fachliche Antwort.",
    "lueckenvorgang.ruecknahme": "Administrativ zurücknehmen",
    "lueckenvorgang.ruecknahmeWaehlen": "Grund wählen",
    "lueckenvorgang.ruecknahme.dublette": "Dublette einer anderen Frage",
    "lueckenvorgang.ruecknahme.nicht_beantwortbar": "nicht beantwortbar",
    "lueckenvorgang.ruecknahme.ausser_zustaendigkeit": "außerhalb unserer Zuständigkeit",
    "lueckenvorgang.ruecknahme.zurueckgezogen": "von den Fragenden zurückgezogen",
    "lueckenvorgang.klara.titel": "{{name}} erklärt den Vorgang",
    "lueckenvorgang.klara.satz":
      "Stand: {{phase}}. Als Nächstes: {{schritt}}. Das ist der tatsächliche Stand dieses Vorgangs, keine Fachprüfung durch {{name}}.",
    "lueckenvorgang.klara.demo":
      "{{name}} steht gerade im Vorschau-Betrieb; diese Erklärung stammt trotzdem aus dem echten Vorgang.",
    "lueckenvorgang.meldung.geloest": "Deine Frage ist fachlich gelöst",
    "lueckenvorgang.meldung.rueckfrage": "Rückfrage zu deiner Frage",
    "lueckenvorgang.meldung.rueckfrageBeantwortet": "Rückfrage beantwortet",
    "lueckenvorgang.meldungArt": "Wissenslücke",
    "lueckenvorgang.liste.geloest": "gelöst",
    "lueckenvorgang.liste.zurueckgenommen": "zurückgenommen",
    "lueckenvorgang.liste.rueckfrageOffen": "Rückfrage offen",
    "lueckenvorgang.frage.geloestTitel": "Diese Frage ist bereits fachlich beantwortet",
    "lueckenvorgang.frage.geloestText":
      "Geprüfter Wissenseintrag „{{titel}}“, Fassung {{v}} — für dich heute nutzbar. Es wurde keine neue Wissenslücke angelegt.",
    "lueckenvorgang.frage.geloestOeffnen": "Eintrag öffnen",
    "lueckenvorgang.frage.vorgangOeffnen": "Vorgang dieser Frage verfolgen",
    "lueckenvorgang.seite.titel": "Vorgang einer Wissenslücke",
    "lueckenvorgang.seite.lead":
      "Wer zuständig ist, was gerade geschieht und was als Nächstes ansteht — so, wie es für dich heute gilt.",
    // produkt:20261010:antwort-beanstandung-korrektur
    "lueckenvorgang.phase.zurueckgewiesen":
      "Fachlich geprüft und begründet zurückgewiesen — die Aussage bleibt",
    "lueckenvorgang.schritt.begruendung_lesen": "Die Begründung lesen",
    "lueckenvorgang.abschluss.zurueckgewiesen":
      "Beanstandung am {{datum}} begründet zurückgewiesen. Das ist keine Korrektur.",
    "lueckenvorgang.zurueckweisungQuelle": "Geprüfte Quelle öffnen (Fassung {{v}})",
    "lueckenvorgang.zurueckweisen":
      "Beanstandung begründet zurückweisen (die Begründung geht an die Meldenden)",
    "lueckenvorgang.zurueckweisenSenden": "Begründet zurückweisen",
    "lueckenvorgang.beanstandung.titel": "Beanstandete Aussage",
    "lueckenvorgang.beanstandung.zurueckgehalten":
      "Die Aussage ist für dich zurückgehalten — dir fehlt der Zugriff auf eine ihrer Quellen.",
    "lueckenvorgang.beanstandung.quelleFehlt": "Gemeldet: eine Quelle fehlt",
    "lueckenvorgang.beanstandung.quelle": "Beanstandet in Fassung {{fassungen}} der Quelle",
    "lueckenvorgang.beanstandung.quelleNichtZugaenglich": "Quelle für dich nicht zugänglich",
    "lueckenvorgang.beanstandung.meldungen": "{{count}} Meldung(en)",
    "lueckenvorgang.beanstandung.quelleOeffnen": "Quelle öffnen",
    "lueckenvorgang.meldung.zurueckgewiesen": "Deine Beanstandung wurde begründet zurückgewiesen",
    "lueckenvorgang.liste.zurueckgewiesen": "zurückgewiesen",
    "lueckenvorgang.liste.beanstandung": "Beanstandete Aussage einer Antwort",
  },
  en: {
    "lueckenvorgang.oeffnen": "Process",
    "lueckenvorgang.einklappen": "Collapse process",
    "lueckenvorgang.titel": "Process of this question",
    "lueckenvorgang.laden": "Loading process …",
    "lueckenvorgang.nichtBeteiligt":
      "Only the askers, the responsible person and administrators can see this process.",
    "lueckenvorgang.fehler": "The process could not be loaded.",
    "lueckenvorgang.aktionFehler": "The step was not carried out.",
    "lueckenvorgang.stand": "Status",
    "lueckenvorgang.naechster": "Next step",
    "lueckenvorgang.fragende": "Asked by {{count}} person(s)",
    "lueckenvorgang.phase.ohne_zustaendigkeit":
      "No subject-matter owner — nobody holds this question",
    "lueckenvorgang.phase.zustaendigkeit_nicht_verfuegbar":
      "The responsible person is no longer available",
    "lueckenvorgang.phase.rueckfrage_offen": "Follow-up question to the askers is open",
    "lueckenvorgang.phase.in_bearbeitung": "Being worked on by the responsible person",
    "lueckenvorgang.phase.in_fachpruefung": "Answer draft in expert review",
    "lueckenvorgang.phase.bereit_zum_abschluss":
      "Expert review passed — subject-matter closure is pending",
    "lueckenvorgang.phase.geloest": "Resolved on the merits",
    "lueckenvorgang.phase.zurueckgenommen": "Withdrawn administratively — no subject-matter answer",
    "lueckenvorgang.phase.geschlossen_ohne_nachweis":
      "Closed without a recorded closure (legacy data)",
    "lueckenvorgang.schritt.zustaendigkeit_uebergeben":
      "Hand over to an authorised subject-matter owner",
    "lueckenvorgang.schritt.zustaendigkeit_zuordnen": "Assign a subject-matter owner",
    "lueckenvorgang.schritt.neu_zuordnen": "Reassign",
    "lueckenvorgang.schritt.rueckfrage_beantworten": "Answer the follow-up question",
    "lueckenvorgang.schritt.antwort_auf_rueckfrage_abwarten": "Wait for the askers' reply",
    "lueckenvorgang.schritt.antwortentwurf_erfassen":
      "Capture the answer and link the submitted entry",
    "lueckenvorgang.schritt.fachpruefung_abwarten":
      "Wait for the required expert review of the entry",
    "lueckenvorgang.schritt.fachlich_abschliessen": "Close on the merits",
    "lueckenvorgang.schritt.bearbeitung_abwarten": "Nothing to do — work is in progress",
    "lueckenvorgang.schritt.ergebnis_lesen": "Read the result",
    "lueckenvorgang.schritt.erneut_fragen": "Ask again if needed",
    "lueckenvorgang.schritt.keiner": "No step open",
    "lueckenvorgang.rolle.fragend": "You asked",
    "lueckenvorgang.rolle.zustaendig": "You are responsible",
    "lueckenvorgang.rolle.verwaltend": "You administer",
    "lueckenvorgang.zustaendig": "Responsible",
    "lueckenvorgang.zustaendigNiemand": "nobody",
    "lueckenvorgang.zustaendigNichtVerfuegbar": "no longer available",
    "lueckenvorgang.verlauf": "Responsibility history",
    "lueckenvorgang.verlauf.zuordnung": "assigned to {{name}}",
    "lueckenvorgang.verlauf.uebergabe": "handed over to {{name}}",
    "lueckenvorgang.verlauf.neuzuordnung": "reassigned to {{name}}",
    "lueckenvorgang.uebergeben": "Hand over to subject-matter owner",
    "lueckenvorgang.uebergebenWaehlen": "Choose person",
    "lueckenvorgang.uebergebenHinweis":
      "Only people with an approved account and the right to capture knowledge are accepted.",
    "lueckenvorgang.rueckfrage": "Follow-up question",
    "lueckenvorgang.rueckfrageOffen": "open",
    "lueckenvorgang.rueckfrageBeantwortet": "answered",
    "lueckenvorgang.rueckfrageStellen": "Follow-up question to the askers",
    "lueckenvorgang.rueckfrageSenden": "Send follow-up question",
    "lueckenvorgang.rueckfrageAntwort": "Reply to the responsible person",
    "lueckenvorgang.rueckfrageAntwortSenden": "Send reply",
    "lueckenvorgang.rueckfrageVonMir": "answered by you",
    "lueckenvorgang.entwurf": "Answer draft",
    "lueckenvorgang.entwurfErfassen": "Capture answer",
    "lueckenvorgang.entwurfVerknuepfen": "Link submitted entry",
    "lueckenvorgang.entwurfNichtZugaenglich": "The linked entry is not accessible to you.",
    "lueckenvorgang.ergebnis": "Result",
    "lueckenvorgang.ergebnisOeffnen": "Open knowledge entry",
    "lueckenvorgang.ergebnisNichtZugaenglich": "The result is currently not accessible to you.",
    "lueckenvorgang.nichtNutzbar": "Currently does not stand as a result",
    "lueckenvorgang.nutzbar": "Approved by experts, valid and usable for you",
    "lueckenvorgang.eintrag.fassung": "Version {{v}}",
    "lueckenvorgang.eintrag.pruefung":
      "Expert review: {{gruen}} of {{benoetigt}} ratings, {{rot}} red",
    "lueckenvorgang.eintrag.pruefungUnbekannt": "Expert review: cannot be determined",
    "lueckenvorgang.eintrag.eigentuemer": "Responsible: {{name}}",
    "lueckenvorgang.eintrag.sichtbarkeit": "Visibility: {{stufe}}",
    "lueckenvorgang.eintrag.space": "bound to a space",
    "lueckenvorgang.eintrag.quellen": "Sources: {{count}}",
    "lueckenvorgang.grund.nicht_vorhanden": "entry not present",
    "lueckenvorgang.grund.kein_zugriff": "no access",
    "lueckenvorgang.grund.nicht_freigegeben": "not yet approved by experts",
    "lueckenvorgang.grund.bewertungen_fehlen": "required ratings missing",
    "lueckenvorgang.grund.negative_bewertung": "blocked by a negative rating",
    "lueckenvorgang.grund.abgelaufen": "validity expired",
    "lueckenvorgang.grund.quarantaene": "in protected-data quarantine",
    "lueckenvorgang.grund.pruefstand_unbekannt": "review status cannot be determined",
    "lueckenvorgang.abschliessen": "Close on the merits",
    "lueckenvorgang.abschliessenHinweis":
      "Closes only with an expert-approved, valid entry in its current version.",
    "lueckenvorgang.abschluss.fachlich": "Resolved on the merits on {{datum}} with version {{v}}",
    "lueckenvorgang.abschluss.administrativ":
      "Withdrawn administratively on {{datum}}: {{grund}}. This is not a subject-matter answer.",
    "lueckenvorgang.ruecknahme": "Withdraw administratively",
    "lueckenvorgang.ruecknahmeWaehlen": "Choose reason",
    "lueckenvorgang.ruecknahme.dublette": "duplicate of another question",
    "lueckenvorgang.ruecknahme.nicht_beantwortbar": "cannot be answered",
    "lueckenvorgang.ruecknahme.ausser_zustaendigkeit": "outside our responsibility",
    "lueckenvorgang.ruecknahme.zurueckgezogen": "withdrawn by the askers",
    "lueckenvorgang.klara.titel": "{{name}} explains the process",
    "lueckenvorgang.klara.satz":
      "Status: {{phase}}. Next: {{schritt}}. This is the actual status of this process, not an expert review by {{name}}.",
    "lueckenvorgang.klara.demo":
      "{{name}} is currently in preview mode; this explanation still comes from the real process.",
    "lueckenvorgang.meldung.geloest": "Your question has been resolved",
    "lueckenvorgang.meldung.rueckfrage": "Follow-up on your question",
    "lueckenvorgang.meldung.rueckfrageBeantwortet": "Follow-up answered",
    "lueckenvorgang.meldungArt": "Knowledge gap",
    "lueckenvorgang.liste.geloest": "resolved",
    "lueckenvorgang.liste.zurueckgenommen": "withdrawn",
    "lueckenvorgang.liste.rueckfrageOffen": "follow-up open",
    "lueckenvorgang.frage.geloestTitel": "This question has already been answered on the merits",
    "lueckenvorgang.frage.geloestText":
      "Reviewed knowledge entry “{{titel}}”, version {{v}} — usable for you today. No new knowledge gap was created.",
    "lueckenvorgang.frage.geloestOeffnen": "Open entry",
    "lueckenvorgang.frage.vorgangOeffnen": "Follow the process of this question",
    "lueckenvorgang.seite.titel": "Process of a knowledge gap",
    "lueckenvorgang.seite.lead":
      "Who is responsible, what is happening and what comes next — as it applies to you today.",
    "lueckenvorgang.phase.zurueckgewiesen":
      "Reviewed on the merits and rejected with reasons — the statement stands",
    "lueckenvorgang.schritt.begruendung_lesen": "Read the reasons",
    "lueckenvorgang.abschluss.zurueckgewiesen":
      "Complaint rejected with reasons on {{datum}}. This is not a correction.",
    "lueckenvorgang.zurueckweisungQuelle": "Open the reviewed source (version {{v}})",
    "lueckenvorgang.zurueckweisen":
      "Reject the complaint with reasons (the reasons go to the reporters)",
    "lueckenvorgang.zurueckweisenSenden": "Reject with reasons",
    "lueckenvorgang.beanstandung.titel": "Disputed statement",
    "lueckenvorgang.beanstandung.zurueckgehalten":
      "The statement is withheld from you — you lack access to one of its sources.",
    "lueckenvorgang.beanstandung.quelleFehlt": "Reported: a source is missing",
    "lueckenvorgang.beanstandung.quelle": "Disputed in version {{fassungen}} of the source",
    "lueckenvorgang.beanstandung.quelleNichtZugaenglich": "Source not accessible to you",
    "lueckenvorgang.beanstandung.meldungen": "{{count}} report(s)",
    "lueckenvorgang.beanstandung.quelleOeffnen": "Open source",
    "lueckenvorgang.meldung.zurueckgewiesen": "Your complaint was rejected with reasons",
    "lueckenvorgang.liste.zurueckgewiesen": "rejected",
    "lueckenvorgang.liste.beanstandung": "Disputed statement of an answer",
  },
  nl: {
    "lueckenvorgang.oeffnen": "Verloop",
    "lueckenvorgang.einklappen": "Verloop inklappen",
    "lueckenvorgang.titel": "Verloop van deze vraag",
    "lueckenvorgang.laden": "Verloop wordt geladen …",
    "lueckenvorgang.nichtBeteiligt":
      "Dit verloop zien alleen de vragenstellers, de verantwoordelijke en beheerders.",
    "lueckenvorgang.fehler": "Het verloop kon niet worden geladen.",
    "lueckenvorgang.aktionFehler": "De stap is niet uitgevoerd.",
    "lueckenvorgang.stand": "Stand",
    "lueckenvorgang.naechster": "Volgende stap",
    "lueckenvorgang.fragende": "Gesteld door {{count}} persoon/personen",
    "lueckenvorgang.phase.ohne_zustaendigkeit":
      "Geen vakverantwoordelijke — de vraag ligt bij niemand",
    "lueckenvorgang.phase.zustaendigkeit_nicht_verfuegbar":
      "De verantwoordelijke is niet meer beschikbaar",
    "lueckenvorgang.phase.rueckfrage_offen": "Wedervraag aan de vragenstellers staat open",
    "lueckenvorgang.phase.in_bearbeitung": "In behandeling bij de verantwoordelijke",
    "lueckenvorgang.phase.in_fachpruefung": "Antwoordconcept in vakinhoudelijke controle",
    "lueckenvorgang.phase.bereit_zum_abschluss":
      "Vakinhoudelijke controle doorstaan — inhoudelijke afsluiting staat nog uit",
    "lueckenvorgang.phase.geloest": "Inhoudelijk opgelost",
    "lueckenvorgang.phase.zurueckgenommen":
      "Administratief ingetrokken — geen inhoudelijk antwoord",
    "lueckenvorgang.phase.geschlossen_ohne_nachweis":
      "Gesloten zonder vastgelegde afsluiting (oude gegevens)",
    "lueckenvorgang.schritt.zustaendigkeit_uebergeben":
      "Overdragen aan een bevoegde vakverantwoordelijke",
    "lueckenvorgang.schritt.zustaendigkeit_zuordnen": "Een vakverantwoordelijke toewijzen",
    "lueckenvorgang.schritt.neu_zuordnen": "Opnieuw toewijzen",
    "lueckenvorgang.schritt.rueckfrage_beantworten": "De wedervraag beantwoorden",
    "lueckenvorgang.schritt.antwort_auf_rueckfrage_abwarten":
      "Wachten op het antwoord van de vragenstellers",
    "lueckenvorgang.schritt.antwortentwurf_erfassen":
      "Antwoord vastleggen en het ingediende item koppelen",
    "lueckenvorgang.schritt.fachpruefung_abwarten":
      "De voorgeschreven vakinhoudelijke controle afwachten",
    "lueckenvorgang.schritt.fachlich_abschliessen": "Inhoudelijk afsluiten",
    "lueckenvorgang.schritt.bearbeitung_abwarten": "Niets te doen — de behandeling loopt",
    "lueckenvorgang.schritt.ergebnis_lesen": "Het resultaat lezen",
    "lueckenvorgang.schritt.erneut_fragen": "Indien nodig opnieuw vragen",
    "lueckenvorgang.schritt.keiner": "Geen stap open",
    "lueckenvorgang.rolle.fragend": "Jij hebt gevraagd",
    "lueckenvorgang.rolle.zustaendig": "Jij bent verantwoordelijk",
    "lueckenvorgang.rolle.verwaltend": "Jij beheert",
    "lueckenvorgang.zustaendig": "Verantwoordelijk",
    "lueckenvorgang.zustaendigNiemand": "niemand",
    "lueckenvorgang.zustaendigNichtVerfuegbar": "niet meer beschikbaar",
    "lueckenvorgang.verlauf": "Verloop van de verantwoordelijkheid",
    "lueckenvorgang.verlauf.zuordnung": "toegewezen aan {{name}}",
    "lueckenvorgang.verlauf.uebergabe": "overgedragen aan {{name}}",
    "lueckenvorgang.verlauf.neuzuordnung": "opnieuw toegewezen aan {{name}}",
    "lueckenvorgang.uebergeben": "Overdragen aan vakverantwoordelijke",
    "lueckenvorgang.uebergebenWaehlen": "Persoon kiezen",
    "lueckenvorgang.uebergebenHinweis":
      "Alleen personen met een vrijgegeven account en het recht om kennis vast te leggen worden aanvaard.",
    "lueckenvorgang.rueckfrage": "Wedervraag",
    "lueckenvorgang.rueckfrageOffen": "open",
    "lueckenvorgang.rueckfrageBeantwortet": "beantwoord",
    "lueckenvorgang.rueckfrageStellen": "Wedervraag aan de vragenstellers",
    "lueckenvorgang.rueckfrageSenden": "Wedervraag versturen",
    "lueckenvorgang.rueckfrageAntwort": "Antwoord aan de verantwoordelijke",
    "lueckenvorgang.rueckfrageAntwortSenden": "Antwoord versturen",
    "lueckenvorgang.rueckfrageVonMir": "door jou beantwoord",
    "lueckenvorgang.entwurf": "Antwoordconcept",
    "lueckenvorgang.entwurfErfassen": "Antwoord vastleggen",
    "lueckenvorgang.entwurfVerknuepfen": "Ingediend item koppelen",
    "lueckenvorgang.entwurfNichtZugaenglich": "Het gekoppelde item is voor jou niet toegankelijk.",
    "lueckenvorgang.ergebnis": "Resultaat",
    "lueckenvorgang.ergebnisOeffnen": "Kennisitem openen",
    "lueckenvorgang.ergebnisNichtZugaenglich":
      "Het resultaat is momenteel niet voor jou toegankelijk.",
    "lueckenvorgang.nichtNutzbar": "Geldt momenteel niet als resultaat",
    "lueckenvorgang.nutzbar": "Vakinhoudelijk vrijgegeven, geldig en voor jou bruikbaar",
    "lueckenvorgang.eintrag.fassung": "Versie {{v}}",
    "lueckenvorgang.eintrag.pruefung":
      "Vakinhoudelijke controle: {{gruen}} van {{benoetigt}} beoordelingen, {{rot}} rood",
    "lueckenvorgang.eintrag.pruefungUnbekannt": "Vakinhoudelijke controle: niet vast te stellen",
    "lueckenvorgang.eintrag.eigentuemer": "Verantwoordelijk: {{name}}",
    "lueckenvorgang.eintrag.sichtbarkeit": "Zichtbaarheid: {{stufe}}",
    "lueckenvorgang.eintrag.space": "aan een space gebonden",
    "lueckenvorgang.eintrag.quellen": "Bronnen: {{count}}",
    "lueckenvorgang.grund.nicht_vorhanden": "item niet aanwezig",
    "lueckenvorgang.grund.kein_zugriff": "geen toegang",
    "lueckenvorgang.grund.nicht_freigegeben": "nog niet vakinhoudelijk vrijgegeven",
    "lueckenvorgang.grund.bewertungen_fehlen": "voorgeschreven beoordelingen ontbreken",
    "lueckenvorgang.grund.negative_bewertung": "geblokkeerd door een negatieve beoordeling",
    "lueckenvorgang.grund.abgelaufen": "geldigheid verlopen",
    "lueckenvorgang.grund.quarantaene": "in quarantaine voor beschermde gegevens",
    "lueckenvorgang.grund.pruefstand_unbekannt": "controlestand niet vast te stellen",
    "lueckenvorgang.abschliessen": "Inhoudelijk afsluiten",
    "lueckenvorgang.abschliessenHinweis":
      "Sluit alleen af met een vakinhoudelijk vrijgegeven, geldig item in de actuele versie.",
    "lueckenvorgang.abschluss.fachlich": "Inhoudelijk opgelost op {{datum}} met versie {{v}}",
    "lueckenvorgang.abschluss.administrativ":
      "Administratief ingetrokken op {{datum}}: {{grund}}. Dit is geen inhoudelijk antwoord.",
    "lueckenvorgang.ruecknahme": "Administratief intrekken",
    "lueckenvorgang.ruecknahmeWaehlen": "Reden kiezen",
    "lueckenvorgang.ruecknahme.dublette": "duplicaat van een andere vraag",
    "lueckenvorgang.ruecknahme.nicht_beantwortbar": "niet te beantwoorden",
    "lueckenvorgang.ruecknahme.ausser_zustaendigkeit": "buiten onze verantwoordelijkheid",
    "lueckenvorgang.ruecknahme.zurueckgezogen": "door de vragenstellers ingetrokken",
    "lueckenvorgang.klara.titel": "{{name}} legt het verloop uit",
    "lueckenvorgang.klara.satz":
      "Stand: {{phase}}. Hierna: {{schritt}}. Dit is de werkelijke stand van dit verloop, geen vakinhoudelijke controle door {{name}}.",
    "lueckenvorgang.klara.demo":
      "{{name}} staat momenteel in voorbeeldmodus; deze uitleg komt toch uit het echte verloop.",
    "lueckenvorgang.meldung.geloest": "Je vraag is inhoudelijk opgelost",
    "lueckenvorgang.meldung.rueckfrage": "Wedervraag over je vraag",
    "lueckenvorgang.meldung.rueckfrageBeantwortet": "Wedervraag beantwoord",
    "lueckenvorgang.meldungArt": "Kennishiaat",
    "lueckenvorgang.liste.geloest": "opgelost",
    "lueckenvorgang.liste.zurueckgenommen": "ingetrokken",
    "lueckenvorgang.liste.rueckfrageOffen": "wedervraag open",
    "lueckenvorgang.frage.geloestTitel": "Deze vraag is al inhoudelijk beantwoord",
    "lueckenvorgang.frage.geloestText":
      "Gecontroleerd kennisitem ‘{{titel}}’, versie {{v}} — vandaag voor jou bruikbaar. Er is geen nieuw kennishiaat aangemaakt.",
    "lueckenvorgang.frage.geloestOeffnen": "Item openen",
    "lueckenvorgang.frage.vorgangOeffnen": "Verloop van deze vraag volgen",
    "lueckenvorgang.seite.titel": "Verloop van een kennishiaat",
    "lueckenvorgang.seite.lead":
      "Wie verantwoordelijk is, wat er gebeurt en wat hierna komt — zoals het vandaag voor jou geldt.",
    "lueckenvorgang.phase.zurueckgewiesen":
      "Inhoudelijk gecontroleerd en met redenen afgewezen — de uitspraak blijft",
    "lueckenvorgang.schritt.begruendung_lesen": "De motivering lezen",
    "lueckenvorgang.abschluss.zurueckgewiesen":
      "Klacht op {{datum}} met redenen afgewezen. Dit is geen correctie.",
    "lueckenvorgang.zurueckweisungQuelle": "Gecontroleerde bron openen (versie {{v}})",
    "lueckenvorgang.zurueckweisen":
      "Klacht met redenen afwijzen (de motivering gaat naar de melders)",
    "lueckenvorgang.zurueckweisenSenden": "Met redenen afwijzen",
    "lueckenvorgang.beanstandung.titel": "Betwiste uitspraak",
    "lueckenvorgang.beanstandung.zurueckgehalten":
      "De uitspraak wordt voor jou achtergehouden — je hebt geen toegang tot een van de bronnen.",
    "lueckenvorgang.beanstandung.quelleFehlt": "Gemeld: er ontbreekt een bron",
    "lueckenvorgang.beanstandung.quelle": "Betwist in versie {{fassungen}} van de bron",
    "lueckenvorgang.beanstandung.quelleNichtZugaenglich": "Bron niet voor jou toegankelijk",
    "lueckenvorgang.beanstandung.meldungen": "{{count}} melding(en)",
    "lueckenvorgang.beanstandung.quelleOeffnen": "Bron openen",
    "lueckenvorgang.meldung.zurueckgewiesen": "Je klacht is met redenen afgewezen",
    "lueckenvorgang.liste.zurueckgewiesen": "afgewezen",
    "lueckenvorgang.liste.beanstandung": "Betwiste uitspraak van een antwoord",
  },
} satisfies Textmodul;
