// ================================================================================================
// ADMIN-04 · NUTZER MIT ZUGANG UND VERANTWORTUNGSUMFANG — die Texte dieses Auftrags.
// ================================================================================================
//
// WOHER SIE KOMMEN: `produkt:20261009:admin-nutzer-uebersicht`. Flächen: die Kontenliste
// (`pages/Admin.tsx`), die Kontokarte (`pages/AdminKontenDetails.tsx`) und die Sammelbearbeitung
// (`pages/AdminKontenSammel.tsx`); das Modell steht in `lib/nutzerliste.ts`.
//
// WAS DIE SÄTZE NICHT BEHAUPTEN: einen letzten Besuch oder eine offene Einladung. Beides führt das
// Konto nicht — die Karte sagt das ausdrücklich, statt einen Wert zu schätzen.
//
// Die zwei `audit.action.*`-Schlüssel sind Altnamen-Muster: `lib/auditAction.ts` leitet sie aus den
// Protokollvorgängen `user.access-expiry-set` und `verantwortung.uebergabe` ab.
import type { Textmodul } from "./intern/pruefung";

export default {
  praefix: "nutzerliste.",
  legacySchluessel: ["audit.action.user_access_expiry_set", "audit.action.verantwortung_uebergabe"],
  de: {
    "audit.action.user_access_expiry_set": "Befristung geändert",
    "audit.action.verantwortung_uebergabe": "Hauptverantwortung übergeben",
    "nutzerliste.suche": "Suchen",
    "nutzerliste.sucheHilfe": "Nach Name oder E-Mail-Adresse suchen",
    "nutzerliste.rolleTitel": "Rolle",
    "nutzerliste.zugangTitel": "Zugang",
    "nutzerliste.alle": "alle",
    "nutzerliste.zugang.aktiv": "aktiv, unbefristet",
    "nutzerliste.zugang.befristet": "aktiv, befristet",
    "nutzerliste.zugang.abgelaufen": "abgelaufen",
    "nutzerliste.zugang.gesperrt": "gesperrt (wartet auf Freigabe)",
    "nutzerliste.treffer": "{{anzahl}} von {{gesamt}} Konten",
    "nutzerliste.leer": "Kein Konto passt zu diesen Filtern",
    "nutzerliste.zuruecksetzen": "Filter zurücksetzen",
    "nutzerliste.filter.suche": "Suche „{{suche}}“",
    "nutzerliste.filter.rolle": "Rolle: {{rolle}}",
    "nutzerliste.filter.zugang": "Zugang: {{zugang}}",
    "nutzerliste.verantwortung": "Verantwortung",
    "nutzerliste.zeile.beitraege": "Beiträge: {{anzahl}}",
    "nutzerliste.zeile.vorgaenge": "offene Vorgänge: {{anzahl}}",
    "nutzerliste.konto.zustand.aktiv": "Aktiv, unbefristet — kann sich anmelden.",
    "nutzerliste.konto.zustand.befristet":
      "Aktiv, befristet — kann sich bis zum Ende der Befristung anmelden.",
    "nutzerliste.konto.zustand.abgelaufen": "Abgelaufen — die Anmeldung ist nicht mehr möglich.",
    "nutzerliste.konto.zustand.gesperrt":
      "Gesperrt — wartet auf Freigabe; die Anmeldung ist nicht möglich.",
    "nutzerliste.konto.angelegt": "Angelegt am {{datum}}",
    "nutzerliste.konto.angelegtUnbekannt": "Anlagedatum nicht lesbar",
    "nutzerliste.konto.nichtErfasst": "Letzte Anmeldung und Einladungen erfasst Klarwerk nicht.",
    "nutzerliste.konto.beitraege": "Beiträge in Hauptverantwortung: {{anzahl}}",
    "nutzerliste.konto.beitraegeOeffnen": "Beiträge anzeigen",
    "nutzerliste.konto.vorgaengeTitel": "Andere offene Vorgänge",
    "nutzerliste.konto.vorgaenge":
      "Andere offene Vorgänge: Prüfaufgaben {{pruefaufgaben}} · Lücken {{luecken}} · Entwürfe {{entwuerfe}}",
    "nutzerliste.konto.vorgaengeOeffnen": "Vorgänge anzeigen",
    "nutzerliste.konto.pruefaufgabe": "Prüfaufgabe:",
    "nutzerliste.konto.luecke": "Lücke:",
    "nutzerliste.konto.entwurf": "Entwurf:",
    "nutzerliste.konto.nichtEinsehbar": "Beitrag ohne Leserecht",
    "nutzerliste.konto.protokoll": "Prüfprotokoll zu diesem Konto",
    "nutzerliste.konto.protokollLeer": "Noch kein Vermerk zu diesem Konto.",
    "nutzerliste.konto.vermerkBis": "bis {{datum}}",
    "nutzerliste.konto.vermerkUnbefristet": "unbefristet",
    "nutzerliste.rolle.wirkungKopf": "Wechsel von {{von}} zu {{nach}}",
    "nutzerliste.rolle.dazu": "Kommt hinzu",
    "nutzerliste.rolle.weg": "Fällt weg",
    "nutzerliste.rolle.hinweis":
      "Die Änderung gilt ab der nächsten Anfrage dieses Kontos. Der Server prüft sie; den letzten Admin stuft er nicht herab.",
    "nutzerliste.rolle.uebernehmen": "Rolle {{rolle}} übernehmen",
    "nutzerliste.rolle.bestaetigt":
      "Gespeichert: Die Rolle ist jetzt {{rolle}} (vom Server bestätigt).",
    "nutzerliste.rolle.gespeichertOhneStand": "Gespeichert. Der Stand wird vom Server neu geladen.",
    "nutzerliste.rolle.unveraendert": "Die Rolle ist unverändert.",
    "nutzerliste.rolle.ausgangOffen":
      "Ob die Änderung gespeichert wurde, ist offen; der Stand wird neu geladen.",
    "nutzerliste.frist.wirkung":
      "Wirkung: {{name}} kann sich bis zum Ende des {{datum}} anmelden, danach nicht mehr. Liegen noch Beiträge in der Hauptverantwortung dieses Kontos, lehnt der Server die Befristung ab, bis sie übergeben sind.",
    "nutzerliste.sammel.titel": "Mehrere Konten bearbeiten",
    "nutzerliste.sammel.auswahl": "Ausgewählt: {{anzahl}} von {{gesamt}} angezeigten Konten",
    "nutzerliste.sammel.alle": "Alle angezeigten auswählen",
    "nutzerliste.sammel.keine": "Auswahl leeren",
    "nutzerliste.sammel.aktionTitel": "Aktion",
    "nutzerliste.sammel.aktionWaehlen": "Bitte wählen",
    "nutzerliste.sammel.aktion.freigeben": "Freigeben",
    "nutzerliste.sammel.aktion.befristen": "Befristung setzen",
    "nutzerliste.sammel.pruefen": "Auswirkungen prüfen",
    "nutzerliste.sammel.ausfuehren": "Für {{anzahl}} Konten ausführen",
    "nutzerliste.sammel.laeuft": "Wird ausgeführt …",
    "nutzerliste.sammel.keineAuswahl": "Bitte zuerst mindestens ein Konto auswählen.",
    "nutzerliste.sammel.keineAktion": "Bitte zuerst eine Aktion wählen.",
    "nutzerliste.sammel.vorschauKopf": "Wirkt bei {{wirkt}} Konten · entfällt bei {{entfaellt}}",
    "nutzerliste.sammel.wirkt.freigeben": "wird freigegeben und kann sich danach anmelden",
    "nutzerliste.sammel.wirkt.befristen": "Zugang endet mit Ablauf des {{datum}}",
    "nutzerliste.sammel.entfaellt.schonFrei": "entfällt — ist bereits freigegeben",
    "nutzerliste.sammel.entfaellt.gesperrt":
      "entfällt — nicht freigegeben, eine Befristung würde nichts beenden",
    "nutzerliste.sammel.entfaellt.selbst": "entfällt — das eigene Konto wird hier nicht befristet",
    "nutzerliste.sammel.befristenHinweis":
      "Konten mit Beiträgen in Hauptverantwortung lehnt der Server einzeln ab; sie stehen danach mit Grund im Ergebnis.",
    "nutzerliste.sammel.bilanzVoll": "Ausgeführt für {{ok}} Konten.",
    "nutzerliste.sammel.bilanzTeil":
      "Nur teilweise ausgeführt: {{ok}} erledigt, {{fehler}} fehlgeschlagen.",
    "nutzerliste.sammel.zeileOk": "{{name}}: erledigt",
    "nutzerliste.sammel.zeileFehler": "{{name}}: fehlgeschlagen —",
    "nutzerliste.sammel.unveraendert": "Dieses Konto ist unverändert.",
    "nutzerliste.sammel.ausgangOffen":
      "Ob die Änderung gespeichert wurde, ist offen; die Liste wird neu geladen.",
    "nutzerliste.sammel.vorschauVeraltet":
      "Auswahl, Filter oder Kontostand haben sich seit der Prüfung geändert. Bitte die Auswirkungen erneut prüfen.",
  },
  en: {
    "audit.action.user_access_expiry_set": "Time limit changed",
    "audit.action.verantwortung_uebergabe": "Main responsibility handed over",
    "nutzerliste.suche": "Search",
    "nutzerliste.sucheHilfe": "Search by name or email address",
    "nutzerliste.rolleTitel": "Role",
    "nutzerliste.zugangTitel": "Access",
    "nutzerliste.alle": "all",
    "nutzerliste.zugang.aktiv": "active, no end date",
    "nutzerliste.zugang.befristet": "active, time-limited",
    "nutzerliste.zugang.abgelaufen": "expired",
    "nutzerliste.zugang.gesperrt": "locked (awaiting approval)",
    "nutzerliste.treffer": "{{anzahl}} of {{gesamt}} accounts",
    "nutzerliste.leer": "No account matches these filters",
    "nutzerliste.zuruecksetzen": "Reset filters",
    "nutzerliste.filter.suche": "Search “{{suche}}”",
    "nutzerliste.filter.rolle": "Role: {{rolle}}",
    "nutzerliste.filter.zugang": "Access: {{zugang}}",
    "nutzerliste.verantwortung": "Responsibility",
    "nutzerliste.zeile.beitraege": "Contributions: {{anzahl}}",
    "nutzerliste.zeile.vorgaenge": "open items: {{anzahl}}",
    "nutzerliste.konto.zustand.aktiv": "Active, no end date — can sign in.",
    "nutzerliste.konto.zustand.befristet":
      "Active, time-limited — can sign in until the time limit ends.",
    "nutzerliste.konto.zustand.abgelaufen": "Expired — signing in is no longer possible.",
    "nutzerliste.konto.zustand.gesperrt": "Locked — awaiting approval; signing in is not possible.",
    "nutzerliste.konto.angelegt": "Created on {{datum}}",
    "nutzerliste.konto.angelegtUnbekannt": "Creation date unreadable",
    "nutzerliste.konto.nichtErfasst": "Klarwerk does not record last sign-in or invitations.",
    "nutzerliste.konto.beitraege": "Contributions in main responsibility: {{anzahl}}",
    "nutzerliste.konto.beitraegeOeffnen": "Show contributions",
    "nutzerliste.konto.vorgaengeTitel": "Other open items",
    "nutzerliste.konto.vorgaenge":
      "Other open items: review tasks {{pruefaufgaben}} · gaps {{luecken}} · drafts {{entwuerfe}}",
    "nutzerliste.konto.vorgaengeOeffnen": "Show items",
    "nutzerliste.konto.pruefaufgabe": "Review task:",
    "nutzerliste.konto.luecke": "Gap:",
    "nutzerliste.konto.entwurf": "Draft:",
    "nutzerliste.konto.nichtEinsehbar": "Contribution without read access",
    "nutzerliste.konto.protokoll": "Audit log for this account",
    "nutzerliste.konto.protokollLeer": "No entry for this account yet.",
    "nutzerliste.konto.vermerkBis": "until {{datum}}",
    "nutzerliste.konto.vermerkUnbefristet": "no end date",
    "nutzerliste.rolle.wirkungKopf": "Change from {{von}} to {{nach}}",
    "nutzerliste.rolle.dazu": "Added",
    "nutzerliste.rolle.weg": "Removed",
    "nutzerliste.rolle.hinweis":
      "The change applies from this account's next request. The server checks it; it does not demote the last admin.",
    "nutzerliste.rolle.uebernehmen": "Apply role {{rolle}}",
    "nutzerliste.rolle.bestaetigt": "Saved: the role is now {{rolle}} (confirmed by the server).",
    "nutzerliste.rolle.gespeichertOhneStand": "Saved. The state is being reloaded from the server.",
    "nutzerliste.rolle.unveraendert": "The role is unchanged.",
    "nutzerliste.rolle.ausgangOffen":
      "Whether the change was saved is unknown; the state is being reloaded.",
    "nutzerliste.frist.wirkung":
      "Effect: {{name}} can sign in until the end of {{datum}}, not afterwards. If this account still holds contributions in main responsibility, the server rejects the time limit until they are handed over.",
    "nutzerliste.sammel.titel": "Edit several accounts",
    "nutzerliste.sammel.auswahl": "Selected: {{anzahl}} of {{gesamt}} shown accounts",
    "nutzerliste.sammel.alle": "Select all shown",
    "nutzerliste.sammel.keine": "Clear selection",
    "nutzerliste.sammel.aktionTitel": "Action",
    "nutzerliste.sammel.aktionWaehlen": "Please choose",
    "nutzerliste.sammel.aktion.freigeben": "Approve",
    "nutzerliste.sammel.aktion.befristen": "Set time limit",
    "nutzerliste.sammel.pruefen": "Check effects",
    "nutzerliste.sammel.ausfuehren": "Run for {{anzahl}} accounts",
    "nutzerliste.sammel.laeuft": "Running …",
    "nutzerliste.sammel.keineAuswahl": "Please select at least one account first.",
    "nutzerliste.sammel.keineAktion": "Please choose an action first.",
    "nutzerliste.sammel.vorschauKopf": "Applies to {{wirkt}} accounts · skipped for {{entfaellt}}",
    "nutzerliste.sammel.wirkt.freigeben": "will be approved and can then sign in",
    "nutzerliste.sammel.wirkt.befristen": "access ends at the end of {{datum}}",
    "nutzerliste.sammel.entfaellt.schonFrei": "skipped — already approved",
    "nutzerliste.sammel.entfaellt.gesperrt":
      "skipped — not approved, a time limit would end nothing",
    "nutzerliste.sammel.entfaellt.selbst": "skipped — your own account is not time-limited here",
    "nutzerliste.sammel.befristenHinweis":
      "The server rejects accounts holding contributions in main responsibility one by one; they then appear in the result with a reason.",
    "nutzerliste.sammel.bilanzVoll": "Done for {{ok}} accounts.",
    "nutzerliste.sammel.bilanzTeil": "Only partly done: {{ok}} done, {{fehler}} failed.",
    "nutzerliste.sammel.zeileOk": "{{name}}: done",
    "nutzerliste.sammel.zeileFehler": "{{name}}: failed —",
    "nutzerliste.sammel.unveraendert": "This account is unchanged.",
    "nutzerliste.sammel.ausgangOffen":
      "Whether the change was saved is unknown; the list is being reloaded.",
    "nutzerliste.sammel.vorschauVeraltet":
      "The selection, filters or account state have changed since the check. Please check the effects again.",
  },
  nl: {
    "audit.action.user_access_expiry_set": "Beperking gewijzigd",
    "audit.action.verantwortung_uebergabe": "Hoofdverantwoordelijkheid overgedragen",
    "nutzerliste.suche": "Zoeken",
    "nutzerliste.sucheHilfe": "Zoeken op naam of e-mailadres",
    "nutzerliste.rolleTitel": "Rol",
    "nutzerliste.zugangTitel": "Toegang",
    "nutzerliste.alle": "alle",
    "nutzerliste.zugang.aktiv": "actief, onbeperkt",
    "nutzerliste.zugang.befristet": "actief, beperkt",
    "nutzerliste.zugang.abgelaufen": "verlopen",
    "nutzerliste.zugang.gesperrt": "geblokkeerd (wacht op vrijgave)",
    "nutzerliste.treffer": "{{anzahl}} van {{gesamt}} accounts",
    "nutzerliste.leer": "Geen account past bij deze filters",
    "nutzerliste.zuruecksetzen": "Filters wissen",
    "nutzerliste.filter.suche": "Zoeken „{{suche}}”",
    "nutzerliste.filter.rolle": "Rol: {{rolle}}",
    "nutzerliste.filter.zugang": "Toegang: {{zugang}}",
    "nutzerliste.verantwortung": "Verantwoordelijkheid",
    "nutzerliste.zeile.beitraege": "Bijdragen: {{anzahl}}",
    "nutzerliste.zeile.vorgaenge": "open zaken: {{anzahl}}",
    "nutzerliste.konto.zustand.aktiv": "Actief, onbeperkt — kan zich aanmelden.",
    "nutzerliste.konto.zustand.befristet":
      "Actief, beperkt — kan zich aanmelden tot de beperking afloopt.",
    "nutzerliste.konto.zustand.abgelaufen": "Verlopen — aanmelden is niet meer mogelijk.",
    "nutzerliste.konto.zustand.gesperrt":
      "Geblokkeerd — wacht op vrijgave; aanmelden is niet mogelijk.",
    "nutzerliste.konto.angelegt": "Aangemaakt op {{datum}}",
    "nutzerliste.konto.angelegtUnbekannt": "Aanmaakdatum onleesbaar",
    "nutzerliste.konto.nichtErfasst":
      "Klarwerk legt de laatste aanmelding en uitnodigingen niet vast.",
    "nutzerliste.konto.beitraege": "Bijdragen in hoofdverantwoordelijkheid: {{anzahl}}",
    "nutzerliste.konto.beitraegeOeffnen": "Bijdragen tonen",
    "nutzerliste.konto.vorgaengeTitel": "Andere open zaken",
    "nutzerliste.konto.vorgaenge":
      "Andere open zaken: controletaken {{pruefaufgaben}} · lacunes {{luecken}} · concepten {{entwuerfe}}",
    "nutzerliste.konto.vorgaengeOeffnen": "Zaken tonen",
    "nutzerliste.konto.pruefaufgabe": "Controletaak:",
    "nutzerliste.konto.luecke": "Lacune:",
    "nutzerliste.konto.entwurf": "Concept:",
    "nutzerliste.konto.nichtEinsehbar": "Bijdrage zonder leesrecht",
    "nutzerliste.konto.protokoll": "Controlelogboek voor dit account",
    "nutzerliste.konto.protokollLeer": "Nog geen vermelding voor dit account.",
    "nutzerliste.konto.vermerkBis": "tot {{datum}}",
    "nutzerliste.konto.vermerkUnbefristet": "onbeperkt",
    "nutzerliste.rolle.wirkungKopf": "Wissel van {{von}} naar {{nach}}",
    "nutzerliste.rolle.dazu": "Komt erbij",
    "nutzerliste.rolle.weg": "Vervalt",
    "nutzerliste.rolle.hinweis":
      "De wijziging geldt vanaf het volgende verzoek van dit account. De server controleert haar; de laatste admin wordt niet teruggezet.",
    "nutzerliste.rolle.uebernehmen": "Rol {{rolle}} overnemen",
    "nutzerliste.rolle.bestaetigt":
      "Opgeslagen: de rol is nu {{rolle}} (bevestigd door de server).",
    "nutzerliste.rolle.gespeichertOhneStand":
      "Opgeslagen. De stand wordt opnieuw van de server geladen.",
    "nutzerliste.rolle.unveraendert": "De rol is ongewijzigd.",
    "nutzerliste.rolle.ausgangOffen":
      "Of de wijziging is opgeslagen, is onbekend; de stand wordt opnieuw geladen.",
    "nutzerliste.frist.wirkung":
      "Gevolg: {{name}} kan zich aanmelden tot het einde van {{datum}}, daarna niet meer. Heeft dit account nog bijdragen in hoofdverantwoordelijkheid, dan weigert de server de beperking tot ze zijn overgedragen.",
    "nutzerliste.sammel.titel": "Meerdere accounts bewerken",
    "nutzerliste.sammel.auswahl": "Geselecteerd: {{anzahl}} van {{gesamt}} getoonde accounts",
    "nutzerliste.sammel.alle": "Alle getoonde selecteren",
    "nutzerliste.sammel.keine": "Selectie wissen",
    "nutzerliste.sammel.aktionTitel": "Actie",
    "nutzerliste.sammel.aktionWaehlen": "Kies een actie",
    "nutzerliste.sammel.aktion.freigeben": "Vrijgeven",
    "nutzerliste.sammel.aktion.befristen": "Beperking instellen",
    "nutzerliste.sammel.pruefen": "Gevolgen controleren",
    "nutzerliste.sammel.ausfuehren": "Uitvoeren voor {{anzahl}} accounts",
    "nutzerliste.sammel.laeuft": "Wordt uitgevoerd …",
    "nutzerliste.sammel.keineAuswahl": "Selecteer eerst minstens één account.",
    "nutzerliste.sammel.keineAktion": "Kies eerst een actie.",
    "nutzerliste.sammel.vorschauKopf": "Geldt voor {{wirkt}} accounts · vervalt voor {{entfaellt}}",
    "nutzerliste.sammel.wirkt.freigeben": "wordt vrijgegeven en kan zich daarna aanmelden",
    "nutzerliste.sammel.wirkt.befristen": "toegang eindigt aan het einde van {{datum}}",
    "nutzerliste.sammel.entfaellt.schonFrei": "vervalt — is al vrijgegeven",
    "nutzerliste.sammel.entfaellt.gesperrt":
      "vervalt — niet vrijgegeven, een beperking zou niets beëindigen",
    "nutzerliste.sammel.entfaellt.selbst": "vervalt — het eigen account wordt hier niet beperkt",
    "nutzerliste.sammel.befristenHinweis":
      "Accounts met bijdragen in hoofdverantwoordelijkheid weigert de server afzonderlijk; ze staan daarna met reden in het resultaat.",
    "nutzerliste.sammel.bilanzVoll": "Uitgevoerd voor {{ok}} accounts.",
    "nutzerliste.sammel.bilanzTeil":
      "Slechts gedeeltelijk uitgevoerd: {{ok}} gelukt, {{fehler}} mislukt.",
    "nutzerliste.sammel.zeileOk": "{{name}}: gelukt",
    "nutzerliste.sammel.zeileFehler": "{{name}}: mislukt —",
    "nutzerliste.sammel.unveraendert": "Dit account is ongewijzigd.",
    "nutzerliste.sammel.ausgangOffen":
      "Of de wijziging is opgeslagen, is onbekend; de lijst wordt opnieuw geladen.",
    "nutzerliste.sammel.vorschauVeraltet":
      "Selectie, filters of accountstatus zijn sinds de controle gewijzigd. Controleer de gevolgen opnieuw.",
  },
} satisfies Textmodul;
