// ================================================================================================
// ADMIN-10 · QUALITÄTSAUFGABEN UND RÜCKMELDUNGEN — eine Übersicht auf bestehende Vorgänge.
// ================================================================================================
//
// Die Texte versprechen nichts, was die Fläche nicht tut: Übernehmen fordert die vorhandene
// Revalidierung an, „erledigt" steht nur mit Bestätigungsbeleg, und eine fehlende Zuständigkeit
// oder Frist wird ausgesprochen statt weggelassen.
import type { Textmodul } from "./intern/pruefung";

export default {
  praefix: "qualitaetsaufgaben.",
  legacySchluessel: [],
  de: {
    "qualitaetsaufgaben.titel": "Qualitätsaufgaben",
    "qualitaetsaufgaben.leitsatz":
      "Prüfungen, Revalidierungen, Konflikte, Duplikate, Wissenslücken und belegte Rückmeldungen an einem Ort. Jeder Eintrag öffnet den bestehenden Vorgang.",
    "qualitaetsaufgaben.zurueck": "Zur Verwaltung",
    "qualitaetsaufgaben.laedt": "Wird geladen …",
    "qualitaetsaufgaben.fehler": "Die Übersicht konnte nicht geladen werden.",
    "qualitaetsaufgaben.recht": "Diese Übersicht ist der Verwaltung vorbehalten.",
    "qualitaetsaufgaben.erneut": "Erneut laden",
    "qualitaetsaufgaben.aktualisieren": "Aktualisieren",
    "qualitaetsaufgaben.aktualisiertGerade": "Wird aktualisiert …",
    "qualitaetsaufgaben.stand": "Stand {{zeit}}",
    "qualitaetsaufgaben.quelleFehlt":
      "Nicht abrufbar: {{liste}}. Liste und Zahlen sind unvollständig — fehlende Einträge sind nicht erledigt.",
    "qualitaetsaufgaben.bilanz": "{{treffer}} von {{gesamt}} Vorgängen",
    "qualitaetsaufgaben.einmalGezaehlt":
      "{{einstiege}} Einstiege führen auf {{vorgaenge}} Vorgänge — jeder Vorgang zählt einmal.",
    "qualitaetsaufgaben.leer": "Nichts offen.",
    "qualitaetsaufgaben.leerUnvollstaendig":
      "In den abrufbaren Quellen steht nichts — die übrigen sind nicht geprüft.",
    "qualitaetsaufgaben.leerGefiltert": "Keine Einträge für diese Auswahl.",
    "qualitaetsaufgaben.filter.titel": "Filter",
    "qualitaetsaufgaben.filter.space": "Space",
    "qualitaetsaufgaben.filter.typ": "Art",
    "qualitaetsaufgaben.filter.zustand": "Zustand",
    "qualitaetsaufgaben.filter.zustaendig": "Zuständig",
    "qualitaetsaufgaben.filter.alle": "Alle",
    "qualitaetsaufgaben.filter.ohneSpace": "Ohne Space",
    "qualitaetsaufgaben.filter.niemand": "Niemand zugeordnet",
    "qualitaetsaufgaben.filter.option": "{{name}} ({{anzahl}})",
    "qualitaetsaufgaben.filter.zuruecksetzen": "Filter zurücksetzen",
    "qualitaetsaufgaben.typ.pruefung": "Prüfung",
    "qualitaetsaufgaben.typ.revalidierung": "Revalidierung",
    "qualitaetsaufgaben.typ.konflikt": "Konflikt",
    "qualitaetsaufgaben.typ.duplikat": "Duplikat",
    "qualitaetsaufgaben.typ.luecke": "Wissenslücke",
    "qualitaetsaufgaben.typ.rueckmeldung": "Rückmeldung",
    "qualitaetsaufgaben.zustand.offen": "Offen",
    "qualitaetsaufgaben.zustand.in_arbeit": "In Arbeit",
    "qualitaetsaufgaben.zustand.eskaliert": "Eskaliert",
    "qualitaetsaufgaben.zustand.erledigt": "Erledigt",
    "qualitaetsaufgaben.zustand.unklar": "Unklar – Signal fehlt",
    "qualitaetsaufgaben.zustaendigListe": "Zuständig: {{liste}}",
    "qualitaetsaufgaben.zustaendig.niemand": "Zuständig: niemand zugeordnet",
    "qualitaetsaufgaben.zustaendig.unbekannt": "Konto nicht mehr vorhanden",
    "qualitaetsaufgaben.zustaendig.pruefer": "{{name}} (Prüfung)",
    "qualitaetsaufgaben.zustaendig.verantwortlich": "{{name}} (verantwortlich)",
    "qualitaetsaufgaben.zustaendig.autor-ersatz":
      "{{name}} (Autor, keine verantwortliche Person benannt)",
    "qualitaetsaufgaben.zustaendig.zugewiesen": "{{name}} (zugewiesen)",
    "qualitaetsaufgaben.frist.keine": "Frist: nicht hinterlegt",
    "qualitaetsaufgaben.frist.am": "Frist: {{datum}}",
    "qualitaetsaufgaben.frist.ueberfaellig": "Frist: {{datum}} – überfällig",
    "qualitaetsaufgaben.seit.tage": "seit {{anzahl}} Tagen",
    "qualitaetsaufgaben.seit.heute": "seit heute",
    "qualitaetsaufgaben.seit.unbekannt": "Beginn nicht erfasst",
    "qualitaetsaufgaben.inhalt.keiner": "Ohne Wissensobjekt",
    "qualitaetsaufgaben.textZurueckgehalten": "Fragetext nur für Zuständige sichtbar",
    "qualitaetsaufgaben.einstiege": "Erreichbar über {{anzahl}} Einstiege, einmal gezählt",
    "qualitaetsaufgaben.einstieg.pruefboard": "Prüfboard",
    "qualitaetsaufgaben.einstieg.zuweisung": "Prüferzuweisung",
    "qualitaetsaufgaben.einstieg.lebenszyklus": "Lebenszyklus",
    "qualitaetsaufgaben.einstieg.anforderung": "Prüfanforderung",
    "qualitaetsaufgaben.einstieg.rueckmeldung": "Übernommene Rückmeldung",
    "qualitaetsaufgaben.einstieg.konflikte": "Konfliktboard",
    "qualitaetsaufgaben.einstieg.duplikate": "Duplikatboard",
    "qualitaetsaufgaben.einstieg.risiko": "Risiko-Board",
    "qualitaetsaufgaben.einstieg.glocke": "Meldungen der verantwortlichen Person",
    "qualitaetsaufgaben.oeffnen": "Bearbeiten",
    "qualitaetsaufgaben.oeffnenLabel": "{{typ}} bearbeiten: {{titel}}",
    "qualitaetsaufgaben.uebernehmen": "Als Aufgabe übernehmen",
    "qualitaetsaufgaben.uebernehmenLaeuft": "Wird übernommen …",
    "qualitaetsaufgaben.uebernahmeFortsetzen": "Übernahme fortsetzen",
    "qualitaetsaufgaben.uebernahme.nachgeholt":
      "Fortgesetzt: Die fehlende Revalidierung für „{{titel}}“ ist jetzt angefordert.",
    "qualitaetsaufgaben.uebernahme.angelegt":
      "Übernommen: Für „{{titel}}“ ist jetzt eine Revalidierung angefordert.",
    "qualitaetsaufgaben.uebernahme.angehaengt":
      "Übernommen: Die Rückmeldung hängt an der laufenden Revalidierung von „{{titel}}“.",
    "qualitaetsaufgaben.uebernahme.bereits":
      "Bereits übernommen am {{zeit}} durch {{wer}} — es wurde nichts doppelt angelegt.",
    "qualitaetsaufgaben.uebernahme.nichtGefunden":
      "Diese Rückmeldung ist nicht mehr verfügbar. Die Übersicht wurde neu geladen.",
    "qualitaetsaufgaben.uebernahme.fehler": "Übernehmen ist fehlgeschlagen: {{meldung}}",
    "qualitaetsaufgaben.rueckmeldung.uebernommen": "Übernommen am {{zeit}} durch {{wer}}",
    "qualitaetsaufgaben.rueckmeldung.ergebnis":
      "Ergebnis: am {{zeit}} von {{wer}} als weiterhin gültig bestätigt (Fassung {{fassung}})",
    "qualitaetsaufgaben.rueckmeldung.ergebnisOhneFassung":
      "Ergebnis: am {{zeit}} von {{wer}} als weiterhin gültig bestätigt",
    "qualitaetsaufgaben.rueckmeldung.unklar":
      "Übernommen, aber weder eine laufende Revalidierung noch eine Bestätigung danach gefunden — nicht als erledigt gewertet.",
    "qualitaetsaufgaben.rueckmeldung.rueckbezug": "Zum Ursprung",
    "qualitaetsaufgaben.rueckmeldungen.angehaengt": "Übernommene Rückmeldungen: {{anzahl}}",
  },
  en: {
    "qualitaetsaufgaben.titel": "Quality tasks",
    "qualitaetsaufgaben.leitsatz":
      "Reviews, revalidations, conflicts, duplicates, knowledge gaps and recorded feedback in one place. Each entry opens the existing case.",
    "qualitaetsaufgaben.zurueck": "Back to administration",
    "qualitaetsaufgaben.laedt": "Loading …",
    "qualitaetsaufgaben.fehler": "The overview could not be loaded.",
    "qualitaetsaufgaben.recht": "This overview is reserved for administration.",
    "qualitaetsaufgaben.erneut": "Load again",
    "qualitaetsaufgaben.aktualisieren": "Refresh",
    "qualitaetsaufgaben.aktualisiertGerade": "Refreshing …",
    "qualitaetsaufgaben.stand": "As of {{zeit}}",
    "qualitaetsaufgaben.quelleFehlt":
      "Not available: {{liste}}. List and numbers are incomplete — missing entries are not done.",
    "qualitaetsaufgaben.bilanz": "{{treffer}} of {{gesamt}} cases",
    "qualitaetsaufgaben.einmalGezaehlt":
      "{{einstiege}} entry points lead to {{vorgaenge}} cases — each case counts once.",
    "qualitaetsaufgaben.leer": "Nothing open.",
    "qualitaetsaufgaben.leerUnvollstaendig":
      "Nothing in the available sources — the others have not been checked.",
    "qualitaetsaufgaben.leerGefiltert": "No entries for this selection.",
    "qualitaetsaufgaben.filter.titel": "Filters",
    "qualitaetsaufgaben.filter.space": "Space",
    "qualitaetsaufgaben.filter.typ": "Type",
    "qualitaetsaufgaben.filter.zustand": "State",
    "qualitaetsaufgaben.filter.zustaendig": "Responsible",
    "qualitaetsaufgaben.filter.alle": "All",
    "qualitaetsaufgaben.filter.ohneSpace": "No space",
    "qualitaetsaufgaben.filter.niemand": "Nobody assigned",
    "qualitaetsaufgaben.filter.option": "{{name}} ({{anzahl}})",
    "qualitaetsaufgaben.filter.zuruecksetzen": "Reset filters",
    "qualitaetsaufgaben.typ.pruefung": "Review",
    "qualitaetsaufgaben.typ.revalidierung": "Revalidation",
    "qualitaetsaufgaben.typ.konflikt": "Conflict",
    "qualitaetsaufgaben.typ.duplikat": "Duplicate",
    "qualitaetsaufgaben.typ.luecke": "Knowledge gap",
    "qualitaetsaufgaben.typ.rueckmeldung": "Feedback",
    "qualitaetsaufgaben.zustand.offen": "Open",
    "qualitaetsaufgaben.zustand.in_arbeit": "In progress",
    "qualitaetsaufgaben.zustand.eskaliert": "Escalated",
    "qualitaetsaufgaben.zustand.erledigt": "Done",
    "qualitaetsaufgaben.zustand.unklar": "Unclear – signal missing",
    "qualitaetsaufgaben.zustaendigListe": "Responsible: {{liste}}",
    "qualitaetsaufgaben.zustaendig.niemand": "Responsible: nobody assigned",
    "qualitaetsaufgaben.zustaendig.unbekannt": "Account no longer exists",
    "qualitaetsaufgaben.zustaendig.pruefer": "{{name}} (review)",
    "qualitaetsaufgaben.zustaendig.verantwortlich": "{{name}} (responsible)",
    "qualitaetsaufgaben.zustaendig.autor-ersatz": "{{name}} (author, no responsible person named)",
    "qualitaetsaufgaben.zustaendig.zugewiesen": "{{name}} (assigned)",
    "qualitaetsaufgaben.frist.keine": "Deadline: not set",
    "qualitaetsaufgaben.frist.am": "Deadline: {{datum}}",
    "qualitaetsaufgaben.frist.ueberfaellig": "Deadline: {{datum}} – overdue",
    "qualitaetsaufgaben.seit.tage": "for {{anzahl}} days",
    "qualitaetsaufgaben.seit.heute": "since today",
    "qualitaetsaufgaben.seit.unbekannt": "Start not recorded",
    "qualitaetsaufgaben.inhalt.keiner": "No knowledge object",
    "qualitaetsaufgaben.textZurueckgehalten":
      "Question text visible to the responsible person only",
    "qualitaetsaufgaben.einstiege": "Reachable from {{anzahl}} entry points, counted once",
    "qualitaetsaufgaben.einstieg.pruefboard": "Review board",
    "qualitaetsaufgaben.einstieg.zuweisung": "Reviewer assignment",
    "qualitaetsaufgaben.einstieg.lebenszyklus": "Lifecycle",
    "qualitaetsaufgaben.einstieg.anforderung": "Revalidation request",
    "qualitaetsaufgaben.einstieg.rueckmeldung": "Adopted feedback",
    "qualitaetsaufgaben.einstieg.konflikte": "Conflict board",
    "qualitaetsaufgaben.einstieg.duplikate": "Duplicate board",
    "qualitaetsaufgaben.einstieg.risiko": "Risk board",
    "qualitaetsaufgaben.einstieg.glocke": "Notifications of the responsible person",
    "qualitaetsaufgaben.oeffnen": "Work on it",
    "qualitaetsaufgaben.oeffnenLabel": "Work on {{typ}}: {{titel}}",
    "qualitaetsaufgaben.uebernehmen": "Adopt as task",
    "qualitaetsaufgaben.uebernehmenLaeuft": "Adopting …",
    "qualitaetsaufgaben.uebernahmeFortsetzen": "Continue adoption",
    "qualitaetsaufgaben.uebernahme.nachgeholt":
      "Continued: the missing revalidation for “{{titel}}” is now requested.",
    "qualitaetsaufgaben.uebernahme.angelegt":
      "Adopted: a revalidation is now requested for “{{titel}}”.",
    "qualitaetsaufgaben.uebernahme.angehaengt":
      "Adopted: the feedback is attached to the running revalidation of “{{titel}}”.",
    "qualitaetsaufgaben.uebernahme.bereits":
      "Already adopted on {{zeit}} by {{wer}} — nothing was created twice.",
    "qualitaetsaufgaben.uebernahme.nichtGefunden":
      "This feedback is no longer available. The overview has been reloaded.",
    "qualitaetsaufgaben.uebernahme.fehler": "Adopting failed: {{meldung}}",
    "qualitaetsaufgaben.rueckmeldung.uebernommen": "Adopted on {{zeit}} by {{wer}}",
    "qualitaetsaufgaben.rueckmeldung.ergebnis":
      "Result: confirmed as still valid on {{zeit}} by {{wer}} (version {{fassung}})",
    "qualitaetsaufgaben.rueckmeldung.ergebnisOhneFassung":
      "Result: confirmed as still valid on {{zeit}} by {{wer}}",
    "qualitaetsaufgaben.rueckmeldung.unklar":
      "Adopted, but neither a running revalidation nor a later confirmation was found — not counted as done.",
    "qualitaetsaufgaben.rueckmeldung.rueckbezug": "To the origin",
    "qualitaetsaufgaben.rueckmeldungen.angehaengt": "Adopted feedback: {{anzahl}}",
  },
  nl: {
    "qualitaetsaufgaben.titel": "Kwaliteitstaken",
    "qualitaetsaufgaben.leitsatz":
      "Controles, hervalidaties, conflicten, duplicaten, kennislacunes en vastgelegde feedback op één plek. Elk item opent de bestaande zaak.",
    "qualitaetsaufgaben.zurueck": "Naar beheer",
    "qualitaetsaufgaben.laedt": "Wordt geladen …",
    "qualitaetsaufgaben.fehler": "Het overzicht kon niet worden geladen.",
    "qualitaetsaufgaben.recht": "Dit overzicht is voorbehouden aan beheer.",
    "qualitaetsaufgaben.erneut": "Opnieuw laden",
    "qualitaetsaufgaben.aktualisieren": "Vernieuwen",
    "qualitaetsaufgaben.aktualisiertGerade": "Wordt vernieuwd …",
    "qualitaetsaufgaben.stand": "Stand {{zeit}}",
    "qualitaetsaufgaben.quelleFehlt":
      "Niet beschikbaar: {{liste}}. Lijst en aantallen zijn onvolledig — ontbrekende items zijn niet afgehandeld.",
    "qualitaetsaufgaben.bilanz": "{{treffer}} van {{gesamt}} zaken",
    "qualitaetsaufgaben.einmalGezaehlt":
      "{{einstiege}} ingangen leiden naar {{vorgaenge}} zaken — elke zaak telt één keer.",
    "qualitaetsaufgaben.leer": "Niets open.",
    "qualitaetsaufgaben.leerUnvollstaendig":
      "In de beschikbare bronnen staat niets — de overige zijn niet gecontroleerd.",
    "qualitaetsaufgaben.leerGefiltert": "Geen items voor deze selectie.",
    "qualitaetsaufgaben.filter.titel": "Filters",
    "qualitaetsaufgaben.filter.space": "Space",
    "qualitaetsaufgaben.filter.typ": "Soort",
    "qualitaetsaufgaben.filter.zustand": "Status",
    "qualitaetsaufgaben.filter.zustaendig": "Verantwoordelijk",
    "qualitaetsaufgaben.filter.alle": "Alle",
    "qualitaetsaufgaben.filter.ohneSpace": "Zonder space",
    "qualitaetsaufgaben.filter.niemand": "Niemand toegewezen",
    "qualitaetsaufgaben.filter.option": "{{name}} ({{anzahl}})",
    "qualitaetsaufgaben.filter.zuruecksetzen": "Filters wissen",
    "qualitaetsaufgaben.typ.pruefung": "Controle",
    "qualitaetsaufgaben.typ.revalidierung": "Hervalidatie",
    "qualitaetsaufgaben.typ.konflikt": "Conflict",
    "qualitaetsaufgaben.typ.duplikat": "Duplicaat",
    "qualitaetsaufgaben.typ.luecke": "Kennislacune",
    "qualitaetsaufgaben.typ.rueckmeldung": "Feedback",
    "qualitaetsaufgaben.zustand.offen": "Open",
    "qualitaetsaufgaben.zustand.in_arbeit": "In behandeling",
    "qualitaetsaufgaben.zustand.eskaliert": "Geëscaleerd",
    "qualitaetsaufgaben.zustand.erledigt": "Afgehandeld",
    "qualitaetsaufgaben.zustand.unklar": "Onduidelijk – signaal ontbreekt",
    "qualitaetsaufgaben.zustaendigListe": "Verantwoordelijk: {{liste}}",
    "qualitaetsaufgaben.zustaendig.niemand": "Verantwoordelijk: niemand toegewezen",
    "qualitaetsaufgaben.zustaendig.unbekannt": "Account bestaat niet meer",
    "qualitaetsaufgaben.zustaendig.pruefer": "{{name}} (controle)",
    "qualitaetsaufgaben.zustaendig.verantwortlich": "{{name}} (verantwoordelijk)",
    "qualitaetsaufgaben.zustaendig.autor-ersatz":
      "{{name}} (auteur, geen verantwoordelijke benoemd)",
    "qualitaetsaufgaben.zustaendig.zugewiesen": "{{name}} (toegewezen)",
    "qualitaetsaufgaben.frist.keine": "Termijn: niet vastgelegd",
    "qualitaetsaufgaben.frist.am": "Termijn: {{datum}}",
    "qualitaetsaufgaben.frist.ueberfaellig": "Termijn: {{datum}} – verlopen",
    "qualitaetsaufgaben.seit.tage": "sinds {{anzahl}} dagen",
    "qualitaetsaufgaben.seit.heute": "sinds vandaag",
    "qualitaetsaufgaben.seit.unbekannt": "Begin niet vastgelegd",
    "qualitaetsaufgaben.inhalt.keiner": "Zonder kennisobject",
    "qualitaetsaufgaben.textZurueckgehalten":
      "Vraagtekst alleen zichtbaar voor de verantwoordelijke",
    "qualitaetsaufgaben.einstiege": "Bereikbaar via {{anzahl}} ingangen, één keer geteld",
    "qualitaetsaufgaben.einstieg.pruefboard": "Controlebord",
    "qualitaetsaufgaben.einstieg.zuweisung": "Toewijzing controleur",
    "qualitaetsaufgaben.einstieg.lebenszyklus": "Levenscyclus",
    "qualitaetsaufgaben.einstieg.anforderung": "Hervalidatieverzoek",
    "qualitaetsaufgaben.einstieg.rueckmeldung": "Overgenomen feedback",
    "qualitaetsaufgaben.einstieg.konflikte": "Conflictenbord",
    "qualitaetsaufgaben.einstieg.duplikate": "Duplicatenbord",
    "qualitaetsaufgaben.einstieg.risiko": "Risicobord",
    "qualitaetsaufgaben.einstieg.glocke": "Meldingen van de verantwoordelijke",
    "qualitaetsaufgaben.oeffnen": "Bewerken",
    "qualitaetsaufgaben.oeffnenLabel": "{{typ}} bewerken: {{titel}}",
    "qualitaetsaufgaben.uebernehmen": "Als taak overnemen",
    "qualitaetsaufgaben.uebernehmenLaeuft": "Wordt overgenomen …",
    "qualitaetsaufgaben.uebernahmeFortsetzen": "Overname voortzetten",
    "qualitaetsaufgaben.uebernahme.nachgeholt":
      "Voortgezet: de ontbrekende hervalidatie voor ‘{{titel}}’ is nu aangevraagd.",
    "qualitaetsaufgaben.uebernahme.angelegt":
      "Overgenomen: voor ‘{{titel}}’ is nu een hervalidatie aangevraagd.",
    "qualitaetsaufgaben.uebernahme.angehaengt":
      "Overgenomen: de feedback hangt aan de lopende hervalidatie van ‘{{titel}}’.",
    "qualitaetsaufgaben.uebernahme.bereits":
      "Al overgenomen op {{zeit}} door {{wer}} — er is niets dubbel aangemaakt.",
    "qualitaetsaufgaben.uebernahme.nichtGefunden":
      "Deze feedback is niet meer beschikbaar. Het overzicht is opnieuw geladen.",
    "qualitaetsaufgaben.uebernahme.fehler": "Overnemen is mislukt: {{meldung}}",
    "qualitaetsaufgaben.rueckmeldung.uebernommen": "Overgenomen op {{zeit}} door {{wer}}",
    "qualitaetsaufgaben.rueckmeldung.ergebnis":
      "Resultaat: op {{zeit}} door {{wer}} bevestigd als nog geldig (versie {{fassung}})",
    "qualitaetsaufgaben.rueckmeldung.ergebnisOhneFassung":
      "Resultaat: op {{zeit}} door {{wer}} bevestigd als nog geldig",
    "qualitaetsaufgaben.rueckmeldung.unklar":
      "Overgenomen, maar geen lopende hervalidatie en geen latere bevestiging gevonden — niet als afgehandeld geteld.",
    "qualitaetsaufgaben.rueckmeldung.rueckbezug": "Naar de oorsprong",
    "qualitaetsaufgaben.rueckmeldungen.angehaengt": "Overgenomen feedback: {{anzahl}}",
  },
} satisfies Textmodul;
