// ================================================================================================
// SPACES — die Texte der Seite `/spaces`, der Spacezeile am Artikel und des Spacekontexts in Klara.
// ================================================================================================
//
// Auftrag `produkt:20261007:spaces`. DE/EN/NL, weil der Textmodulvertrag jede Sprache der
// Oberfläche verlangt (docs/i18n-textmodule.md).
import type { Textmodul } from "./intern/pruefung";

export default {
  praefix: "spaces.",
  legacySchluessel: [],
  de: {
    "spaces.seite.titel": "Spaces",
    "spaces.seite.lead":
      "Arbeitsräume mit Zweck, Mitgliedern und Zuständigkeit. Ein Artikel hat genau einen führenden Space; Tags und gespeicherte Ansichten zeigen dasselbe Objekt an weiteren Stellen.",
    "spaces.seite.grenze":
      "Ein Space ist kein Ordner: es gibt keine Unterordner und keine Kopien. Der führende Space bestimmt, wer einen Artikel sehen darf — zusätzlich zur Vertraulichkeitsstufe.",
    "spaces.seite.neu": "Space anlegen",
    "spaces.seite.bearbeiten": "Space bearbeiten",
    "spaces.seite.laedt": "Spaces werden geladen …",
    "spaces.seite.leer": "Es gibt noch keinen Space, den du sehen darfst.",
    "spaces.seite.zurueck": "Alle Spaces",
    "spaces.seite.oeffnen": "Öffnen",
    "spaces.seite.artikelZahl": "{{anzahl}} sichtbare Artikel",
    "spaces.feld.name": "Name",
    "spaces.feld.zweck": "Zweck",
    "spaces.feld.verantwortlich": "Spacezuständigkeit",
    "spaces.feld.zugang": "Zugang zu den Inhalten",
    "spaces.feld.zugangAlle": "Alle mit Leserecht",
    "spaces.feld.zugangMitglieder": "Nur Mitglieder und Zuständige",
    "spaces.feld.mitglieder": "Mitglieder",
    "spaces.feld.mitgliedWaehlen": "Konto wählen",
    "spaces.feld.mitgliedHinzu": "Mitglied hinzufügen",
    "spaces.feld.entfernen": "Entfernen",
    "spaces.feld.ansichten": "Gespeicherte Ansichten (Tag)",
    "spaces.feld.ansichtName": "Name der Ansicht",
    "spaces.feld.ansichtTag": "Tag",
    "spaces.feld.ansichtHinzu": "Ansicht hinzufügen",
    "spaces.feld.teams": "Teams",
    "spaces.feld.teamRecht": "Recht für Team {{name}}",
    "spaces.feld.teamWaehlen": "Team wählen",
    "spaces.feld.teamHinzu": "Team binden",
    "spaces.formular.teamHinweis":
      "Jedes aktive Mitglied eines gebundenen Teams erhält dieses Recht — zusätzlich zu direkten Mitgliedschaften.",
    "spaces.team.archiviert": "archiviert, gewährt nichts mehr",
    "spaces.detail.teamMitglieder": "Über Teams",
    "spaces.formular.speichern": "Speichern",
    "spaces.formular.abbrechen": "Abbrechen",
    "spaces.formular.hinweis":
      "Jede Änderung ist eine neue Fassung des Space. Die Verantwortung für einzelne Artikel bleibt davon getrennt.",
    "spaces.recht.lesen": "lesen",
    "spaces.recht.schreiben": "schreiben",
    "spaces.eigenesRecht.zustaendig": "Du bist zuständig",
    "spaces.eigenesRecht.schreiben": "Du darfst Artikel hinein- und herausbewegen",
    "spaces.eigenesRecht.lesen": "Du darfst die Inhalte lesen",
    "spaces.eigenesRecht.verwalten": "Du verwaltest Konten, liest die Inhalte aber nicht",
    "spaces.eigenesRecht.keins": "Kein Zugang",
    "spaces.zugang.alle": "Offen für alle mit Leserecht",
    "spaces.zugang.mitglieder": "Nur Mitglieder",
    "spaces.detail.zustaendig": "Spacezuständigkeit: {{name}}",
    "spaces.detail.artikel": "Artikel mit diesem führenden Space",
    "spaces.detail.ansicht":
      "Ansicht „{{name}}“ — alle für dich sichtbaren Artikel mit dem Tag „{{tag}}“",
    "spaces.detail.keineArtikel": "Hier gibt es keinen Artikel, den du sehen darfst.",
    "spaces.detail.ausSpace": "Führender Space: {{name}}",
    "spaces.detail.ohneSpace": "Ohne Space",
    "spaces.detail.fassung": "Fassung {{version}}",
    "spaces.detail.verlauf": "Verlauf",
    "spaces.detail.verlaufEintrag": "Fassung {{version}} · {{zeit}} · {{wer}}",
    "spaces.detail.nichtGefunden": "Diesen Space gibt es nicht oder du darfst ihn nicht sehen.",
    "spaces.artikel.titel": "Space und Verantwortung",
    "spaces.artikel.fuehrend": "Führender Space",
    "spaces.artikel.keiner":
      "Kein Space — sichtbar nach der Vertraulichkeitsstufe für alle mit Leserecht.",
    "spaces.artikel.spaceZustaendig": "Spacezuständigkeit",
    "spaces.artikel.verantwortung": "Artikelverantwortung",
    "spaces.artikel.verantwortungErsatz": "kein Eigentümer benannt — der Autor trägt sie",
    "spaces.artikel.autor": "Autor",
    "spaces.artikel.verschieben": "Space wechseln",
    "spaces.artikel.ziel": "Neuer führender Space",
    "spaces.artikel.ohneSpace": "Ohne Space",
    "spaces.artikel.vorschau": "Rechtewirkung prüfen",
    "spaces.artikel.alleSpaces": "Alle Spaces",
    "spaces.vorschau.titel": "Rechtewirkung vor der Übernahme",
    "spaces.vorschau.von": "Von: {{quelle}} → Nach: {{ziel}}",
    "spaces.vorschau.verlieren": "Verlieren den Zugang ({{anzahl}})",
    "spaces.vorschau.erhalten": "Erhalten Zugang ({{anzahl}})",
    "spaces.vorschau.niemand": "niemand",
    "spaces.vorschau.unveraendert": "Unverändert mit Zugang: {{anzahl}}",
    "spaces.vorschau.autorVerliert": "Achtung: Der Autor verliert danach den Zugang.",
    "spaces.vorschau.verantwortlicheVerliert":
      "Achtung: Die Artikelverantwortliche Person verliert danach den Zugang.",
    "spaces.vorschau.bleibt":
      "Bleibt unverändert: Fassung {{version}}, Autor {{autor}}, {{history}} Historieneinträge, Artikelverantwortung {{verantwortung}}.",
    "spaces.vorschau.uebernehmen": "Wechsel übernehmen",
    "spaces.vorschau.abbrechen": "Abbrechen",
    "spaces.vorschau.veraltet":
      "Die Rechtelage hat sich seit der Vorschau geändert. Bitte die neue Vorschau prüfen.",
    "spaces.vorschau.erfolg": "Der Space wurde gewechselt. Fassung und Historie sind unverändert.",
    "spaces.fehler.allgemein": "Das hat nicht geklappt. Bitte erneut versuchen.",
    "spaces.fehler.ungueltig": "Bitte Name, Zweck und Zuständigkeit vollständig angeben.",
    "spaces.fehler.veraltet": "Der Space wurde inzwischen geändert. Bitte neu laden.",
    "spaces.fehler.recht": "Dafür fehlt dir das Recht.",
    "spaces.klara.label": "Space",
    "spaces.klara.inSpace": "Du bist im Space „{{name}}“.",
    "spaces.klara.artikelInSpace": "Dieser Artikel gehört zum Space „{{name}}“.",
    "spaces.klara.artikelOhneSpace": "Dieser Artikel gehört zu keinem Space.",
    "spaces.klara.zweck": "Zweck: {{zweck}}",
    "spaces.klara.zustaendig":
      "Spacezuständigkeit: {{name}} · Artikelverantwortung: {{verantwortung}}",
    "spaces.klara.zustaendigSpace": "Spacezuständigkeit: {{name}}",
    "spaces.klara.antwortGrenze":
      "Meine Antworten aus dem Wissen stützen sich nur auf Artikel, die du nach Space und Stufe sehen darfst.",
  },
  en: {
    "spaces.seite.titel": "Spaces",
    "spaces.seite.lead":
      "Workspaces with a purpose, members and an owner. An article has exactly one leading space; tags and saved views show the same object in further places.",
    "spaces.seite.grenze":
      "A space is not a folder: there are no subfolders and no copies. The leading space decides who may see an article — in addition to its confidentiality level.",
    "spaces.seite.neu": "Create space",
    "spaces.seite.bearbeiten": "Edit space",
    "spaces.seite.laedt": "Loading spaces …",
    "spaces.seite.leer": "There is no space you are allowed to see yet.",
    "spaces.seite.zurueck": "All spaces",
    "spaces.seite.oeffnen": "Open",
    "spaces.seite.artikelZahl": "{{anzahl}} visible articles",
    "spaces.feld.name": "Name",
    "spaces.feld.zweck": "Purpose",
    "spaces.feld.verantwortlich": "Space owner",
    "spaces.feld.zugang": "Access to the contents",
    "spaces.feld.zugangAlle": "Everyone with read access",
    "spaces.feld.zugangMitglieder": "Members and owner only",
    "spaces.feld.mitglieder": "Members",
    "spaces.feld.mitgliedWaehlen": "Choose account",
    "spaces.feld.mitgliedHinzu": "Add member",
    "spaces.feld.entfernen": "Remove",
    "spaces.feld.ansichten": "Saved views (tag)",
    "spaces.feld.ansichtName": "View name",
    "spaces.feld.ansichtTag": "Tag",
    "spaces.feld.ansichtHinzu": "Add view",
    "spaces.feld.teams": "Teams",
    "spaces.feld.teamRecht": "Right for team {{name}}",
    "spaces.feld.teamWaehlen": "Choose team",
    "spaces.feld.teamHinzu": "Bind team",
    "spaces.formular.teamHinweis":
      "Every active member of a bound team receives this right — in addition to direct memberships.",
    "spaces.team.archiviert": "archived, grants nothing",
    "spaces.detail.teamMitglieder": "Via teams",
    "spaces.formular.speichern": "Save",
    "spaces.formular.abbrechen": "Cancel",
    "spaces.formular.hinweis":
      "Every change is a new version of the space. Responsibility for individual articles stays separate.",
    "spaces.recht.lesen": "read",
    "spaces.recht.schreiben": "write",
    "spaces.eigenesRecht.zustaendig": "You own this space",
    "spaces.eigenesRecht.schreiben": "You may move articles in and out",
    "spaces.eigenesRecht.lesen": "You may read the contents",
    "spaces.eigenesRecht.verwalten": "You manage accounts but do not read the contents",
    "spaces.eigenesRecht.keins": "No access",
    "spaces.zugang.alle": "Open to everyone with read access",
    "spaces.zugang.mitglieder": "Members only",
    "spaces.detail.zustaendig": "Space owner: {{name}}",
    "spaces.detail.artikel": "Articles with this leading space",
    "spaces.detail.ansicht": "View “{{name}}” — all articles visible to you tagged “{{tag}}”",
    "spaces.detail.keineArtikel": "There is no article here you are allowed to see.",
    "spaces.detail.ausSpace": "Leading space: {{name}}",
    "spaces.detail.ohneSpace": "No space",
    "spaces.detail.fassung": "Version {{version}}",
    "spaces.detail.verlauf": "History",
    "spaces.detail.verlaufEintrag": "Version {{version}} · {{zeit}} · {{wer}}",
    "spaces.detail.nichtGefunden": "This space does not exist or you may not see it.",
    "spaces.artikel.titel": "Space and responsibility",
    "spaces.artikel.fuehrend": "Leading space",
    "spaces.artikel.keiner":
      "No space — visible to everyone with read access according to its confidentiality level.",
    "spaces.artikel.spaceZustaendig": "Space owner",
    "spaces.artikel.verantwortung": "Article responsibility",
    "spaces.artikel.verantwortungErsatz": "no owner named — the author carries it",
    "spaces.artikel.autor": "Author",
    "spaces.artikel.verschieben": "Change space",
    "spaces.artikel.ziel": "New leading space",
    "spaces.artikel.ohneSpace": "No space",
    "spaces.artikel.vorschau": "Check effect on access",
    "spaces.artikel.alleSpaces": "All spaces",
    "spaces.vorschau.titel": "Effect on access before applying",
    "spaces.vorschau.von": "From: {{quelle}} → To: {{ziel}}",
    "spaces.vorschau.verlieren": "Lose access ({{anzahl}})",
    "spaces.vorschau.erhalten": "Gain access ({{anzahl}})",
    "spaces.vorschau.niemand": "nobody",
    "spaces.vorschau.unveraendert": "Unchanged with access: {{anzahl}}",
    "spaces.vorschau.autorVerliert": "Attention: the author will lose access.",
    "spaces.vorschau.verantwortlicheVerliert":
      "Attention: the person responsible for the article will lose access.",
    "spaces.vorschau.bleibt":
      "Stays unchanged: version {{version}}, author {{autor}}, {{history}} history entries, article responsibility {{verantwortung}}.",
    "spaces.vorschau.uebernehmen": "Apply change",
    "spaces.vorschau.abbrechen": "Cancel",
    "spaces.vorschau.veraltet":
      "Access has changed since the preview. Please review the new preview.",
    "spaces.vorschau.erfolg": "The space was changed. Version and history are unchanged.",
    "spaces.fehler.allgemein": "That did not work. Please try again.",
    "spaces.fehler.ungueltig": "Please provide name, purpose and owner.",
    "spaces.fehler.veraltet": "The space has changed in the meantime. Please reload.",
    "spaces.fehler.recht": "You are not allowed to do that.",
    "spaces.klara.label": "Space",
    "spaces.klara.inSpace": "You are in the space “{{name}}”.",
    "spaces.klara.artikelInSpace": "This article belongs to the space “{{name}}”.",
    "spaces.klara.artikelOhneSpace": "This article belongs to no space.",
    "spaces.klara.zweck": "Purpose: {{zweck}}",
    "spaces.klara.zustaendig": "Space owner: {{name}} · Article responsibility: {{verantwortung}}",
    "spaces.klara.zustaendigSpace": "Space owner: {{name}}",
    "spaces.klara.antwortGrenze":
      "My answers from the knowledge base only use articles you may see by space and level.",
  },
  nl: {
    "spaces.seite.titel": "Spaces",
    "spaces.seite.lead":
      "Werkruimtes met een doel, leden en een verantwoordelijke. Een artikel heeft precies één leidende space; tags en opgeslagen weergaven tonen hetzelfde object op meer plekken.",
    "spaces.seite.grenze":
      "Een space is geen map: er zijn geen submappen en geen kopieën. De leidende space bepaalt wie een artikel mag zien — naast het vertrouwelijkheidsniveau.",
    "spaces.seite.neu": "Space aanmaken",
    "spaces.seite.bearbeiten": "Space bewerken",
    "spaces.seite.laedt": "Spaces worden geladen …",
    "spaces.seite.leer": "Er is nog geen space die je mag zien.",
    "spaces.seite.zurueck": "Alle spaces",
    "spaces.seite.oeffnen": "Openen",
    "spaces.seite.artikelZahl": "{{anzahl}} zichtbare artikelen",
    "spaces.feld.name": "Naam",
    "spaces.feld.zweck": "Doel",
    "spaces.feld.verantwortlich": "Verantwoordelijke van de space",
    "spaces.feld.zugang": "Toegang tot de inhoud",
    "spaces.feld.zugangAlle": "Iedereen met leesrecht",
    "spaces.feld.zugangMitglieder": "Alleen leden en verantwoordelijke",
    "spaces.feld.mitglieder": "Leden",
    "spaces.feld.mitgliedWaehlen": "Account kiezen",
    "spaces.feld.mitgliedHinzu": "Lid toevoegen",
    "spaces.feld.entfernen": "Verwijderen",
    "spaces.feld.ansichten": "Opgeslagen weergaven (tag)",
    "spaces.feld.ansichtName": "Naam van de weergave",
    "spaces.feld.ansichtTag": "Tag",
    "spaces.feld.ansichtHinzu": "Weergave toevoegen",
    "spaces.feld.teams": "Teams",
    "spaces.feld.teamRecht": "Recht voor team {{name}}",
    "spaces.feld.teamWaehlen": "Team kiezen",
    "spaces.feld.teamHinzu": "Team koppelen",
    "spaces.formular.teamHinweis":
      "Elk actief lid van een gekoppeld team krijgt dit recht — naast directe lidmaatschappen.",
    "spaces.team.archiviert": "gearchiveerd, verleent niets meer",
    "spaces.detail.teamMitglieder": "Via teams",
    "spaces.formular.speichern": "Opslaan",
    "spaces.formular.abbrechen": "Annuleren",
    "spaces.formular.hinweis":
      "Elke wijziging is een nieuwe versie van de space. De verantwoordelijkheid voor afzonderlijke artikelen blijft daarvan gescheiden.",
    "spaces.recht.lesen": "lezen",
    "spaces.recht.schreiben": "schrijven",
    "spaces.eigenesRecht.zustaendig": "Jij bent verantwoordelijk",
    "spaces.eigenesRecht.schreiben": "Je mag artikelen erin en eruit verplaatsen",
    "spaces.eigenesRecht.lesen": "Je mag de inhoud lezen",
    "spaces.eigenesRecht.verwalten": "Je beheert accounts, maar leest de inhoud niet",
    "spaces.eigenesRecht.keins": "Geen toegang",
    "spaces.zugang.alle": "Open voor iedereen met leesrecht",
    "spaces.zugang.mitglieder": "Alleen leden",
    "spaces.detail.zustaendig": "Verantwoordelijke van de space: {{name}}",
    "spaces.detail.artikel": "Artikelen met deze leidende space",
    "spaces.detail.ansicht":
      "Weergave „{{name}}” — alle voor jou zichtbare artikelen met de tag „{{tag}}”",
    "spaces.detail.keineArtikel": "Hier is geen artikel dat je mag zien.",
    "spaces.detail.ausSpace": "Leidende space: {{name}}",
    "spaces.detail.ohneSpace": "Geen space",
    "spaces.detail.fassung": "Versie {{version}}",
    "spaces.detail.verlauf": "Verloop",
    "spaces.detail.verlaufEintrag": "Versie {{version}} · {{zeit}} · {{wer}}",
    "spaces.detail.nichtGefunden": "Deze space bestaat niet of je mag hem niet zien.",
    "spaces.artikel.titel": "Space en verantwoordelijkheid",
    "spaces.artikel.fuehrend": "Leidende space",
    "spaces.artikel.keiner":
      "Geen space — zichtbaar voor iedereen met leesrecht volgens het vertrouwelijkheidsniveau.",
    "spaces.artikel.spaceZustaendig": "Verantwoordelijke van de space",
    "spaces.artikel.verantwortung": "Verantwoordelijkheid voor het artikel",
    "spaces.artikel.verantwortungErsatz": "geen eigenaar genoemd — de auteur draagt die",
    "spaces.artikel.autor": "Auteur",
    "spaces.artikel.verschieben": "Space wijzigen",
    "spaces.artikel.ziel": "Nieuwe leidende space",
    "spaces.artikel.ohneSpace": "Geen space",
    "spaces.artikel.vorschau": "Effect op toegang controleren",
    "spaces.artikel.alleSpaces": "Alle spaces",
    "spaces.vorschau.titel": "Effect op toegang vóór het overnemen",
    "spaces.vorschau.von": "Van: {{quelle}} → Naar: {{ziel}}",
    "spaces.vorschau.verlieren": "Verliezen toegang ({{anzahl}})",
    "spaces.vorschau.erhalten": "Krijgen toegang ({{anzahl}})",
    "spaces.vorschau.niemand": "niemand",
    "spaces.vorschau.unveraendert": "Ongewijzigd met toegang: {{anzahl}}",
    "spaces.vorschau.autorVerliert": "Let op: de auteur verliest daarna de toegang.",
    "spaces.vorschau.verantwortlicheVerliert":
      "Let op: de verantwoordelijke voor het artikel verliest daarna de toegang.",
    "spaces.vorschau.bleibt":
      "Blijft ongewijzigd: versie {{version}}, auteur {{autor}}, {{history}} historie-items, verantwoordelijkheid {{verantwortung}}.",
    "spaces.vorschau.uebernehmen": "Wijziging overnemen",
    "spaces.vorschau.abbrechen": "Annuleren",
    "spaces.vorschau.veraltet":
      "De toegang is sinds de voorvertoning gewijzigd. Controleer de nieuwe voorvertoning.",
    "spaces.vorschau.erfolg": "De space is gewijzigd. Versie en historie zijn ongewijzigd.",
    "spaces.fehler.allgemein": "Dat is niet gelukt. Probeer het opnieuw.",
    "spaces.fehler.ungueltig": "Vul naam, doel en verantwoordelijke volledig in.",
    "spaces.fehler.veraltet": "De space is inmiddels gewijzigd. Laad opnieuw.",
    "spaces.fehler.recht": "Daarvoor heb je geen recht.",
    "spaces.klara.label": "Space",
    "spaces.klara.inSpace": "Je bent in de space „{{name}}”.",
    "spaces.klara.artikelInSpace": "Dit artikel hoort bij de space „{{name}}”.",
    "spaces.klara.artikelOhneSpace": "Dit artikel hoort bij geen enkele space.",
    "spaces.klara.zweck": "Doel: {{zweck}}",
    "spaces.klara.zustaendig":
      "Verantwoordelijke van de space: {{name}} · Verantwoordelijkheid voor het artikel: {{verantwortung}}",
    "spaces.klara.zustaendigSpace": "Verantwoordelijke van de space: {{name}}",
    "spaces.klara.antwortGrenze":
      "Mijn antwoorden uit de kennisbank gebruiken alleen artikelen die je volgens space en niveau mag zien.",
  },
} satisfies Textmodul;
