// ================================================================================================
// ADMIN-06 · TEAMS — die Texte der Teamverwaltung (produkt:20261009:admin-teams).
// ================================================================================================
//
// Flächen: Verwaltung › Benutzer und Rollen › Teams (`pages/AdminTeams.tsx`). Die Sätze trennen
// ausdrücklich die drei Wege zu einem Space — globale Rolle, direkte Mitgliedschaft, Team — und
// sagen vor jeder Bestätigung, was sich für wen ändert.
//
// Die drei `audit.action.*`-Schlüssel sind Altnamen-Muster: `lib/auditAction.ts` leitet sie aus den
// Protokollvorgängen `team.angelegt`, `team.geaendert` und `team.archiviert` ab.
import type { Textmodul } from "./intern/pruefung";

export default {
  praefix: "teams.",
  legacySchluessel: [
    "audit.action.team_angelegt",
    "audit.action.team_geaendert",
    "audit.action.team_archiviert",
  ],
  de: {
    "audit.action.team_angelegt": "Team angelegt",
    "audit.action.team_geaendert": "Team geändert",
    "audit.action.team_archiviert": "Team archiviert",
    "teams.titel": "Teams",
    "teams.syn": "Gruppen Mitgliedschaften",
    "teams.wege.titel": "Drei Wege zu einem Space",
    "teams.wege.text":
      "Die globale Rolle gilt für das ganze Konto und öffnet keine geschlossenen Spaces. Eine direkte Mitgliedschaft gilt für genau einen Space. Ein Team bündelt Konten; jeder Space, der das Team bindet, gibt allen aktiven Mitgliedern dasselbe Recht. Entfernen aus einem Team nimmt nur, was dieses Team gewährt hat.",
    "teams.wege.kurz":
      "Ein Team ist ein Mitgliedschaftsweg auf bestehenden Konten — keine Kopie und keine Rolle.",
    "teams.laedt": "Teams werden geladen …",
    "teams.erneut": "Erneut versuchen",
    "teams.leer": "Es gibt noch kein Team.",
    "teams.liste.aktiv": "Aktive Teams",
    "teams.liste.archiv": "Archivierte Teams",
    "teams.liste.mitglieder": "Mitglieder: {{anzahl}}",
    "teams.liste.spaces": "Spaces: {{anzahl}}",
    "teams.status.aktiv": "Aktiv",
    "teams.status.archiviert": "Archiviert",
    "teams.anlegen.titel": "Team anlegen",
    "teams.anlegen.hinweis":
      "Ein neues Team ist an keinen Space gebunden. Die Bindung entsteht in der Spacepflege.",
    "teams.anlegen.speichern": "Team anlegen",
    "teams.abbrechen": "Abbrechen",
    "teams.feld.name": "Name",
    "teams.feld.zweck": "Zweck",
    "teams.feld.verantwortlich": "Teamzuständigkeit",
    "teams.feld.mitglieder": "Mitglieder",
    "teams.fehler.allgemein": "Das hat nicht geklappt. Bitte erneut versuchen.",
    "teams.fehler.ungueltig":
      "Bitte Name, Zweck und Zuständigkeit angeben; Mitglieder müssen bestehende Konten sein.",
    "teams.fehler.archiviert": "Dieses Team ist archiviert und nimmt keine Änderungen mehr auf.",
    "teams.fehler.veraltet": "Das Team wurde inzwischen geändert. Bitte neu laden.",
    "teams.fehler.vorschauVeraltet":
      "Die Rechtelage hat sich seit der Vorschau geändert. Bitte die neue Wirkung prüfen.",
    "teams.fehler.recht": "Teams verwaltet nur die Kontoverwaltung.",
    "teams.wirkung.titel": "Wirkung vor der Bestätigung",
    "teams.wirkung.titelArchiv": "Folgen des Archivierens",
    "teams.wirkung.keinSpace":
      "Dieses Team ist an keinen Space gebunden — die Änderung wirkt auf keinen Zugang.",
    "teams.wirkung.space":
      "{{name}} (Team-Recht: {{recht}}) — verlieren den Zugang ganz: {{anzahl}}",
    "teams.wirkung.aenderung.hinzu": "{{name}} kommt hinzu",
    "teams.wirkung.aenderung.entfernt": "{{name}} wird entfernt",
    "teams.wirkung.aenderung.archiviert": "{{name}} verliert diesen Teamweg",
    "teams.wirkung.rolle": "Globale Rolle: {{rolle}} — bleibt unverändert",
    "teams.wirkung.vorherNachher": "vorher {{vorher}} → nachher {{nachher}}",
    "teams.wirkung.wege": "Wege danach: {{wege}}",
    "teams.wirkung.archivBleibt":
      "Inhalte, Autorschaft, Fassungen und Prüfprotokoll bleiben unverändert. Ein archiviertes Team nimmt keine Mitglieder mehr auf und lässt sich nicht neu an einen Space binden.",
    "teams.wirkung.bestaetigen": "Änderung übernehmen",
    "teams.weg.zustaendig": "Spacezuständigkeit",
    "teams.weg.direkt": "direkte Mitgliedschaft ({{recht}})",
    "teams.weg.team": "Team „{{team}}“ ({{recht}})",
    "teams.weg.offen": "offener Space ({{recht}})",
    "teams.weg.keiner": "Danach kein Weg in diesen Space.",
    "teams.recht.zustaendig": "zuständig",
    "teams.recht.schreiben": "schreiben",
    "teams.recht.lesen": "lesen",
    "teams.recht.verwalten": "nur verwalten, kein Inhalt",
    "teams.recht.keins": "kein Zugang",
    "teams.fassung": "Fassung {{version}}",
    "teams.zustaendig": "Teamzuständigkeit: {{name}}",
    "teams.keineKopie":
      "Name, Rolle und Zugang der Mitglieder stehen am Konto; das Team verweist nur darauf.",
    "teams.spaces.titel": "Gebundene Spaces",
    "teams.spaces.keine": "Noch an keinen Space gebunden.",
    "teams.spaces.hinweis": "Ein Space bindet Teams in seiner Pflege unter „Teams“.",
    "teams.mitglieder.keine": "Noch keine Mitglieder.",
    "teams.mitglieder.entfernen": "Entfernen …",
    "teams.mitglieder.entfernenFuer": "{{name}} aus dem Team entfernen — Wirkung zuerst ansehen",
    "teams.mitglieder.waehlen": "Konto wählen",
    "teams.mitglieder.hinzu": "Hinzufügen …",
    "teams.bearbeiten.titel": "Name, Zweck und Zuständigkeit ändern",
    "teams.bearbeiten.speichern": "Speichern",
    "teams.archiv.titel": "Archivieren",
    "teams.archiv.hinweis":
      "Archivieren ersetzt das Löschen: die Geschichte bleibt, der Teamweg endet.",
    "teams.archiv.pruefen": "Folgen ansehen …",
    "teams.archiv.bestaetigen": "Team archivieren",
    "teams.archiv.keineMitglieder": "Archiviert — keine neuen Mitglieder, keine Änderungen.",
    "teams.verlauf.titel": "Verlauf",
    "teams.verlauf.angelegt": "Fassung {{version}} · {{zeit}} · angelegt von {{wer}}",
    "teams.verlauf.geaendert": "Fassung {{version}} · {{zeit}} · geändert von {{wer}}",
    "teams.verlauf.archiviert": "Fassung {{version}} · {{zeit}} · archiviert von {{wer}}",
    "teams.verlauf.hinzu": "hinzu: {{namen}}",
    "teams.verlauf.entfernt": "entfernt: {{namen}}",
  },
  en: {
    "audit.action.team_angelegt": "Team created",
    "audit.action.team_geaendert": "Team changed",
    "audit.action.team_archiviert": "Team archived",
    "teams.titel": "Teams",
    "teams.syn": "groups memberships",
    "teams.wege.titel": "Three ways into a space",
    "teams.wege.text":
      "The global role applies to the whole account and does not open closed spaces. A direct membership applies to exactly one space. A team bundles accounts; every space that binds the team gives all active members the same right. Removing someone from a team only takes away what this team granted.",
    "teams.wege.kurz":
      "A team is a membership path on existing accounts — not a copy and not a role.",
    "teams.laedt": "Loading teams …",
    "teams.erneut": "Try again",
    "teams.leer": "There is no team yet.",
    "teams.liste.aktiv": "Active teams",
    "teams.liste.archiv": "Archived teams",
    "teams.liste.mitglieder": "Members: {{anzahl}}",
    "teams.liste.spaces": "Spaces: {{anzahl}}",
    "teams.status.aktiv": "Active",
    "teams.status.archiviert": "Archived",
    "teams.anlegen.titel": "Create team",
    "teams.anlegen.hinweis":
      "A new team is not bound to any space. The binding is made when editing a space.",
    "teams.anlegen.speichern": "Create team",
    "teams.abbrechen": "Cancel",
    "teams.feld.name": "Name",
    "teams.feld.zweck": "Purpose",
    "teams.feld.verantwortlich": "Team owner",
    "teams.feld.mitglieder": "Members",
    "teams.fehler.allgemein": "That did not work. Please try again.",
    "teams.fehler.ungueltig":
      "Please enter name, purpose and owner; members must be existing accounts.",
    "teams.fehler.archiviert": "This team is archived and no longer accepts changes.",
    "teams.fehler.veraltet": "The team has changed in the meantime. Please reload.",
    "teams.fehler.vorschauVeraltet":
      "Access has changed since the preview. Please review the new effect.",
    "teams.fehler.recht": "Only account administration manages teams.",
    "teams.wirkung.titel": "Effect before confirming",
    "teams.wirkung.titelArchiv": "Consequences of archiving",
    "teams.wirkung.keinSpace":
      "This team is not bound to any space — the change affects no access.",
    "teams.wirkung.space": "{{name}} (team right: {{recht}}) — lose access entirely: {{anzahl}}",
    "teams.wirkung.aenderung.hinzu": "{{name}} is added",
    "teams.wirkung.aenderung.entfernt": "{{name}} is removed",
    "teams.wirkung.aenderung.archiviert": "{{name}} loses this team path",
    "teams.wirkung.rolle": "Global role: {{rolle}} — stays unchanged",
    "teams.wirkung.vorherNachher": "before {{vorher}} → after {{nachher}}",
    "teams.wirkung.wege": "Paths afterwards: {{wege}}",
    "teams.wirkung.archivBleibt":
      "Content, authorship, versions and audit trail stay unchanged. An archived team accepts no new members and cannot be bound to a space again.",
    "teams.wirkung.bestaetigen": "Apply change",
    "teams.weg.zustaendig": "space owner",
    "teams.weg.direkt": "direct membership ({{recht}})",
    "teams.weg.team": "team “{{team}}” ({{recht}})",
    "teams.weg.offen": "open space ({{recht}})",
    "teams.weg.keiner": "Afterwards no path into this space.",
    "teams.recht.zustaendig": "owner",
    "teams.recht.schreiben": "write",
    "teams.recht.lesen": "read",
    "teams.recht.verwalten": "manage only, no content",
    "teams.recht.keins": "no access",
    "teams.fassung": "Version {{version}}",
    "teams.zustaendig": "Team owner: {{name}}",
    "teams.keineKopie":
      "Name, role and access of the members stay with the account; the team only refers to it.",
    "teams.spaces.titel": "Bound spaces",
    "teams.spaces.keine": "Not bound to any space yet.",
    "teams.spaces.hinweis": "A space binds teams under “Teams” when it is edited.",
    "teams.mitglieder.keine": "No members yet.",
    "teams.mitglieder.entfernen": "Remove …",
    "teams.mitglieder.entfernenFuer": "Remove {{name}} from the team — review the effect first",
    "teams.mitglieder.waehlen": "Choose account",
    "teams.mitglieder.hinzu": "Add …",
    "teams.bearbeiten.titel": "Change name, purpose and owner",
    "teams.bearbeiten.speichern": "Save",
    "teams.archiv.titel": "Archive",
    "teams.archiv.hinweis": "Archiving replaces deletion: the history stays, the team path ends.",
    "teams.archiv.pruefen": "Review consequences …",
    "teams.archiv.bestaetigen": "Archive team",
    "teams.archiv.keineMitglieder": "Archived — no new members, no changes.",
    "teams.verlauf.titel": "History",
    "teams.verlauf.angelegt": "Version {{version}} · {{zeit}} · created by {{wer}}",
    "teams.verlauf.geaendert": "Version {{version}} · {{zeit}} · changed by {{wer}}",
    "teams.verlauf.archiviert": "Version {{version}} · {{zeit}} · archived by {{wer}}",
    "teams.verlauf.hinzu": "added: {{namen}}",
    "teams.verlauf.entfernt": "removed: {{namen}}",
  },
  nl: {
    "audit.action.team_angelegt": "Team aangemaakt",
    "audit.action.team_geaendert": "Team gewijzigd",
    "audit.action.team_archiviert": "Team gearchiveerd",
    "teams.titel": "Teams",
    "teams.syn": "groepen lidmaatschappen",
    "teams.wege.titel": "Drie wegen naar een space",
    "teams.wege.text":
      "De globale rol geldt voor het hele account en opent geen gesloten spaces. Een direct lidmaatschap geldt voor precies één space. Een team bundelt accounts; elke space die het team koppelt, geeft alle actieve leden hetzelfde recht. Verwijderen uit een team neemt alleen weg wat dit team heeft toegekend.",
    "teams.wege.kurz":
      "Een team is een lidmaatschapsweg op bestaande accounts — geen kopie en geen rol.",
    "teams.laedt": "Teams worden geladen …",
    "teams.erneut": "Opnieuw proberen",
    "teams.leer": "Er is nog geen team.",
    "teams.liste.aktiv": "Actieve teams",
    "teams.liste.archiv": "Gearchiveerde teams",
    "teams.liste.mitglieder": "Leden: {{anzahl}}",
    "teams.liste.spaces": "Spaces: {{anzahl}}",
    "teams.status.aktiv": "Actief",
    "teams.status.archiviert": "Gearchiveerd",
    "teams.anlegen.titel": "Team aanmaken",
    "teams.anlegen.hinweis":
      "Een nieuw team is aan geen enkele space gekoppeld. De koppeling ontstaat bij het bewerken van een space.",
    "teams.anlegen.speichern": "Team aanmaken",
    "teams.abbrechen": "Annuleren",
    "teams.feld.name": "Naam",
    "teams.feld.zweck": "Doel",
    "teams.feld.verantwortlich": "Teamverantwoordelijke",
    "teams.feld.mitglieder": "Leden",
    "teams.fehler.allgemein": "Dat is niet gelukt. Probeer het opnieuw.",
    "teams.fehler.ungueltig":
      "Vul naam, doel en verantwoordelijke in; leden moeten bestaande accounts zijn.",
    "teams.fehler.archiviert": "Dit team is gearchiveerd en neemt geen wijzigingen meer aan.",
    "teams.fehler.veraltet": "Het team is intussen gewijzigd. Laad opnieuw.",
    "teams.fehler.vorschauVeraltet":
      "De toegang is sinds de voorvertoning gewijzigd. Controleer het nieuwe effect.",
    "teams.fehler.recht": "Alleen het accountbeheer beheert teams.",
    "teams.wirkung.titel": "Effect vóór bevestiging",
    "teams.wirkung.titelArchiv": "Gevolgen van archiveren",
    "teams.wirkung.keinSpace":
      "Dit team is aan geen enkele space gekoppeld — de wijziging raakt geen toegang.",
    "teams.wirkung.space":
      "{{name}} (teamrecht: {{recht}}) — verliezen de toegang helemaal: {{anzahl}}",
    "teams.wirkung.aenderung.hinzu": "{{name}} komt erbij",
    "teams.wirkung.aenderung.entfernt": "{{name}} wordt verwijderd",
    "teams.wirkung.aenderung.archiviert": "{{name}} verliest deze teamweg",
    "teams.wirkung.rolle": "Globale rol: {{rolle}} — blijft ongewijzigd",
    "teams.wirkung.vorherNachher": "vooraf {{vorher}} → daarna {{nachher}}",
    "teams.wirkung.wege": "Wegen daarna: {{wege}}",
    "teams.wirkung.archivBleibt":
      "Inhoud, auteurschap, versies en auditlog blijven ongewijzigd. Een gearchiveerd team neemt geen leden meer aan en kan niet opnieuw aan een space worden gekoppeld.",
    "teams.wirkung.bestaetigen": "Wijziging toepassen",
    "teams.weg.zustaendig": "spaceverantwoordelijke",
    "teams.weg.direkt": "direct lidmaatschap ({{recht}})",
    "teams.weg.team": "team „{{team}}” ({{recht}})",
    "teams.weg.offen": "open space ({{recht}})",
    "teams.weg.keiner": "Daarna geen weg naar deze space.",
    "teams.recht.zustaendig": "verantwoordelijk",
    "teams.recht.schreiben": "schrijven",
    "teams.recht.lesen": "lezen",
    "teams.recht.verwalten": "alleen beheren, geen inhoud",
    "teams.recht.keins": "geen toegang",
    "teams.fassung": "Versie {{version}}",
    "teams.zustaendig": "Teamverantwoordelijke: {{name}}",
    "teams.keineKopie":
      "Naam, rol en toegang van de leden staan bij het account; het team verwijst er alleen naar.",
    "teams.spaces.titel": "Gekoppelde spaces",
    "teams.spaces.keine": "Nog aan geen enkele space gekoppeld.",
    "teams.spaces.hinweis": "Een space koppelt teams bij het bewerken onder „Teams”.",
    "teams.mitglieder.keine": "Nog geen leden.",
    "teams.mitglieder.entfernen": "Verwijderen …",
    "teams.mitglieder.entfernenFuer":
      "{{name}} uit het team verwijderen — eerst het effect bekijken",
    "teams.mitglieder.waehlen": "Account kiezen",
    "teams.mitglieder.hinzu": "Toevoegen …",
    "teams.bearbeiten.titel": "Naam, doel en verantwoordelijke wijzigen",
    "teams.bearbeiten.speichern": "Opslaan",
    "teams.archiv.titel": "Archiveren",
    "teams.archiv.hinweis":
      "Archiveren vervangt verwijderen: de geschiedenis blijft, de teamweg eindigt.",
    "teams.archiv.pruefen": "Gevolgen bekijken …",
    "teams.archiv.bestaetigen": "Team archiveren",
    "teams.archiv.keineMitglieder": "Gearchiveerd — geen nieuwe leden, geen wijzigingen.",
    "teams.verlauf.titel": "Geschiedenis",
    "teams.verlauf.angelegt": "Versie {{version}} · {{zeit}} · aangemaakt door {{wer}}",
    "teams.verlauf.geaendert": "Versie {{version}} · {{zeit}} · gewijzigd door {{wer}}",
    "teams.verlauf.archiviert": "Versie {{version}} · {{zeit}} · gearchiveerd door {{wer}}",
    "teams.verlauf.hinzu": "toegevoegd: {{namen}}",
    "teams.verlauf.entfernt": "verwijderd: {{namen}}",
  },
} satisfies Textmodul;
