// ================================================================================================
// HAUPTVERANTWORTUNG ÜBERGEBEN — die Texte des Übergabebereichs in der Kontokarte.
// ================================================================================================
//
// Auftrag `produkt:20261007:ownership-uebergabe`. DE/EN/NL, weil der Textmodulvertrag jede Sprache
// der Oberfläche verlangt (docs/i18n-textmodule.md).
import type { Textmodul } from "./intern/pruefung";

export default {
  praefix: "uebergabe.",
  legacySchluessel: [],
  de: {
    "uebergabe.titel": "Hauptverantwortung für Beiträge",
    "uebergabe.oeffnen": "Beiträge übergeben",
    "uebergabe.einklappen": "Einklappen",
    "uebergabe.laedt": "Bestand wird geladen …",
    "uebergabe.ladefehler": "Der Bestand konnte nicht geladen werden.",
    "uebergabe.leer": "{{name}} ist für keinen Beitrag hauptverantwortlich.",
    "uebergabe.anzahl": "{{name}} ist für {{anzahl}} Beiträge hauptverantwortlich.",
    "uebergabe.nichtEinsehbar":
      "Davon darfst du {{anzahl}} nicht lesen — sie erscheinen nur mit Space und Status.",
    "uebergabe.zugang.aktiv": "Zugang aktiv",
    "uebergabe.zugang.befristet": "Zugang befristet — endet von selbst",
    "uebergabe.keinGemeinsamesZiel":
      "Für diese Beiträge gibt es keinen gemeinsam zulässigen Nachfolger. Bitte kleinere Pakete bilden.",
    "uebergabe.papierkorb": "im Papierkorb",
    "uebergabe.zugang.abgelaufen": "Zugang beendet",
    "uebergabe.zugang.gesperrt": "Konto nicht freigegeben",
    "uebergabe.zugang.geloescht": "Konto gelöscht",
    "uebergabe.vertretung":
      "Bei kurzfristiger Sperrung bleiben die Beiträge bei dieser Person. Vertretung nach dem Rollenmodell — prüfen, freigeben und Verantwortung neu benennen: {{namen}}.",
    "uebergabe.vertretungNiemand":
      "Bei kurzfristiger Sperrung bleiben die Beiträge bei dieser Person. Derzeit hat kein anderes aktives Konto die Rolle Controller oder Admin, die vertreten könnte.",
    "uebergabe.verborgen": "Nicht einsehbarer Beitrag",
    "uebergabe.autor": "Autor: {{name}}",
    "uebergabe.ursprung": "Ursprünglich: {{name}}",
    "uebergabe.unbekannt": "unbekannt",
    "uebergabe.ersatz": "Verantwortung bisher über die Autorschaft",
    "uebergabe.mitwirkende": "{{anzahl}} Mitwirkende",
    "uebergabe.zugeteilt": "geht an {{name}}",
    "uebergabe.loesen": "Zuteilung lösen",
    "uebergabe.ziel": "Nachfolger",
    "uebergabe.zielWaehlen": "Nachfolger wählen …",
    "uebergabe.keinZiel": "Es gibt kein aktives Konto mit Bearbeitungsrecht als Nachfolger.",
    "uebergabe.auswahlZuteilen": "Auswahl zuteilen ({{anzahl}})",
    "uebergabe.restZuteilen": "Alle übrigen zuteilen",
    "uebergabe.planLeer":
      "Beiträge anhaken, Nachfolger wählen und zuteilen. Für weitere Nachfolger wiederholen — so entstehen Pakete.",
    "uebergabe.vorschau": "Vorschau",
    "uebergabe.verwerfen": "Zuteilung verwerfen",
    "uebergabe.vorschauTitel": "Vorschau — noch ist nichts geändert",
    "uebergabe.gruppe": "{{name}}: {{anzahl}} Beiträge",
    "uebergabe.abgelehnt": "Nicht übertragbar: {{anzahl}}",
    "uebergabe.bleibt":
      "Unverändert bleiben Autorschaft, Mitwirkung, Freigabestatus, Fassung und Zugriffsrechte.",
    "uebergabe.verbleibt": "Danach noch bei {{name}}: {{anzahl}} Beiträge.",
    "uebergabe.ausfuehren": "Übergabe ausführen",
    "uebergabe.ergebnisVoll": "Übergabe vollständig: {{anzahl}} Beiträge übertragen.",
    "uebergabe.ergebnisTeil":
      "Übergabe unvollständig: {{uebertragen}} übertragen, {{offen}} offen. Die offenen Beiträge sind unverändert.",
    "uebergabe.bereitsErledigt": "{{anzahl}} waren bereits übertragen.",
    "uebergabe.erneut": "Offene erneut übertragen",
    "uebergabe.deaktivieren": "Übergeben und Zugang beenden",
    "uebergabe.deaktivierenHinweis":
      "Der Zugang endet nur, wenn danach kein Beitrag mehr bei dieser Person liegt. Wieder öffnen lässt er sich über die Befristung dieses Kontos.",
    "uebergabe.deaktiviert": "Zugang beendet — bei dieser Person liegt kein Beitrag mehr.",
    "uebergabe.bereitsInaktiv": "Der Zugang war bereits beendet; es liegt kein Beitrag mehr hier.",
    "uebergabe.fehler": "Der Vorgang ist gescheitert: {{meldung}}",
    "uebergabe.andere": "Weitere Bestände ohne aktive Hauptverantwortung",
    "uebergabe.andereZeile": "{{name}} · {{zugang}} · {{anzahl}} Beiträge",
    "uebergabe.andereWaehlen": "Diesen Bestand übergeben",
    "uebergabe.zurueckZurPerson": "Zurück zu {{name}}",
    "uebergabe.geloeschtesKonto": "Gelöschtes Konto",
  },
  en: {
    "uebergabe.titel": "Main responsibility for contributions",
    "uebergabe.oeffnen": "Hand over contributions",
    "uebergabe.einklappen": "Collapse",
    "uebergabe.laedt": "Loading contributions …",
    "uebergabe.ladefehler": "The contributions could not be loaded.",
    "uebergabe.leer": "{{name}} is not mainly responsible for any contribution.",
    "uebergabe.anzahl": "{{name}} is mainly responsible for {{anzahl}} contributions.",
    "uebergabe.nichtEinsehbar":
      "You may not read {{anzahl}} of them — they appear only with space and status.",
    "uebergabe.zugang.aktiv": "Access active",
    "uebergabe.zugang.befristet": "Access time-limited — ends by itself",
    "uebergabe.keinGemeinsamesZiel":
      "There is no successor permitted for all of these contributions. Please form smaller packages.",
    "uebergabe.papierkorb": "in the recycle bin",
    "uebergabe.zugang.abgelaufen": "Access ended",
    "uebergabe.zugang.gesperrt": "Account not approved",
    "uebergabe.zugang.geloescht": "Account deleted",
    "uebergabe.vertretung":
      "During a short-term lock the contributions stay with this person. Deputies under the role model — review, approve and name a new owner: {{namen}}.",
    "uebergabe.vertretungNiemand":
      "During a short-term lock the contributions stay with this person. No other active account currently has the controller or admin role to deputise.",
    "uebergabe.verborgen": "Contribution you may not read",
    "uebergabe.autor": "Author: {{name}}",
    "uebergabe.ursprung": "Originally: {{name}}",
    "uebergabe.unbekannt": "unknown",
    "uebergabe.ersatz": "Responsibility so far via authorship",
    "uebergabe.mitwirkende": "{{anzahl}} contributors",
    "uebergabe.zugeteilt": "goes to {{name}}",
    "uebergabe.loesen": "Remove assignment",
    "uebergabe.ziel": "Successor",
    "uebergabe.zielWaehlen": "Choose successor …",
    "uebergabe.keinZiel": "There is no active account with editing rights to take over.",
    "uebergabe.auswahlZuteilen": "Assign selection ({{anzahl}})",
    "uebergabe.restZuteilen": "Assign all remaining",
    "uebergabe.planLeer":
      "Tick contributions, choose a successor and assign. Repeat for further successors — this creates packages.",
    "uebergabe.vorschau": "Preview",
    "uebergabe.verwerfen": "Discard assignment",
    "uebergabe.vorschauTitel": "Preview — nothing has changed yet",
    "uebergabe.gruppe": "{{name}}: {{anzahl}} contributions",
    "uebergabe.abgelehnt": "Cannot be handed over: {{anzahl}}",
    "uebergabe.bleibt":
      "Authorship, contributors, approval status, version and access rights stay unchanged.",
    "uebergabe.verbleibt": "Still with {{name}} afterwards: {{anzahl}} contributions.",
    "uebergabe.ausfuehren": "Carry out handover",
    "uebergabe.ergebnisVoll": "Handover complete: {{anzahl}} contributions handed over.",
    "uebergabe.ergebnisTeil":
      "Handover incomplete: {{uebertragen}} handed over, {{offen}} open. The open contributions are unchanged.",
    "uebergabe.bereitsErledigt": "{{anzahl}} had already been handed over.",
    "uebergabe.erneut": "Retry open contributions",
    "uebergabe.deaktivieren": "Hand over and end access",
    "uebergabe.deaktivierenHinweis":
      "Access only ends if no contribution remains with this person afterwards. It can be reopened through this account's time limit.",
    "uebergabe.deaktiviert": "Access ended — no contribution remains with this person.",
    "uebergabe.bereitsInaktiv": "Access had already ended; no contribution remains here.",
    "uebergabe.fehler": "The action failed: {{meldung}}",
    "uebergabe.andere": "Other holdings without active main responsibility",
    "uebergabe.andereZeile": "{{name}} · {{zugang}} · {{anzahl}} contributions",
    "uebergabe.andereWaehlen": "Hand over these contributions",
    "uebergabe.zurueckZurPerson": "Back to {{name}}",
    "uebergabe.geloeschtesKonto": "Deleted account",
  },
  nl: {
    "uebergabe.titel": "Hoofdverantwoordelijkheid voor bijdragen",
    "uebergabe.oeffnen": "Bijdragen overdragen",
    "uebergabe.einklappen": "Inklappen",
    "uebergabe.laedt": "Bijdragen worden geladen …",
    "uebergabe.ladefehler": "De bijdragen konden niet worden geladen.",
    "uebergabe.leer": "{{name}} is voor geen enkele bijdrage hoofdverantwoordelijk.",
    "uebergabe.anzahl": "{{name}} is hoofdverantwoordelijk voor {{anzahl}} bijdragen.",
    "uebergabe.nichtEinsehbar":
      "{{anzahl}} daarvan mag je niet lezen — die verschijnen alleen met space en status.",
    "uebergabe.zugang.aktiv": "Toegang actief",
    "uebergabe.zugang.befristet": "Toegang tijdelijk — eindigt vanzelf",
    "uebergabe.keinGemeinsamesZiel":
      "Er is geen opvolger die voor al deze bijdragen is toegestaan. Vorm kleinere pakketten.",
    "uebergabe.papierkorb": "in de prullenbak",
    "uebergabe.zugang.abgelaufen": "Toegang beëindigd",
    "uebergabe.zugang.gesperrt": "Account niet vrijgegeven",
    "uebergabe.zugang.geloescht": "Account verwijderd",
    "uebergabe.vertretung":
      "Bij een kortstondige blokkering blijven de bijdragen bij deze persoon. Vervanging volgens het rollenmodel — controleren, vrijgeven en een nieuwe verantwoordelijke aanwijzen: {{namen}}.",
    "uebergabe.vertretungNiemand":
      "Bij een kortstondige blokkering blijven de bijdragen bij deze persoon. Momenteel heeft geen ander actief account de rol controller of beheerder om te vervangen.",
    "uebergabe.verborgen": "Bijdrage die je niet mag lezen",
    "uebergabe.autor": "Auteur: {{name}}",
    "uebergabe.ursprung": "Oorspronkelijk: {{name}}",
    "uebergabe.unbekannt": "onbekend",
    "uebergabe.ersatz": "Verantwoordelijkheid tot nu toe via het auteurschap",
    "uebergabe.mitwirkende": "{{anzahl}} medewerkers",
    "uebergabe.zugeteilt": "gaat naar {{name}}",
    "uebergabe.loesen": "Toewijzing opheffen",
    "uebergabe.ziel": "Opvolger",
    "uebergabe.zielWaehlen": "Opvolger kiezen …",
    "uebergabe.keinZiel": "Er is geen actief account met bewerkingsrechten als opvolger.",
    "uebergabe.auswahlZuteilen": "Selectie toewijzen ({{anzahl}})",
    "uebergabe.restZuteilen": "Alle overige toewijzen",
    "uebergabe.planLeer":
      "Vink bijdragen aan, kies een opvolger en wijs toe. Herhaal voor verdere opvolgers — zo ontstaan pakketten.",
    "uebergabe.vorschau": "Voorbeeld",
    "uebergabe.verwerfen": "Toewijzing verwerpen",
    "uebergabe.vorschauTitel": "Voorbeeld — er is nog niets gewijzigd",
    "uebergabe.gruppe": "{{name}}: {{anzahl}} bijdragen",
    "uebergabe.abgelehnt": "Niet over te dragen: {{anzahl}}",
    "uebergabe.bleibt":
      "Auteurschap, medewerking, vrijgavestatus, versie en toegangsrechten blijven ongewijzigd.",
    "uebergabe.verbleibt": "Daarna nog bij {{name}}: {{anzahl}} bijdragen.",
    "uebergabe.ausfuehren": "Overdracht uitvoeren",
    "uebergabe.ergebnisVoll": "Overdracht volledig: {{anzahl}} bijdragen overgedragen.",
    "uebergabe.ergebnisTeil":
      "Overdracht onvolledig: {{uebertragen}} overgedragen, {{offen}} open. De open bijdragen zijn ongewijzigd.",
    "uebergabe.bereitsErledigt": "{{anzahl}} waren al overgedragen.",
    "uebergabe.erneut": "Open bijdragen opnieuw overdragen",
    "uebergabe.deaktivieren": "Overdragen en toegang beëindigen",
    "uebergabe.deaktivierenHinweis":
      "De toegang eindigt alleen als daarna geen bijdrage meer bij deze persoon ligt. Heropenen kan via de tijdslimiet van dit account.",
    "uebergabe.deaktiviert": "Toegang beëindigd — er ligt geen bijdrage meer bij deze persoon.",
    "uebergabe.bereitsInaktiv": "De toegang was al beëindigd; er ligt hier geen bijdrage meer.",
    "uebergabe.fehler": "De actie is mislukt: {{meldung}}",
    "uebergabe.andere": "Andere bestanden zonder actieve hoofdverantwoordelijkheid",
    "uebergabe.andereZeile": "{{name}} · {{zugang}} · {{anzahl}} bijdragen",
    "uebergabe.andereWaehlen": "Deze bijdragen overdragen",
    "uebergabe.zurueckZurPerson": "Terug naar {{name}}",
    "uebergabe.geloeschtesKonto": "Verwijderd account",
  },
} satisfies Textmodul;
