// ================================================================================================
// VORLAGEN — die Texte für Vorlagenwahl, Vorlagenseite, Space-Vorgaben, Begriffspflege und Klara
// (produkt:20261007:templates-default · ADMIN-08).
// ================================================================================================
//
// Flächen: Vorlagenwahl im Erfassen-Editor (`components/VorlagenWahl.tsx`), die Seite `/vorlagen`
// (`pages/Vorlagen.tsx`), die Herkunftszeile am Beitrag (`components/VorlagenHerkunft.tsx`) und
// Klaras Vorlagenkontext. Die Sätze sagen vor jeder Übernahme, was mit eingegebenen Werten geschieht,
// und erklären die Vorrangregel: verbindlich im Space → persönlicher Standard → freie Eingabe.
//
// Die `audit.action.*`-Schlüssel sind Altnamen-Muster: `lib/auditAction.ts` leitet sie aus den
// Protokollvorgängen dieser Funktion ab.
import type { Textmodul } from "./intern/pruefung";

export default {
  praefix: "vorlagen.",
  legacySchluessel: [
    "audit.action.vorlage_angelegt",
    "audit.action.vorlage_geaendert",
    "audit.action.vorlage_geteilt",
    "audit.action.vorlage_ausgemustert",
    "audit.action.vorlage_standard_gesetzt",
    "audit.action.vorlage_verwendet",
    "audit.action.space_vorgaben_geaendert",
    "audit.action.begriff_umbenennen",
    "audit.action.begriff_zusammenfuehren",
    "audit.action.begriff_ausmustern",
  ],
  de: {
    "audit.action.vorlage_angelegt": "Vorlage angelegt",
    "audit.action.vorlage_geaendert": "Vorlage geändert (neue Fassung)",
    "audit.action.vorlage_geteilt": "Vorlage geteilt",
    "audit.action.vorlage_ausgemustert": "Vorlage ausgemustert",
    "audit.action.vorlage_standard_gesetzt": "Persönlicher Vorlagenstandard gesetzt",
    "audit.action.vorlage_verwendet": "Mit Vorlage eingereicht",
    "audit.action.space_vorgaben_geaendert": "Space-Vorgaben geändert",
    "audit.action.begriff_umbenennen": "Begriff umbenannt",
    "audit.action.begriff_zusammenfuehren": "Begriffe zusammengeführt",
    "audit.action.begriff_ausmustern": "Begriff ausgemustert",
    "vorlagen.ziel": "Vorlagen, Kategorien und Tags",
    "vorlagen.seite.kicker": "Wissen ordnen",
    "vorlagen.seite.titel": "Vorlagen",
    "vorlagen.seite.lead":
      "Eigene Vorlagen anlegen, im Space oder unternehmensweit teilen, den persönlichen Standard wählen und Space-Vorgaben pflegen.",
    "vorlagen.laedt": "Vorlagen werden geladen …",
    "vorlagen.laden.fehler":
      "Die Vorlagen konnten nicht geladen werden. Freie Eingabe ist weiter möglich.",
    "vorlagen.neu": "Neue Vorlage",
    "vorlagen.liste.titel": "Verfügbare Vorlagen",
    "vorlagen.abbrechen": "Abbrechen",
    "vorlagen.bearbeiten": "Bearbeiten",
    "vorlagen.kopieren": "Als eigene Vorlage kopieren",
    "vorlagen.verlauf": "Fassungen",
    "vorlagen.begruendung": "Begründung",
    "vorlagen.fassung": "Fassung {{version}}",
    "vorlagen.istStandard": "Ihr Standard",
    "vorlagen.ausgemustert": "ausgemustert",
    "vorlagen.ohneSpace": "ohne Space",
    "vorlagen.pflicht.marke": "Pflicht",
    "vorlagen.pflicht.erklaerung":
      "Pflichtfelder werden beim Einreichen geprüft. Einen unvollständigen Entwurf können Sie jederzeit speichern.",
    "vorlagen.geltung.standard": "Standard",
    "vorlagen.geltung.unternehmen": "Unternehmensweit",
    "vorlagen.geltung.space": "Im Space",
    "vorlagen.geltung.persoenlich": "Persönlich",
    "vorlagen.geltung.erklaerung.persoenlich": "Nur Sie sehen und nutzen diese Vorlage.",
    "vorlagen.geltung.erklaerung.space":
      "Alle, die den Space lesen, nutzen die Vorlage. Ändern dürfen Sie (mit Schreibrecht) und die Spacezuständigen.",
    "vorlagen.geltung.erklaerung.unternehmen":
      "Alle nutzen die Vorlage. Ändern darf nur die Kontoverwaltung.",
    "vorlagen.einschraenkung.unternehmen":
      "Unternehmensweite Struktur: ändern darf sie nur die Kontoverwaltung; jede Änderung wird eine neue Fassung.",
    "vorlagen.einschraenkung.standard":
      "Standardvorlage: unveränderlich. Zum Anpassen als eigene Vorlage kopieren.",
    "vorlagen.art.absatz": "Absatz",
    "vorlagen.art.liste": "Liste",
    "vorlagen.art.schritte": "Schritte",
    "vorlagen.art.hinweis": "Hinweis",
    "vorlagen.art.warnung": "Warnung",
    "vorlagen.vorgang.angelegt": "angelegt",
    "vorlagen.vorgang.geaendert": "geändert",
    "vorlagen.vorgang.geteilt": "geteilt",
    "vorlagen.vorgang.ausgemustert": "ausgemustert",
    "vorlagen.wahl.titel": "Vorlage",
    "vorlagen.wahl.verwalten": "Vorlagen verwalten",
    "vorlagen.wahl.hinweis":
      "Wählen Sie eine Struktur. Nichts wird ohne Klick eingesetzt, eingegebene Werte gehen nicht verloren.",
    "vorlagen.wahl.space": "Für Space:",
    "vorlagen.wahl.ohneSpace": "— kein Space —",
    "vorlagen.zeile.mit": "Vorlage: „{{name}}“ (Fassung {{version}}).",
    "vorlagen.zeile.waehlen": "Vorlage wählen",
    "vorlagen.zeile.aendern": "Andere Vorlage oder freie Eingabe",
    "vorlagen.zeile.schliessen": "Einklappen",
    "vorlagen.frei.knopf": "Freie Eingabe",
    "vorlagen.frei.hinweis":
      "Freie Eingabe: ohne Vorlage. Ihr Text bleibt unverändert; Sie können jederzeit wieder eine Vorlage wählen.",
    "vorlagen.frei.ohneSpace":
      "Ohne Vorlage wird der Beitrag keinem Space zugeordnet; das geht danach über den Spacewechsel.",
    "vorlagen.vorrang.space":
      "Im Space „{{space}}“ ist „{{name}}“ verbindlich und hat Vorrang vor Ihrem Standard.",
    "vorlagen.vorrang.persoenlich": "Vorgewählt: Ihr Standard „{{name}}“.",
    "vorlagen.vorrang.frei": "Kein Standard gewählt — freie Eingabe.",
    "vorlagen.vorrang.ersatz.ausgemustert":
      "Ihr Standard „{{name}}“ ist ausgemustert. Es gilt freie Eingabe; bitte einen neuen Standard wählen.",
    "vorlagen.vorrang.ersatz.nicht_verfuegbar":
      "Ihr Standard „{{name}}“ ist nicht mehr verfügbar. Es gilt freie Eingabe; bitte einen neuen Standard wählen.",
    "vorlagen.vorrang.verdraengt": "(Ihr Standard „{{name}}“ tritt hier zurück.)",
    "vorlagen.vorrang.regel":
      "Vorrang bei neuer Eingabe: eine im gewählten Space verbindliche Vorlage, sonst Ihr Standard, sonst freie Eingabe. Ist Ihr Standard nicht mehr verfügbar, steht das mit Grund da — Inhalte werden nie entfernt.",
    "vorlagen.standard.titel": "Mein Standard",
    "vorlagen.standard.ist": "Ihr Standard: „{{name}}“.",
    "vorlagen.standard.keiner": "Kein Standard — neue Eingaben beginnen frei.",
    "vorlagen.standard.nichtVerfuegbar":
      "Ihr Standard ist nicht mehr verfügbar; neue Eingaben beginnen frei. Bitte einen neuen wählen.",
    "vorlagen.standard.setzen": "Als meinen Standard",
    "vorlagen.standard.aufheben": "Standard aufheben",
    "vorlagen.anwenden.setzen": "Vorlage einsetzen",
    "vorlagen.anwenden.anfuegen": "Unter dem Text anfügen",
    "vorlagen.anwenden.wechseln": "Vorlage wechseln",
    "vorlagen.wechsel.weitere": "Weitere Inhalte (aus der bisherigen Struktur)",
    "vorlagen.wechsel.schon": "Diese Vorlage und Fassung ist bereits angewendet.",
    "vorlagen.wechsel.vorschau": "Vorschau des Ergebnisses",
    "vorlagen.wechsel.setzen": "Der leere Inhalt bekommt die Struktur dieser Vorlage.",
    "vorlagen.wechsel.angefuegt":
      "Ihr Text bleibt oben unverändert; die Struktur wird darunter angefügt.",
    "vorlagen.wechsel.angefuegtErledigt":
      "Struktur unter Ihrem Text angefügt. Nichts wurde entfernt.",
    "vorlagen.wechsel.plan": "Beim Wechsel:",
    "vorlagen.wechsel.erledigt": "Gewechselt:",
    "vorlagen.wechsel.uebernommen": "übernommen in {{liste}}.",
    "vorlagen.wechsel.nichtsUebernommen": "kein Abschnitt passt direkt.",
    "vorlagen.wechsel.verschoben":
      "Unverändert ans Ende unter „Weitere Inhalte“ gestellt: {{liste}}.",
    "vorlagen.wechsel.leer": "Nur leere Hinweise entfallen: {{liste}}.",
    "vorlagen.vorgabe.titel": "Vorgaben im Space „{{space}}“",
    "vorlagen.vorgabe.verbindlich":
      "Verbindliche Vorlage: „{{name}}“ — ihre Pflichtfelder gelten auch bei freier Eingabe.",
    "vorlagen.vorgabe.verbindlichFehlt":
      "Die verbindliche Vorlage ist nicht mehr verfügbar; ihre Pflichtfelder gelten nicht.",
    "vorlagen.vorgabe.kategorien": "Kategorie: eine von {{liste}}.",
    "vorlagen.vorgabe.pflichtKategorie": "Eine Kategorie ist anzugeben.",
    "vorlagen.vorgabe.tags": "Mindestens {{anzahl}} Tag(s).",
    "vorlagen.vorgabe.vorschlag": "Vorgeschlagene Tags: {{liste}}.",
    "vorlagen.vorgabe.wann":
      "Geprüft wird beim Einreichen; Speichern geht immer. Der Beitrag wird in diesem Space abgelegt.",
    "vorlagen.pruefen.knopf": "Pflichtangaben prüfen",
    "vorlagen.pruefen.ok": "Alle Pflichtangaben sind erfüllt.",
    "vorlagen.befund.vorlagenfeld": "Das Pflichtfeld „{{wert}}“ ist noch leer.",
    "vorlagen.befund.kategorie_fehlt": "Bitte eine Kategorie angeben.",
    "vorlagen.befund.kategorie_nicht_erlaubt":
      "Die Kategorie „{{wert}}“ ist in diesem Space nicht vorgesehen.",
    "vorlagen.befund.tags_fehlen": "Bitte mindestens {{wert}} Tag(s) angeben.",
    "vorlagen.befund.begriff_ersetzt":
      "„{{wert}}“ wurde umbenannt oder zusammengeführt — bitte den neuen Begriff verwenden.",
    "vorlagen.befund.begriff_ausgemustert":
      "„{{wert}}“ ist ausgemustert und wird für neue Beiträge nicht mehr verwendet.",
    "vorlagen.feld.name": "Name",
    "vorlagen.feld.geltung": "Geltung",
    "vorlagen.feld.space": "Space",
    "vorlagen.feld.beschreibung": "Beschreibung",
    "vorlagen.feld.felder": "Felder (Reihenfolge = Reihenfolge im Beitrag)",
    "vorlagen.feld.titel": "Titel von Feld {{nummer}}",
    "vorlagen.feld.hinweis": "Hinweis zu Feld {{nummer}}",
    "vorlagen.feld.art": "Art von Feld {{nummer}}",
    "vorlagen.feld.hoch": "Feld {{nummer}} nach oben",
    "vorlagen.feld.runter": "Feld {{nummer}} nach unten",
    "vorlagen.feld.entfernen": "Feld {{nummer}} entfernen",
    "vorlagen.feld.neu": "Feld hinzufügen",
    "vorlagen.formular.anlegen": "Vorlage anlegen",
    "vorlagen.formular.auswirkungen": "Auswirkungen prüfen",
    "vorlagen.formular.neueFassung": "Neue Fassung speichern",
    "vorlagen.wirkung.titel": "Auswirkungen dieser Änderung",
    "vorlagen.wirkung.neu": "Neue Felder: {{liste}}.",
    "vorlagen.wirkung.entfernt": "Entfernte Felder: {{liste}}.",
    "vorlagen.wirkung.umbenannt": "„{{vorher}}“ heisst jetzt „{{nachher}}“.",
    "vorlagen.wirkung.pflichtNeu": "Neu verpflichtend: {{liste}}.",
    "vorlagen.wirkung.pflichtEntfallen": "Nicht mehr verpflichtend: {{liste}}.",
    "vorlagen.wirkung.geltung": "Geltung: {{vorher}} → {{nachher}}.",
    "vorlagen.wirkung.nutzung": "Bestehende Beiträge mit dieser Vorlage: {{anzahl}} {{fassungen}}",
    "vorlagen.wirkung.jeFassung": "Fassung {{version}}: {{anzahl}}",
    "vorlagen.wirkung.jeSpace": "Je Space: {{liste}}.",
    "vorlagen.wirkung.standardBei": "Als persönlicher Standard gewählt: {{anzahl}}.",
    "vorlagen.wirkung.verbindlichIn": "Verbindlich in: {{liste}}.",
    "vorlagen.wirkung.bestand":
      "Bestehende Beiträge behalten ihre Werte und den Bezug auf die Fassung, mit der sie entstanden sind. Neue Pflichtfelder gelten nur für neue Einreichungen; alte Artikel werden nicht umformatiert.",
    "vorlagen.ausmustern.knopf": "Ausmustern",
    "vorlagen.ausmustern.erklaerung":
      "Ausgemustert wird die Vorlage nicht mehr angeboten. Bestehende Beiträge behalten Werte und Fassungsbezug; wer sie als Standard hatte, beginnt mit freier Eingabe und sieht den Grund.",
    "vorlagen.vorgaben.titel": "Space-Vorgaben",
    "vorlagen.vorgaben.erklaerung":
      "Was eine Eingabe für diesen Space mitbringen muss. Gilt für alle, die in diesem Space schreiben, und hat Vorrang vor persönlichen Standards.",
    "vorlagen.vorgaben.verbindlich": "Verbindliche Vorlage",
    "vorlagen.vorgaben.keine": "— keine —",
    "vorlagen.vorgaben.kategorien": "Erlaubte Kategorien (mit Komma getrennt, leer = alle)",
    "vorlagen.vorgaben.pflichtKategorie": "Kategorie ist Pflicht",
    "vorlagen.vorgaben.mindestensTags": "Mindestzahl an Tags (0–5)",
    "vorlagen.vorgaben.tags": "Vorgeschlagene Tags (mit Komma getrennt)",
    "vorlagen.vorgaben.hinweis": "Erklärung für Schreibende",
    "vorlagen.vorgaben.wirkung":
      "Die Vorgaben gelten nur in diesem Space und erst für neue Einreichungen; andere Spaces und bestehende Beiträge bleiben unverändert.",
    "vorlagen.vorgaben.speichern": "Vorgaben speichern",
    "vorlagen.vorgaben.gespeichert": "Vorgaben gespeichert — als neue Fassung.",
    "vorlagen.vorgaben.verlauf": "{{anzahl}} Fassung(en), zuletzt {{am}}.",
    "vorlagen.verwaltung.titel": "Geltung und Nutzungsumfang",
    "vorlagen.verwaltung.erklaerung":
      "Geteilte Vorlagen, Kategorien und Tags mit ihrer Nutzung je Space. Persönliche Vorlagen erscheinen nur als Zahl.",
    "vorlagen.verwaltung.nutzung": "Beiträge (je Fassung · je Space)",
    "vorlagen.verwaltung.standardBei": "Standard bei",
    "vorlagen.verwaltung.verbindlichIn": "Verbindlich in",
    "vorlagen.verwaltung.persoenlich":
      "Persönliche Vorlagen: {{vorlagen}}, damit eingereichte Beiträge: {{beitraege}}.",
    "vorlagen.verwaltung.kategorien": "Kategorien",
    "vorlagen.verwaltung.tags": "Tags",
    "vorlagen.verwaltung.vorgegebenIn": "vorgegeben in {{liste}}",
    "vorlagen.verwaltung.nichtEinsehbar":
      "{{anzahl}} Beiträge sind für Sie nicht einsehbar und hier nicht nach Begriffen aufgeschlüsselt.",
    "vorlagen.begriffe.titel": "Kategorie oder Tag pflegen",
    "vorlagen.begriffe.art": "Art",
    "vorlagen.begriffe.tag": "Tag",
    "vorlagen.begriffe.kategorie": "Kategorie",
    "vorlagen.begriffe.vorgang": "Vorgang",
    "vorlagen.begriffe.umbenennen": "Umbenennen",
    "vorlagen.begriffe.zusammenfuehren": "Zusammenführen",
    "vorlagen.begriffe.ausmustern": "Ausmustern",
    "vorlagen.begriffe.bereich": "Geltungsbereich",
    "vorlagen.begriffe.alle": "Alle Spaces",
    "vorlagen.begriffe.name": "Begriff",
    "vorlagen.begriffe.ziel": "Neuer bzw. Ziel-Begriff",
    "vorlagen.begriffe.vorschau": "Betroffenen Bestand anzeigen",
    "vorlagen.begriffe.ausfuehren": "Jetzt ausführen",
    "vorlagen.begriffe.betroffen": "Betroffene Beiträge: {{anzahl}}.",
    "vorlagen.begriffe.jeSpace":
      "{{space}}: {{betroffen}} betroffen, {{ausserhalb}} außerhalb des Geltungsbereichs unverändert",
    "vorlagen.begriffe.unberuehrt":
      "{{anzahl}} Beiträge in anderen Spaces tragen den Begriff weiter und bleiben unverändert.",
    "vorlagen.begriffe.nichtEinsehbar": "(für Sie nicht einsehbar)",
    "vorlagen.begriffe.ansichtZiehtMit":
      "Ansicht „{{ansicht}}“ im Space „{{space}}“ zieht mit (neue Spacefassung).",
    "vorlagen.begriffe.ansichtBleibt":
      "Ansicht „{{ansicht}}“ im Space „{{space}}“ bleibt unverändert.",
    "vorlagen.begriffe.vorgabeZiehtMit":
      "Vorgaben des Space „{{space}}“ ziehen mit (neue Vorgabenfassung): {{vorher}} → {{nachher}}.",
    "vorlagen.begriffe.vorgabeBleibt":
      "Vorgaben des Space „{{space}}“ nennen den Begriff und bleiben unverändert: {{vorher}}.",
    "vorlagen.begriffe.wirkung":
      "Nur die genannten Beiträge bekommen den neuen Begriff; Inhalte und Fassungen bleiben. Suche und Filter finden sie unter dem neuen Begriff; neue Eingaben mit dem alten werden darauf hingewiesen.",
    "vorlagen.begriffe.wirkungAusmustern":
      "Ausmustern entfernt den Begriff aus keinem Beitrag. Neue Eingaben im Geltungsbereich werden darauf hingewiesen.",
    "vorlagen.begriffe.erledigt":
      "Erledigt: {{geaendert}} geändert, {{fehlgeschlagen}} nicht geändert.",
    "vorlagen.herkunft.mit": "Entstanden mit der Vorlage „{{name}}“, Fassung {{version}}.",
    "vorlagen.herkunft.neuer":
      "Die Vorlage hat inzwischen Fassung {{version}}; dieser Beitrag bleibt unverändert.",
    "vorlagen.herkunft.ausgemustert": "Die Vorlage ist inzwischen ausgemustert.",
    "vorlagen.herkunft.struktur": "Ausgangsstruktur anzeigen",
    "vorlagen.klara.label": "Vorlage",
    "vorlagen.klara.mit": "Du schreibst mit der Vorlage „{{name}}“ (Fassung {{version}}).",
    "vorlagen.klara.frei": "Du schreibst frei, ohne Vorlage.",
    "vorlagen.klara.felder": "Felder: {{liste}}.",
    "vorlagen.klara.pflicht": "Pflicht beim Einreichen: {{liste}}.",
    "vorlagen.klara.space": "Der Beitrag ist für den Space „{{space}}“ gedacht.",
    "vorlagen.klara.freiBleibt":
      "Freie Eingabe bleibt jederzeit möglich; ein Entwurf lässt sich auch unvollständig speichern.",
    "vorlagen.followUp.name": "der Vorlagenvermerk bzw. die Ablage im gewählten Space",
    "vorlagen.followUp.next":
      "Der Beitrag ist gespeichert. Bitte im Beitrag den Space über den Spacewechsel setzen.",
    "vorlagen.fehler.allgemein": "Das hat nicht geklappt. Bitte erneut versuchen.",
    "vorlagen.fehler.ungueltig":
      "Bitte die Angaben prüfen: Name und Feldtitel sind Pflicht, Feldtitel dürfen sich nicht wiederholen.",
    "vorlagen.fehler.veraltet": "Inzwischen geändert. Bitte neu laden.",
    "vorlagen.fehler.vorschauVeraltet":
      "Der Bestand hat sich seit der Vorschau geändert. Bitte die neue Vorschau prüfen.",
    "vorlagen.fehler.begruendung": "Bitte kurz begründen.",
    "vorlagen.fehler.ausgemustert": "Diese Vorlage ist ausgemustert oder hier nicht nutzbar.",
    "vorlagen.fehler.archiviert": "Der Space ist archiviert und nimmt nichts auf.",
    "vorlagen.fehler.recht": "Dafür fehlt Ihnen das Recht.",
  },
  en: {
    "audit.action.vorlage_angelegt": "Template created",
    "audit.action.vorlage_geaendert": "Template changed (new version)",
    "audit.action.vorlage_geteilt": "Template shared",
    "audit.action.vorlage_ausgemustert": "Template retired",
    "audit.action.vorlage_standard_gesetzt": "Personal default template set",
    "audit.action.vorlage_verwendet": "Submitted with template",
    "audit.action.space_vorgaben_geaendert": "Space requirements changed",
    "audit.action.begriff_umbenennen": "Term renamed",
    "audit.action.begriff_zusammenfuehren": "Terms merged",
    "audit.action.begriff_ausmustern": "Term retired",
    "vorlagen.ziel": "Templates, categories and tags",
    "vorlagen.seite.kicker": "Organise knowledge",
    "vorlagen.seite.titel": "Templates",
    "vorlagen.seite.lead":
      "Create your own templates, share them in a space or company-wide, choose your personal default and maintain space requirements.",
    "vorlagen.laedt": "Loading templates …",
    "vorlagen.laden.fehler": "Templates could not be loaded. Free input remains possible.",
    "vorlagen.neu": "New template",
    "vorlagen.liste.titel": "Available templates",
    "vorlagen.abbrechen": "Cancel",
    "vorlagen.bearbeiten": "Edit",
    "vorlagen.kopieren": "Copy as my own template",
    "vorlagen.verlauf": "Versions",
    "vorlagen.begruendung": "Reason",
    "vorlagen.fassung": "Version {{version}}",
    "vorlagen.istStandard": "Your default",
    "vorlagen.ausgemustert": "retired",
    "vorlagen.ohneSpace": "no space",
    "vorlagen.pflicht.marke": "Required",
    "vorlagen.pflicht.erklaerung":
      "Required fields are checked on submission. You can save an incomplete draft at any time.",
    "vorlagen.geltung.standard": "Standard",
    "vorlagen.geltung.unternehmen": "Company-wide",
    "vorlagen.geltung.space": "In space",
    "vorlagen.geltung.persoenlich": "Personal",
    "vorlagen.geltung.erklaerung.persoenlich": "Only you see and use this template.",
    "vorlagen.geltung.erklaerung.space":
      "Everyone who reads the space uses the template. You (with write access) and the space owners may change it.",
    "vorlagen.geltung.erklaerung.unternehmen":
      "Everyone uses the template. Only account administration may change it.",
    "vorlagen.einschraenkung.unternehmen":
      "Company-wide structure: only account administration may change it; every change becomes a new version.",
    "vorlagen.einschraenkung.standard": "Standard template: unchangeable. Copy it to adapt it.",
    "vorlagen.art.absatz": "Paragraph",
    "vorlagen.art.liste": "List",
    "vorlagen.art.schritte": "Steps",
    "vorlagen.art.hinweis": "Note",
    "vorlagen.art.warnung": "Warning",
    "vorlagen.vorgang.angelegt": "created",
    "vorlagen.vorgang.geaendert": "changed",
    "vorlagen.vorgang.geteilt": "shared",
    "vorlagen.vorgang.ausgemustert": "retired",
    "vorlagen.wahl.titel": "Template",
    "vorlagen.wahl.verwalten": "Manage templates",
    "vorlagen.wahl.hinweis":
      "Choose a structure. Nothing is inserted without a click, and entered values are not lost.",
    "vorlagen.wahl.space": "For space:",
    "vorlagen.wahl.ohneSpace": "— no space —",
    "vorlagen.zeile.mit": "Template: “{{name}}” (version {{version}}).",
    "vorlagen.zeile.waehlen": "Choose template",
    "vorlagen.zeile.aendern": "Other template or free input",
    "vorlagen.zeile.schliessen": "Collapse",
    "vorlagen.frei.knopf": "Free input",
    "vorlagen.frei.hinweis":
      "Free input: no template. Your text stays unchanged; you can choose a template again at any time.",
    "vorlagen.frei.ohneSpace":
      "Without a template the entry is not assigned to a space; do that afterwards via the space change.",
    "vorlagen.vorrang.space":
      "In space “{{space}}”, “{{name}}” is mandatory and takes precedence over your default.",
    "vorlagen.vorrang.persoenlich": "Preselected: your default “{{name}}”.",
    "vorlagen.vorrang.frei": "No default chosen — free input.",
    "vorlagen.vorrang.ersatz.ausgemustert":
      "Your default “{{name}}” has been retired. Free input applies; please choose a new default.",
    "vorlagen.vorrang.ersatz.nicht_verfuegbar":
      "Your default “{{name}}” is no longer available. Free input applies; please choose a new default.",
    "vorlagen.vorrang.verdraengt": "(Your default “{{name}}” steps back here.)",
    "vorlagen.vorrang.regel":
      "Precedence for new input: a template mandatory in the chosen space, otherwise your default, otherwise free input. If your default is no longer available, the reason is shown — content is never removed.",
    "vorlagen.standard.titel": "My default",
    "vorlagen.standard.ist": "Your default: “{{name}}”.",
    "vorlagen.standard.keiner": "No default — new input starts free.",
    "vorlagen.standard.nichtVerfuegbar":
      "Your default is no longer available; new input starts free. Please choose a new one.",
    "vorlagen.standard.setzen": "Make my default",
    "vorlagen.standard.aufheben": "Remove default",
    "vorlagen.anwenden.setzen": "Insert template",
    "vorlagen.anwenden.anfuegen": "Append below the text",
    "vorlagen.anwenden.wechseln": "Switch template",
    "vorlagen.wechsel.weitere": "Further content (from the previous structure)",
    "vorlagen.wechsel.schon": "This template and version is already applied.",
    "vorlagen.wechsel.vorschau": "Preview of the result",
    "vorlagen.wechsel.setzen": "The empty content gets the structure of this template.",
    "vorlagen.wechsel.angefuegt":
      "Your text stays unchanged at the top; the structure is appended below.",
    "vorlagen.wechsel.angefuegtErledigt":
      "Structure appended below your text. Nothing was removed.",
    "vorlagen.wechsel.plan": "When switching:",
    "vorlagen.wechsel.erledigt": "Switched:",
    "vorlagen.wechsel.uebernommen": "carried over into {{liste}}.",
    "vorlagen.wechsel.nichtsUebernommen": "no section matches directly.",
    "vorlagen.wechsel.verschoben":
      "Placed unchanged at the end under “Further content”: {{liste}}.",
    "vorlagen.wechsel.leer": "Only empty hints are dropped: {{liste}}.",
    "vorlagen.vorgabe.titel": "Requirements in space “{{space}}”",
    "vorlagen.vorgabe.verbindlich":
      "Mandatory template: “{{name}}” — its required fields apply even with free input.",
    "vorlagen.vorgabe.verbindlichFehlt":
      "The mandatory template is no longer available; its required fields do not apply.",
    "vorlagen.vorgabe.kategorien": "Category: one of {{liste}}.",
    "vorlagen.vorgabe.pflichtKategorie": "A category is required.",
    "vorlagen.vorgabe.tags": "At least {{anzahl}} tag(s).",
    "vorlagen.vorgabe.vorschlag": "Suggested tags: {{liste}}.",
    "vorlagen.vorgabe.wann":
      "Checked on submission; saving always works. The entry is filed in this space.",
    "vorlagen.pruefen.knopf": "Check required details",
    "vorlagen.pruefen.ok": "All required details are complete.",
    "vorlagen.befund.vorlagenfeld": "The required field “{{wert}}” is still empty.",
    "vorlagen.befund.kategorie_fehlt": "Please enter a category.",
    "vorlagen.befund.kategorie_nicht_erlaubt":
      "The category “{{wert}}” is not intended in this space.",
    "vorlagen.befund.tags_fehlen": "Please enter at least {{wert}} tag(s).",
    "vorlagen.befund.begriff_ersetzt":
      "“{{wert}}” was renamed or merged — please use the new term.",
    "vorlagen.befund.begriff_ausgemustert":
      "“{{wert}}” has been retired and is no longer used for new entries.",
    "vorlagen.feld.name": "Name",
    "vorlagen.feld.geltung": "Scope",
    "vorlagen.feld.space": "Space",
    "vorlagen.feld.beschreibung": "Description",
    "vorlagen.feld.felder": "Fields (order = order in the entry)",
    "vorlagen.feld.titel": "Title of field {{nummer}}",
    "vorlagen.feld.hinweis": "Hint for field {{nummer}}",
    "vorlagen.feld.art": "Type of field {{nummer}}",
    "vorlagen.feld.hoch": "Move field {{nummer}} up",
    "vorlagen.feld.runter": "Move field {{nummer}} down",
    "vorlagen.feld.entfernen": "Remove field {{nummer}}",
    "vorlagen.feld.neu": "Add field",
    "vorlagen.formular.anlegen": "Create template",
    "vorlagen.formular.auswirkungen": "Check impact",
    "vorlagen.formular.neueFassung": "Save new version",
    "vorlagen.wirkung.titel": "Impact of this change",
    "vorlagen.wirkung.neu": "New fields: {{liste}}.",
    "vorlagen.wirkung.entfernt": "Removed fields: {{liste}}.",
    "vorlagen.wirkung.umbenannt": "“{{vorher}}” is now called “{{nachher}}”.",
    "vorlagen.wirkung.pflichtNeu": "Newly required: {{liste}}.",
    "vorlagen.wirkung.pflichtEntfallen": "No longer required: {{liste}}.",
    "vorlagen.wirkung.geltung": "Scope: {{vorher}} → {{nachher}}.",
    "vorlagen.wirkung.nutzung": "Existing entries using this template: {{anzahl}} {{fassungen}}",
    "vorlagen.wirkung.jeFassung": "version {{version}}: {{anzahl}}",
    "vorlagen.wirkung.jeSpace": "Per space: {{liste}}.",
    "vorlagen.wirkung.standardBei": "Chosen as personal default: {{anzahl}}.",
    "vorlagen.wirkung.verbindlichIn": "Mandatory in: {{liste}}.",
    "vorlagen.wirkung.bestand":
      "Existing entries keep their values and their link to the version they were created with. New required fields only apply to new submissions; old articles are not reformatted.",
    "vorlagen.ausmustern.knopf": "Retire",
    "vorlagen.ausmustern.erklaerung":
      "A retired template is no longer offered. Existing entries keep values and version link; anyone with it as default starts with free input and sees the reason.",
    "vorlagen.vorgaben.titel": "Space requirements",
    "vorlagen.vorgaben.erklaerung":
      "What input for this space must bring. Applies to everyone writing in this space and takes precedence over personal defaults.",
    "vorlagen.vorgaben.verbindlich": "Mandatory template",
    "vorlagen.vorgaben.keine": "— none —",
    "vorlagen.vorgaben.kategorien": "Allowed categories (comma-separated, empty = all)",
    "vorlagen.vorgaben.pflichtKategorie": "Category is required",
    "vorlagen.vorgaben.mindestensTags": "Minimum number of tags (0–5)",
    "vorlagen.vorgaben.tags": "Suggested tags (comma-separated)",
    "vorlagen.vorgaben.hinweis": "Explanation for writers",
    "vorlagen.vorgaben.wirkung":
      "The requirements apply only in this space and only to new submissions; other spaces and existing entries remain unchanged.",
    "vorlagen.vorgaben.speichern": "Save requirements",
    "vorlagen.vorgaben.gespeichert": "Requirements saved — as a new version.",
    "vorlagen.vorgaben.verlauf": "{{anzahl}} version(s), last {{am}}.",
    "vorlagen.verwaltung.titel": "Scope and usage",
    "vorlagen.verwaltung.erklaerung":
      "Shared templates, categories and tags with their usage per space. Personal templates appear only as a number.",
    "vorlagen.verwaltung.nutzung": "Entries (per version · per space)",
    "vorlagen.verwaltung.standardBei": "Default for",
    "vorlagen.verwaltung.verbindlichIn": "Mandatory in",
    "vorlagen.verwaltung.persoenlich":
      "Personal templates: {{vorlagen}}, entries submitted with them: {{beitraege}}.",
    "vorlagen.verwaltung.kategorien": "Categories",
    "vorlagen.verwaltung.tags": "Tags",
    "vorlagen.verwaltung.vorgegebenIn": "required in {{liste}}",
    "vorlagen.verwaltung.nichtEinsehbar":
      "{{anzahl}} entries are not visible to you and are not broken down by term here.",
    "vorlagen.begriffe.titel": "Maintain category or tag",
    "vorlagen.begriffe.art": "Kind",
    "vorlagen.begriffe.tag": "Tag",
    "vorlagen.begriffe.kategorie": "Category",
    "vorlagen.begriffe.vorgang": "Action",
    "vorlagen.begriffe.umbenennen": "Rename",
    "vorlagen.begriffe.zusammenfuehren": "Merge",
    "vorlagen.begriffe.ausmustern": "Retire",
    "vorlagen.begriffe.bereich": "Scope",
    "vorlagen.begriffe.alle": "All spaces",
    "vorlagen.begriffe.name": "Term",
    "vorlagen.begriffe.ziel": "New or target term",
    "vorlagen.begriffe.vorschau": "Show affected entries",
    "vorlagen.begriffe.ausfuehren": "Apply now",
    "vorlagen.begriffe.betroffen": "Affected entries: {{anzahl}}.",
    "vorlagen.begriffe.jeSpace":
      "{{space}}: {{betroffen}} affected, {{ausserhalb}} outside the scope unchanged",
    "vorlagen.begriffe.unberuehrt":
      "{{anzahl}} entries in other spaces keep the term and remain unchanged.",
    "vorlagen.begriffe.nichtEinsehbar": "(not visible to you)",
    "vorlagen.begriffe.ansichtZiehtMit":
      "View “{{ansicht}}” in space “{{space}}” follows (new space version).",
    "vorlagen.begriffe.ansichtBleibt": "View “{{ansicht}}” in space “{{space}}” stays unchanged.",
    "vorlagen.begriffe.vorgabeZiehtMit":
      "Requirements of space “{{space}}” follow (new requirements version): {{vorher}} → {{nachher}}.",
    "vorlagen.begriffe.vorgabeBleibt":
      "Requirements of space “{{space}}” name the term and stay unchanged: {{vorher}}.",
    "vorlagen.begriffe.wirkung":
      "Only the listed entries get the new term; content and versions remain. Search and filters find them under the new term; new input with the old one is pointed to it.",
    "vorlagen.begriffe.wirkungAusmustern":
      "Retiring removes the term from no entry. New input in the scope is pointed to it.",
    "vorlagen.begriffe.erledigt": "Done: {{geaendert}} changed, {{fehlgeschlagen}} not changed.",
    "vorlagen.herkunft.mit": "Created with the template “{{name}}”, version {{version}}.",
    "vorlagen.herkunft.neuer":
      "The template is now at version {{version}}; this entry remains unchanged.",
    "vorlagen.herkunft.ausgemustert": "The template has since been retired.",
    "vorlagen.herkunft.struktur": "Show original structure",
    "vorlagen.klara.label": "Template",
    "vorlagen.klara.mit": "You are writing with the template “{{name}}” (version {{version}}).",
    "vorlagen.klara.frei": "You are writing freely, without a template.",
    "vorlagen.klara.felder": "Fields: {{liste}}.",
    "vorlagen.klara.pflicht": "Required on submission: {{liste}}.",
    "vorlagen.klara.space": "The entry is meant for the space “{{space}}”.",
    "vorlagen.klara.freiBleibt":
      "Free input remains possible at any time; a draft can also be saved incomplete.",
    "vorlagen.followUp.name": "recording the template or filing in the chosen space",
    "vorlagen.followUp.next":
      "The entry is saved. Please set the space in the entry via the space change.",
    "vorlagen.fehler.allgemein": "That did not work. Please try again.",
    "vorlagen.fehler.ungueltig":
      "Please check the details: name and field titles are required, field titles must not repeat.",
    "vorlagen.fehler.veraltet": "Changed in the meantime. Please reload.",
    "vorlagen.fehler.vorschauVeraltet":
      "The data has changed since the preview. Please check the new preview.",
    "vorlagen.fehler.begruendung": "Please give a short reason.",
    "vorlagen.fehler.ausgemustert": "This template is retired or not usable here.",
    "vorlagen.fehler.archiviert": "The space is archived and accepts nothing.",
    "vorlagen.fehler.recht": "You do not have the right to do this.",
  },
  nl: {
    "audit.action.vorlage_angelegt": "Sjabloon aangemaakt",
    "audit.action.vorlage_geaendert": "Sjabloon gewijzigd (nieuwe versie)",
    "audit.action.vorlage_geteilt": "Sjabloon gedeeld",
    "audit.action.vorlage_ausgemustert": "Sjabloon buiten gebruik gesteld",
    "audit.action.vorlage_standard_gesetzt": "Persoonlijk standaardsjabloon ingesteld",
    "audit.action.vorlage_verwendet": "Ingediend met sjabloon",
    "audit.action.space_vorgaben_geaendert": "Space-vereisten gewijzigd",
    "audit.action.begriff_umbenennen": "Begrip hernoemd",
    "audit.action.begriff_zusammenfuehren": "Begrippen samengevoegd",
    "audit.action.begriff_ausmustern": "Begrip buiten gebruik gesteld",
    "vorlagen.ziel": "Sjablonen, categorieën en tags",
    "vorlagen.seite.kicker": "Kennis ordenen",
    "vorlagen.seite.titel": "Sjablonen",
    "vorlagen.seite.lead":
      "Eigen sjablonen aanmaken, in een space of bedrijfsbreed delen, uw persoonlijke standaard kiezen en space-vereisten beheren.",
    "vorlagen.laedt": "Sjablonen worden geladen …",
    "vorlagen.laden.fehler":
      "De sjablonen konden niet worden geladen. Vrije invoer blijft mogelijk.",
    "vorlagen.neu": "Nieuw sjabloon",
    "vorlagen.liste.titel": "Beschikbare sjablonen",
    "vorlagen.abbrechen": "Annuleren",
    "vorlagen.bearbeiten": "Bewerken",
    "vorlagen.kopieren": "Kopiëren als eigen sjabloon",
    "vorlagen.verlauf": "Versies",
    "vorlagen.begruendung": "Reden",
    "vorlagen.fassung": "Versie {{version}}",
    "vorlagen.istStandard": "Uw standaard",
    "vorlagen.ausgemustert": "buiten gebruik",
    "vorlagen.ohneSpace": "zonder space",
    "vorlagen.pflicht.marke": "Verplicht",
    "vorlagen.pflicht.erklaerung":
      "Verplichte velden worden bij het indienen gecontroleerd. Een onvolledig concept kunt u altijd opslaan.",
    "vorlagen.geltung.standard": "Standaard",
    "vorlagen.geltung.unternehmen": "Bedrijfsbreed",
    "vorlagen.geltung.space": "In de space",
    "vorlagen.geltung.persoenlich": "Persoonlijk",
    "vorlagen.geltung.erklaerung.persoenlich": "Alleen u ziet en gebruikt dit sjabloon.",
    "vorlagen.geltung.erklaerung.space":
      "Iedereen die de space leest, gebruikt het sjabloon. Wijzigen mogen u (met schrijfrecht) en de space-verantwoordelijken.",
    "vorlagen.geltung.erklaerung.unternehmen":
      "Iedereen gebruikt het sjabloon. Alleen het accountbeheer mag het wijzigen.",
    "vorlagen.einschraenkung.unternehmen":
      "Bedrijfsbrede structuur: alleen het accountbeheer mag haar wijzigen; elke wijziging wordt een nieuwe versie.",
    "vorlagen.einschraenkung.standard":
      "Standaardsjabloon: onveranderlijk. Kopieer het om het aan te passen.",
    "vorlagen.art.absatz": "Alinea",
    "vorlagen.art.liste": "Lijst",
    "vorlagen.art.schritte": "Stappen",
    "vorlagen.art.hinweis": "Opmerking",
    "vorlagen.art.warnung": "Waarschuwing",
    "vorlagen.vorgang.angelegt": "aangemaakt",
    "vorlagen.vorgang.geaendert": "gewijzigd",
    "vorlagen.vorgang.geteilt": "gedeeld",
    "vorlagen.vorgang.ausgemustert": "buiten gebruik gesteld",
    "vorlagen.wahl.titel": "Sjabloon",
    "vorlagen.wahl.verwalten": "Sjablonen beheren",
    "vorlagen.wahl.hinweis":
      "Kies een structuur. Niets wordt zonder klik ingevoegd en ingevoerde waarden gaan niet verloren.",
    "vorlagen.wahl.space": "Voor space:",
    "vorlagen.wahl.ohneSpace": "— geen space —",
    "vorlagen.zeile.mit": "Sjabloon: „{{name}}” (versie {{version}}).",
    "vorlagen.zeile.waehlen": "Sjabloon kiezen",
    "vorlagen.zeile.aendern": "Ander sjabloon of vrije invoer",
    "vorlagen.zeile.schliessen": "Inklappen",
    "vorlagen.frei.knopf": "Vrije invoer",
    "vorlagen.frei.hinweis":
      "Vrije invoer: zonder sjabloon. Uw tekst blijft ongewijzigd; u kunt op elk moment weer een sjabloon kiezen.",
    "vorlagen.frei.ohneSpace":
      "Zonder sjabloon wordt de bijdrage aan geen space toegewezen; dat kan daarna via de space-wissel.",
    "vorlagen.vorrang.space":
      "In de space „{{space}}” is „{{name}}” verplicht en gaat voor op uw standaard.",
    "vorlagen.vorrang.persoenlich": "Voorgeselecteerd: uw standaard „{{name}}”.",
    "vorlagen.vorrang.frei": "Geen standaard gekozen — vrije invoer.",
    "vorlagen.vorrang.ersatz.ausgemustert":
      "Uw standaard „{{name}}” is buiten gebruik gesteld. Vrije invoer geldt; kies a.u.b. een nieuwe standaard.",
    "vorlagen.vorrang.ersatz.nicht_verfuegbar":
      "Uw standaard „{{name}}” is niet meer beschikbaar. Vrije invoer geldt; kies a.u.b. een nieuwe standaard.",
    "vorlagen.vorrang.verdraengt": "(Uw standaard „{{name}}” treedt hier terug.)",
    "vorlagen.vorrang.regel":
      "Voorrang bij nieuwe invoer: een in de gekozen space verplicht sjabloon, anders uw standaard, anders vrije invoer. Is uw standaard niet meer beschikbaar, dan staat de reden erbij — inhoud wordt nooit verwijderd.",
    "vorlagen.standard.titel": "Mijn standaard",
    "vorlagen.standard.ist": "Uw standaard: „{{name}}”.",
    "vorlagen.standard.keiner": "Geen standaard — nieuwe invoer begint vrij.",
    "vorlagen.standard.nichtVerfuegbar":
      "Uw standaard is niet meer beschikbaar; nieuwe invoer begint vrij. Kies a.u.b. een nieuwe.",
    "vorlagen.standard.setzen": "Als mijn standaard",
    "vorlagen.standard.aufheben": "Standaard opheffen",
    "vorlagen.anwenden.setzen": "Sjabloon invoegen",
    "vorlagen.anwenden.anfuegen": "Onder de tekst toevoegen",
    "vorlagen.anwenden.wechseln": "Sjabloon wisselen",
    "vorlagen.wechsel.weitere": "Overige inhoud (uit de vorige structuur)",
    "vorlagen.wechsel.schon": "Dit sjabloon en deze versie zijn al toegepast.",
    "vorlagen.wechsel.vorschau": "Voorbeeld van het resultaat",
    "vorlagen.wechsel.setzen": "De lege inhoud krijgt de structuur van dit sjabloon.",
    "vorlagen.wechsel.angefuegt":
      "Uw tekst blijft bovenaan ongewijzigd; de structuur wordt eronder toegevoegd.",
    "vorlagen.wechsel.angefuegtErledigt":
      "Structuur onder uw tekst toegevoegd. Er is niets verwijderd.",
    "vorlagen.wechsel.plan": "Bij het wisselen:",
    "vorlagen.wechsel.erledigt": "Gewisseld:",
    "vorlagen.wechsel.uebernommen": "overgenomen in {{liste}}.",
    "vorlagen.wechsel.nichtsUebernommen": "geen sectie past direct.",
    "vorlagen.wechsel.verschoben":
      "Ongewijzigd aan het einde onder „Overige inhoud” geplaatst: {{liste}}.",
    "vorlagen.wechsel.leer": "Alleen lege aanwijzingen vervallen: {{liste}}.",
    "vorlagen.vorgabe.titel": "Vereisten in de space „{{space}}”",
    "vorlagen.vorgabe.verbindlich":
      "Verplicht sjabloon: „{{name}}” — de verplichte velden gelden ook bij vrije invoer.",
    "vorlagen.vorgabe.verbindlichFehlt":
      "Het verplichte sjabloon is niet meer beschikbaar; de verplichte velden gelden niet.",
    "vorlagen.vorgabe.kategorien": "Categorie: een van {{liste}}.",
    "vorlagen.vorgabe.pflichtKategorie": "Een categorie is verplicht.",
    "vorlagen.vorgabe.tags": "Minstens {{anzahl}} tag(s).",
    "vorlagen.vorgabe.vorschlag": "Voorgestelde tags: {{liste}}.",
    "vorlagen.vorgabe.wann":
      "Gecontroleerd bij het indienen; opslaan kan altijd. De bijdrage wordt in deze space geplaatst.",
    "vorlagen.pruefen.knopf": "Verplichte gegevens controleren",
    "vorlagen.pruefen.ok": "Alle verplichte gegevens zijn ingevuld.",
    "vorlagen.befund.vorlagenfeld": "Het verplichte veld „{{wert}}” is nog leeg.",
    "vorlagen.befund.kategorie_fehlt": "Geef a.u.b. een categorie op.",
    "vorlagen.befund.kategorie_nicht_erlaubt":
      "De categorie „{{wert}}” is in deze space niet voorzien.",
    "vorlagen.befund.tags_fehlen": "Geef a.u.b. minstens {{wert}} tag(s) op.",
    "vorlagen.befund.begriff_ersetzt":
      "„{{wert}}” is hernoemd of samengevoegd — gebruik a.u.b. het nieuwe begrip.",
    "vorlagen.befund.begriff_ausgemustert":
      "„{{wert}}” is buiten gebruik gesteld en wordt voor nieuwe bijdragen niet meer gebruikt.",
    "vorlagen.feld.name": "Naam",
    "vorlagen.feld.geltung": "Geldigheid",
    "vorlagen.feld.space": "Space",
    "vorlagen.feld.beschreibung": "Beschrijving",
    "vorlagen.feld.felder": "Velden (volgorde = volgorde in de bijdrage)",
    "vorlagen.feld.titel": "Titel van veld {{nummer}}",
    "vorlagen.feld.hinweis": "Aanwijzing bij veld {{nummer}}",
    "vorlagen.feld.art": "Soort van veld {{nummer}}",
    "vorlagen.feld.hoch": "Veld {{nummer}} omhoog",
    "vorlagen.feld.runter": "Veld {{nummer}} omlaag",
    "vorlagen.feld.entfernen": "Veld {{nummer}} verwijderen",
    "vorlagen.feld.neu": "Veld toevoegen",
    "vorlagen.formular.anlegen": "Sjabloon aanmaken",
    "vorlagen.formular.auswirkungen": "Gevolgen controleren",
    "vorlagen.formular.neueFassung": "Nieuwe versie opslaan",
    "vorlagen.wirkung.titel": "Gevolgen van deze wijziging",
    "vorlagen.wirkung.neu": "Nieuwe velden: {{liste}}.",
    "vorlagen.wirkung.entfernt": "Verwijderde velden: {{liste}}.",
    "vorlagen.wirkung.umbenannt": "„{{vorher}}” heet nu „{{nachher}}”.",
    "vorlagen.wirkung.pflichtNeu": "Nieuw verplicht: {{liste}}.",
    "vorlagen.wirkung.pflichtEntfallen": "Niet meer verplicht: {{liste}}.",
    "vorlagen.wirkung.geltung": "Geldigheid: {{vorher}} → {{nachher}}.",
    "vorlagen.wirkung.nutzung": "Bestaande bijdragen met dit sjabloon: {{anzahl}} {{fassungen}}",
    "vorlagen.wirkung.jeFassung": "versie {{version}}: {{anzahl}}",
    "vorlagen.wirkung.jeSpace": "Per space: {{liste}}.",
    "vorlagen.wirkung.standardBei": "Als persoonlijke standaard gekozen: {{anzahl}}.",
    "vorlagen.wirkung.verbindlichIn": "Verplicht in: {{liste}}.",
    "vorlagen.wirkung.bestand":
      "Bestaande bijdragen behouden hun waarden en de koppeling met de versie waarmee ze zijn ontstaan. Nieuwe verplichte velden gelden alleen voor nieuwe indieningen; oude artikelen worden niet opnieuw opgemaakt.",
    "vorlagen.ausmustern.knopf": "Buiten gebruik stellen",
    "vorlagen.ausmustern.erklaerung":
      "Een buiten gebruik gesteld sjabloon wordt niet meer aangeboden. Bestaande bijdragen behouden waarden en versiekoppeling; wie het als standaard had, begint met vrije invoer en ziet de reden.",
    "vorlagen.vorgaben.titel": "Space-vereisten",
    "vorlagen.vorgaben.erklaerung":
      "Wat invoer voor deze space moet meebrengen. Geldt voor iedereen die in deze space schrijft en gaat voor op persoonlijke standaarden.",
    "vorlagen.vorgaben.verbindlich": "Verplicht sjabloon",
    "vorlagen.vorgaben.keine": "— geen —",
    "vorlagen.vorgaben.kategorien": "Toegestane categorieën (gescheiden door komma, leeg = alle)",
    "vorlagen.vorgaben.pflichtKategorie": "Categorie is verplicht",
    "vorlagen.vorgaben.mindestensTags": "Minimumaantal tags (0–5)",
    "vorlagen.vorgaben.tags": "Voorgestelde tags (gescheiden door komma)",
    "vorlagen.vorgaben.hinweis": "Toelichting voor schrijvers",
    "vorlagen.vorgaben.wirkung":
      "De vereisten gelden alleen in deze space en pas voor nieuwe indieningen; andere spaces en bestaande bijdragen blijven ongewijzigd.",
    "vorlagen.vorgaben.speichern": "Vereisten opslaan",
    "vorlagen.vorgaben.gespeichert": "Vereisten opgeslagen — als nieuwe versie.",
    "vorlagen.vorgaben.verlauf": "{{anzahl}} versie(s), laatst {{am}}.",
    "vorlagen.verwaltung.titel": "Geldigheid en gebruik",
    "vorlagen.verwaltung.erklaerung":
      "Gedeelde sjablonen, categorieën en tags met hun gebruik per space. Persoonlijke sjablonen verschijnen alleen als aantal.",
    "vorlagen.verwaltung.nutzung": "Bijdragen (per versie · per space)",
    "vorlagen.verwaltung.standardBei": "Standaard bij",
    "vorlagen.verwaltung.verbindlichIn": "Verplicht in",
    "vorlagen.verwaltung.persoenlich":
      "Persoonlijke sjablonen: {{vorlagen}}, daarmee ingediende bijdragen: {{beitraege}}.",
    "vorlagen.verwaltung.kategorien": "Categorieën",
    "vorlagen.verwaltung.tags": "Tags",
    "vorlagen.verwaltung.vorgegebenIn": "voorgeschreven in {{liste}}",
    "vorlagen.verwaltung.nichtEinsehbar":
      "{{anzahl}} bijdragen zijn voor u niet zichtbaar en worden hier niet naar begrip uitgesplitst.",
    "vorlagen.begriffe.titel": "Categorie of tag beheren",
    "vorlagen.begriffe.art": "Soort",
    "vorlagen.begriffe.tag": "Tag",
    "vorlagen.begriffe.kategorie": "Categorie",
    "vorlagen.begriffe.vorgang": "Handeling",
    "vorlagen.begriffe.umbenennen": "Hernoemen",
    "vorlagen.begriffe.zusammenfuehren": "Samenvoegen",
    "vorlagen.begriffe.ausmustern": "Buiten gebruik stellen",
    "vorlagen.begriffe.bereich": "Geldigheidsbereik",
    "vorlagen.begriffe.alle": "Alle spaces",
    "vorlagen.begriffe.name": "Begrip",
    "vorlagen.begriffe.ziel": "Nieuw of doelbegrip",
    "vorlagen.begriffe.vorschau": "Betrokken bijdragen tonen",
    "vorlagen.begriffe.ausfuehren": "Nu uitvoeren",
    "vorlagen.begriffe.betroffen": "Betrokken bijdragen: {{anzahl}}.",
    "vorlagen.begriffe.jeSpace":
      "{{space}}: {{betroffen}} betrokken, {{ausserhalb}} buiten het bereik ongewijzigd",
    "vorlagen.begriffe.unberuehrt":
      "{{anzahl}} bijdragen in andere spaces behouden het begrip en blijven ongewijzigd.",
    "vorlagen.begriffe.nichtEinsehbar": "(voor u niet zichtbaar)",
    "vorlagen.begriffe.ansichtZiehtMit":
      "Weergave „{{ansicht}}” in de space „{{space}}” gaat mee (nieuwe spaceversie).",
    "vorlagen.begriffe.ansichtBleibt":
      "Weergave „{{ansicht}}” in de space „{{space}}” blijft ongewijzigd.",
    "vorlagen.begriffe.vorgabeZiehtMit":
      "Eisen van de space „{{space}}” gaan mee (nieuwe versie van de eisen): {{vorher}} → {{nachher}}.",
    "vorlagen.begriffe.vorgabeBleibt":
      "Eisen van de space „{{space}}” noemen het begrip en blijven ongewijzigd: {{vorher}}.",
    "vorlagen.begriffe.wirkung":
      "Alleen de genoemde bijdragen krijgen het nieuwe begrip; inhoud en versies blijven. Zoeken en filters vinden ze onder het nieuwe begrip; nieuwe invoer met het oude wordt erop gewezen.",
    "vorlagen.begriffe.wirkungAusmustern":
      "Buiten gebruik stellen verwijdert het begrip uit geen enkele bijdrage. Nieuwe invoer in het bereik wordt erop gewezen.",
    "vorlagen.begriffe.erledigt":
      "Klaar: {{geaendert}} gewijzigd, {{fehlgeschlagen}} niet gewijzigd.",
    "vorlagen.herkunft.mit": "Ontstaan met het sjabloon „{{name}}”, versie {{version}}.",
    "vorlagen.herkunft.neuer":
      "Het sjabloon heeft inmiddels versie {{version}}; deze bijdrage blijft ongewijzigd.",
    "vorlagen.herkunft.ausgemustert": "Het sjabloon is inmiddels buiten gebruik gesteld.",
    "vorlagen.herkunft.struktur": "Oorspronkelijke structuur tonen",
    "vorlagen.klara.label": "Sjabloon",
    "vorlagen.klara.mit": "Je schrijft met het sjabloon „{{name}}” (versie {{version}}).",
    "vorlagen.klara.frei": "Je schrijft vrij, zonder sjabloon.",
    "vorlagen.klara.felder": "Velden: {{liste}}.",
    "vorlagen.klara.pflicht": "Verplicht bij indienen: {{liste}}.",
    "vorlagen.klara.space": "De bijdrage is bedoeld voor de space „{{space}}”.",
    "vorlagen.klara.freiBleibt":
      "Vrije invoer blijft altijd mogelijk; een concept kan ook onvolledig worden opgeslagen.",
    "vorlagen.followUp.name": "de sjabloonvermelding of plaatsing in de gekozen space",
    "vorlagen.followUp.next":
      "De bijdrage is opgeslagen. Stel a.u.b. in de bijdrage de space in via de space-wissel.",
    "vorlagen.fehler.allgemein": "Dat is niet gelukt. Probeer het opnieuw.",
    "vorlagen.fehler.ungueltig":
      "Controleer de gegevens: naam en veldtitels zijn verplicht, veldtitels mogen niet herhaald worden.",
    "vorlagen.fehler.veraltet": "Inmiddels gewijzigd. Laad opnieuw.",
    "vorlagen.fehler.vorschauVeraltet":
      "De gegevens zijn sinds het voorbeeld gewijzigd. Controleer het nieuwe voorbeeld.",
    "vorlagen.fehler.begruendung": "Geef a.u.b. een korte reden.",
    "vorlagen.fehler.ausgemustert": "Dit sjabloon is buiten gebruik of hier niet bruikbaar.",
    "vorlagen.fehler.archiviert": "De space is gearchiveerd en neemt niets op.",
    "vorlagen.fehler.recht": "Daarvoor ontbreekt u het recht.",
  },
} satisfies Textmodul;
