// ================================================================================================
// ADMIN-11 · WISSENSKENNZAHLEN — Handlungsbedarf zuerst, jede Zahl mit Grundmenge und Datenstand.
// ================================================================================================
//
// Die Texte behaupten nichts, was die Zahl nicht trägt: „nicht erhoben", „unvollständig" und
// „unbekannt" sind eigene Aussagen und keine Null. Fragen, Antworten und Aktivität beschreiben
// Nutzung — sie werden ausdrücklich nicht als gemessene Zeit- oder Geldersparnis ausgegeben.
import type { Textmodul } from "./intern/pruefung";

export default {
  praefix: "wkz.",
  legacySchluessel: [],
  de: {
    "wkz.titel": "Handlungsbedarf und Wissenskennzahlen",
    "wkz.leitsatz":
      "Zuerst, was jetzt offen ist; darunter Fragen und Lücken im gewählten Zeitraum. Jede Zahl nennt Bedeutung, Grundmenge, Zeitraum und Datenstand.",
    "wkz.laedt": "Kennzahlen werden geladen …",
    "wkz.fehler": "Die Kennzahlen konnten nicht geladen werden.",
    "wkz.recht": "Diese Kennzahlen sind der Verwaltung vorbehalten.",
    "wkz.erneut": "Erneut laden",
    "wkz.aktualisieren": "Aktualisieren",
    "wkz.stand": "Stand {{zeit}}",
    "wkz.zeitraum": "Zeitraum: {{von}} bis {{bis}}",
    "wkz.vorperiode": "Vergleich mit {{von}} bis {{bis}}",
    "wkz.filter.titel": "Auswahl",
    "wkz.filter.zeitraum": "Zeitraum",
    "wkz.filter.tage": "Letzte {{anzahl}} Tage",
    "wkz.filter.space": "Space",
    "wkz.filter.team": "Team",
    "wkz.filter.alle": "Alle",
    "wkz.filter.zuruecksetzen": "Auswahl zurücksetzen",
    "wkz.filter.hinweis":
      "Space und Team grenzen auf Inhalte in diesen Spaces ein. Quellen ohne Space-Angabe (Fragen und Lücken) stehen dann als „nicht erhoben“ da.",
    "wkz.filter.ungueltig":
      "Diese Auswahl ist nicht verfügbar — der Space oder das Team ist für Sie nicht wählbar.",
    "wkz.quelle.teilweise":
      "Nicht alle Vorgangsquellen waren abrufbar. Betroffene Zahlen stehen als „unbekannt“, nicht als 0.",
    "wkz.handlungsbedarf.titel": "Jetzt offen",
    "wkz.handlungsbedarf.erklaerung":
      "Momentaufnahme zum Stand. Ein Verlauf fehlt bewusst: frühere Stände werden nicht gespeichert und deshalb nicht nachgebildet.",
    "wkz.nutzung.titel": "Fragen und Lücken im Zeitraum",
    "wkz.nutzung.erklaerung":
      "Gezählt aus dem Frageprotokoll und den Wissenslücken. Die Zahlen beschreiben Nutzung — sie sind keine gemessene Zeit- oder Geldersparnis.",
    "wkz.anzeige.zahl": "Gemessen",
    "wkz.anzeige.nicht_berechenbar": "Nicht berechenbar: Nenner 0",
    "wkz.anzeige.unvollstaendig": "Unvollständig erhoben",
    "wkz.anzeige.nicht_erhoben": "Nicht erhoben",
    "wkz.anzeige.unbekannt": "Unbekannt – Quelle nicht abrufbar",
    "wkz.anzeige.nichtErhobenGrund":
      "Diese Quelle führt keinen Space. Mit Space- oder Teamfilter gibt es hier keine Zahl — eine ungefilterte stünde für etwas anderes.",
    "wkz.erhoben.seit": "Erhoben seit {{datum}}",
    "wkz.erhoben.keins": "Noch kein Ereignis protokolliert — der Erhebungsbeginn ist nicht belegt.",
    "wkz.trend.verglichen": "{{differenz}} gegenüber dem Vorzeitraum ({{vorher}})",
    "wkz.trend.prozentpunkte": "{{zahl}} Prozentpunkte",
    "wkz.trend.momentaufnahme": "Kein Verlauf: nur der aktuelle Stand ist erhoben.",
    "wkz.trend.vorperiode_unvollstaendig":
      "Kein Trend: der Vorzeitraum ist nicht vollständig erhoben.",
    "wkz.trend.nenner_null": "Kein Trend: in einem der Zeiträume gab es keine Fragen.",
    "wkz.trend.nicht_erhoben": "Kein Trend: für diese Auswahl nicht erhoben.",
    "wkz.trend.unbekannt": "Kein Trend: Quelle nicht abrufbar.",
    "wkz.details.zusammenfassung": "So gezählt",
    "wkz.details.bedeutung": "Bedeutung",
    "wkz.details.nenner": "Grundmenge",
    "wkz.details.zeitraum": "Zeitraum",
    "wkz.details.datenstand": "Datenstand",
    "wkz.details.momentaufnahme":
      "Momentaufnahme zum Stand — der gewählte Zeitraum gilt für diese Zahl nicht.",
    "wkz.details.zeitraumWert": "{{von}} bis {{bis}}",
    "wkz.details.quote": "{{zaehler}} von {{nenner}}",
    "wkz.liste.zusammenfassung": "{{anzahl}} Vorgänge anzeigen",
    "wkz.liste.leer": "Keine offenen Vorgänge in dieser Auswahl.",
    "wkz.liste.oeffnen": "Bearbeiten",
    "wkz.liste.oeffnenLabel": "Bearbeiten: {{titel}}",
    "wkz.liste.arbeitsliste": "In der Arbeitsliste öffnen",
    "wkz.liste.nurHier":
      "Mit Teamfilter steht die Liste nur hier — die Arbeitsliste filtert nach Space, nicht nach Team.",
    "wkz.liste.nurHierZeitraum":
      "Die Arbeitsliste kennt weder Zeitraum noch geschlossene Lücken — genau diese Menge steht deshalb nur hier.",
    "wkz.liste.zurueckgehalten": "Fragetext nur für die Zuständigen sichtbar",
    "wkz.liste.ueberfaellig": "überfällig",
    "wkz.k.pruefung.titel": "Offene Prüfungen",
    "wkz.k.pruefung.bedeutung": "Beiträge, deren aktuelle Fassung auf eine Freigabe wartet.",
    "wkz.k.pruefung.nenner": "Alle für Sie sichtbaren Beiträge im Prüfbereich, je Beitrag einmal.",
    "wkz.k.revalidierung.titel": "Revalidierung fällig",
    "wkz.k.revalidierung.bedeutung":
      "Beiträge, bei denen jemand „Stimmt das noch?“ angefordert hat und noch niemand bestätigt hat.",
    "wkz.k.revalidierung.nenner": "Alle für Sie sichtbaren Beiträge mit laufender Revalidierung.",
    "wkz.k.konflikt.titel": "Ungelöste Konflikte",
    "wkz.k.konflikt.bedeutung":
      "Widersprüche zwischen zwei Beiträgen, die noch entschieden werden müssen.",
    "wkz.k.konflikt.nenner": "Konfliktpaare, deren beide Seiten Sie sehen dürfen.",
    "wkz.k.duplikat.titel": "Offene Duplikate",
    "wkz.k.duplikat.bedeutung":
      "Beiträge, die vermutlich dasselbe sagen und zusammengeführt oder getrennt werden sollten.",
    "wkz.k.duplikat.nenner": "Duplikatpaare, deren beide Seiten Sie sehen dürfen.",
    "wkz.k.luecke.titel": "Offene Wissenslücken",
    "wkz.k.luecke.bedeutung":
      "Fragen, auf die der Bestand keine Antwort hatte und die noch niemand geschlossen hat.",
    "wkz.k.luecke.nenner": "Alle offenen Lücken; dieselbe Frage zählt als eine Lücke.",
    "wkz.k.rueckmeldung.titel": "Neue Rückmeldungen",
    "wkz.k.rueckmeldung.bedeutung":
      "Belegte Meldungen „Antwort falsch“ oder „Quelle passt nicht“, die noch niemand übernommen hat.",
    "wkz.k.rueckmeldung.nenner": "Meldungen zu Beiträgen, die Sie sehen dürfen.",
    "wkz.k.rueckmeldung_unklar.titel": "Rückmeldungen ohne Abschlusssignal",
    "wkz.k.rueckmeldung_unklar.bedeutung":
      "Übernommene Meldungen, bei denen weder eine laufende Revalidierung noch eine Bestätigung belegt ist.",
    "wkz.k.rueckmeldung_unklar.nenner": "Übernommene Meldungen zu Beiträgen, die Sie sehen dürfen.",
    "wkz.k.fragen.titel": "Gestellte Fragen",
    "wkz.k.fragen.bedeutung":
      "Wie oft im Zeitraum eine Frage an den Wissensbestand gestellt wurde.",
    "wkz.k.fragen.nenner":
      "Alle Einträge „Frage gestellt“ im Prüfprotokoll, über alle Spaces; ohne Fragetext.",
    "wkz.k.beantwortet.titel": "Ohne Lücke beantwortet",
    "wkz.k.beantwortet.bedeutung":
      "Fragen im Zeitraum, für die der Bestand eine belegte Antwort hatte.",
    "wkz.k.beantwortet.nenner": "Dieselben Fragen wie oben, davon die beantworteten.",
    "wkz.k.antwortquote.titel": "Antwortquote",
    "wkz.k.antwortquote.bedeutung":
      "Anteil der Fragen, die ohne Wissenslücke beantwortet wurden. Sie sagt nichts über gesparte Zeit.",
    "wkz.k.antwortquote.nenner":
      "Zähler: ohne Lücke beantwortet · Nenner: gestellte Fragen im Zeitraum.",
    "wkz.k.neue_luecken.titel": "Neue Wissenslücken",
    "wkz.k.neue_luecken.bedeutung":
      "Lücken, die im Zeitraum erstmals entstanden sind — offen oder schon geschlossen.",
    "wkz.k.neue_luecken.nenner": "Alle Lücken mit Entstehungszeitpunkt im Zeitraum.",
    "wkz.bedarf.titel": "Häufig gefragt, noch offen",
    "wkz.bedarf.erklaerung":
      "Offene Wissenslücken nach der Häufigkeit derselben Frage. Jede Zeile ist der vorhandene Vorgang dieser Lücke — hier entsteht keine neue Aufgabe.",
    "wkz.bedarf.haeufigkeit": "{{anzahl}}× gefragt",
    "wkz.bedarf.ohneZaehlung": "Häufigkeit nicht gezählt",
    "wkz.bedarf.zugeordnet": "zugeordnet",
    "wkz.bedarf.niemand": "niemand zugeordnet",
    "wkz.bedarf.oeffnen": "Lücke bearbeiten",
    "wkz.bedarf.leer": "Keine offenen Wissenslücken.",
    "wkz.bedarf.gesamt": "{{gezeigt}} von {{offen}} offenen Lücken",
    "wkz.bedarf.altbestand": "{{anzahl}} davon ohne gezählte Häufigkeit (älterer Bestand)",
    "wkz.bedarf.nicht_erhoben":
      "Lücken tragen keinen Space — mit Space- oder Teamfilter ist der Fragebedarf nicht auswertbar.",
    "wkz.bedarf.unbekannt": "Die Wissenslücken sind gerade nicht abrufbar.",
    "wkz.suche.titel": "Ihre Suchen ohne Treffer",
    "wkz.suche.text":
      "Nur Ihre eigenen Suchen: erfolglose Suchen werden je Person geführt, eine Sicht auf die Suchbegriffe anderer ist bewusst nicht gebaut. Gezeigt werden höchstens {{deckel}} Begriffe mit der Zahl seit der ersten Erfassung und dem letzten Zeitpunkt — keine Zahl je Zeitraum, kein Trend, kein Space.",
    "wkz.suche.nicht_erhoben":
      "Suchen tragen keinen Space — mit Space- oder Teamfilter sind sie nicht auswertbar.",
    "wkz.suche.unbekannt": "Ihre Suchen ohne Treffer sind gerade nicht abrufbar.",
    "wkz.suche.leer": "Keine eigenen Suchen ohne Treffer.",
    "wkz.suche.anzahl": "{{anzahl}}× gesucht, zuletzt {{zeit}}",
    "wkz.suche.eingegrenzt": "Mit Filter gesucht: {{filter}}",
    "wkz.suche.vorgang": "Offene Lücke bearbeiten",
    "wkz.suche.vorgangLabel": "Offene Lücke zu „{{begriff}}“ bearbeiten",
    "wkz.suche.ohneVorgang": "Keine offene Lücke dazu, deren Frage Sie sehen dürfen",
    "wkz.suche.zuordnungUnbekannt": "Zuordnung derzeit unbekannt — Lücken nicht abrufbar",
    "wkz.export.knopf": "Als CSV exportieren",
    "wkz.export.hinweis":
      "Der Export enthält genau diese Auswahl und diesen Stand — nur Zahlen, keine Titel oder Fragetexte.",
    "wkz.export.stand": "Stand",
    "wkz.export.zeitraum": "Zeitraum",
    "wkz.export.tage": "Tage",
    "wkz.export.bereich": "Bereich",
    "wkz.export.kennzahl": "Kennzahl",
    "wkz.export.wert": "Wert",
    "wkz.export.lage": "Lage",
    "wkz.export.zaehler": "Zähler",
    "wkz.export.nenner": "Nenner",
    "wkz.export.erhobenSeit": "Erhoben seit",
    "wkz.export.trend": "Trend",
    "wkz.wert.details": "Wie der Wert entsteht",
    "wkz.wert.erklaerung":
      "Ausgangspunkt ist die Validierungsquote. Abgezogen werden veraltetes Wissen (× 0,4), Einzelquellen (× 0,3), offene Lücken (je 4, höchstens 20) und offene Konflikte (je 5, höchstens 20). Ab 70 gilt der Wert als gut, ab 40 als mittel.",
    "wkz.wert.unbelegt":
      "„Einstufung unbelegt“ heisst: Es ist nicht nachgewiesen, dass vollständig nach Konflikten gesucht wurde. Deshalb steht die schlechtere Zahl groß da und kein Band.",
    "wkz.bestand.titel": "Bestandszahlen",
    "wkz.bestand.erklaerung":
      "Gesamtbestand ohne Zeitraum und ohne Space- oder Teamfilter, nur sichtbare Inhalte. Stand {{zeit}}.",
    "wkz.bestand.total": "Alle sichtbaren Wissensobjekte",
    "wkz.bestand.offen": "Status offen, von allen sichtbaren",
    "wkz.bestand.validiert": "Status validiert, von allen sichtbaren",
    "wkz.bestand.categories": "Verschiedene Kategorien im sichtbaren Bestand",
    "wkz.bestand.avgTrust": "Mittleres Vertrauen (0–100) über alle geladenen Objekte",
    "wkz.bestand.validationRate": "Validiert ÷ alle sichtbaren Objekte",
    "wkz.bestand.openTasks": "Offene Prüferzuweisungen aller Prüfenden",
    "wkz.bestand.doneTasks": "Erledigte Prüferzuweisungen aller Prüfenden",
    "wkz.bestand.impactValidated": "Validierte Objekte im sichtbaren Bestand",
    "wkz.bestand.impactAsk": "Alle protokollierten Fragen seit Protokollbeginn, alle Spaces",
    "wkz.bestand.impactAnswered": "Davon ohne Wissenslücke beantwortet",
    "wkz.bestand.impactRate": "Ohne Lücke beantwortet ÷ alle Fragen; keine Zeitersparnis",
    "wkz.bestand.keineGrundmenge": "Grundmenge leer — nicht berechenbar",
    "wkz.bestand.fragenTitel": "Fragen und validiertes Wissen gesamt",
    "wkz.bestand.fragenHilfe":
      "Gesamtzahlen seit Beginn des Protokolls: validierte Objekte, gestellte Fragen, ohne Lücke beantwortete Fragen und die Antwortquote daraus. Sie beschreiben Nutzung und Bestand — keine gemessene Zeit- oder Geldersparnis. Vergleiche über Zeiträume stehen oben unter „Fragen und Lücken im Zeitraum“.",
  },
  en: {
    "wkz.titel": "Action needed and knowledge metrics",
    "wkz.leitsatz":
      "First what is open right now; below, questions and gaps in the selected period. Every figure states its meaning, base, period and data status.",
    "wkz.laedt": "Loading metrics …",
    "wkz.fehler": "The metrics could not be loaded.",
    "wkz.recht": "These metrics are reserved for administration.",
    "wkz.erneut": "Reload",
    "wkz.aktualisieren": "Refresh",
    "wkz.stand": "As of {{zeit}}",
    "wkz.zeitraum": "Period: {{von}} to {{bis}}",
    "wkz.vorperiode": "Compared with {{von}} to {{bis}}",
    "wkz.filter.titel": "Selection",
    "wkz.filter.zeitraum": "Period",
    "wkz.filter.tage": "Last {{anzahl}} days",
    "wkz.filter.space": "Space",
    "wkz.filter.team": "Team",
    "wkz.filter.alle": "All",
    "wkz.filter.zuruecksetzen": "Reset selection",
    "wkz.filter.hinweis":
      "Space and team narrow down to content in those spaces. Sources without a space (questions and gaps) are then shown as “not collected”.",
    "wkz.filter.ungueltig":
      "This selection is not available — you cannot choose this space or team.",
    "wkz.quelle.teilweise":
      "Not all case sources could be reached. Affected figures are shown as “unknown”, not as 0.",
    "wkz.handlungsbedarf.titel": "Open now",
    "wkz.handlungsbedarf.erklaerung":
      "Snapshot as of the data status. There is deliberately no history: earlier states are not stored and are therefore not reconstructed.",
    "wkz.nutzung.titel": "Questions and gaps in the period",
    "wkz.nutzung.erklaerung":
      "Counted from the question log and the knowledge gaps. These figures describe usage — they are not measured time or money savings.",
    "wkz.anzeige.zahl": "Measured",
    "wkz.anzeige.nicht_berechenbar": "Not computable: denominator 0",
    "wkz.anzeige.unvollstaendig": "Incompletely collected",
    "wkz.anzeige.nicht_erhoben": "Not collected",
    "wkz.anzeige.unbekannt": "Unknown – source unavailable",
    "wkz.anzeige.nichtErhobenGrund":
      "This source carries no space. With a space or team filter there is no figure here — an unfiltered one would stand for something else.",
    "wkz.erhoben.seit": "Collected since {{datum}}",
    "wkz.erhoben.keins": "No event logged yet — the start of collection is not evidenced.",
    "wkz.trend.verglichen": "{{differenz}} compared with the previous period ({{vorher}})",
    "wkz.trend.prozentpunkte": "{{zahl}} percentage points",
    "wkz.trend.momentaufnahme": "No history: only the current state is collected.",
    "wkz.trend.vorperiode_unvollstaendig": "No trend: the previous period is not fully collected.",
    "wkz.trend.nenner_null": "No trend: one of the periods had no questions.",
    "wkz.trend.nicht_erhoben": "No trend: not collected for this selection.",
    "wkz.trend.unbekannt": "No trend: source unavailable.",
    "wkz.details.zusammenfassung": "How this is counted",
    "wkz.details.bedeutung": "Meaning",
    "wkz.details.nenner": "Base",
    "wkz.details.zeitraum": "Period",
    "wkz.details.datenstand": "Data status",
    "wkz.details.momentaufnahme":
      "Snapshot as of the data status — the selected period does not apply to this figure.",
    "wkz.details.zeitraumWert": "{{von}} to {{bis}}",
    "wkz.details.quote": "{{zaehler}} of {{nenner}}",
    "wkz.liste.zusammenfassung": "Show {{anzahl}} cases",
    "wkz.liste.leer": "No open cases in this selection.",
    "wkz.liste.oeffnen": "Work on it",
    "wkz.liste.oeffnenLabel": "Work on: {{titel}}",
    "wkz.liste.arbeitsliste": "Open in the work list",
    "wkz.liste.nurHier":
      "With a team filter the list is shown only here — the work list filters by space, not by team.",
    "wkz.liste.nurHierZeitraum":
      "The work list knows neither periods nor closed gaps — so exactly this set is shown only here.",
    "wkz.liste.zurueckgehalten": "Question text visible only to those responsible",
    "wkz.liste.ueberfaellig": "overdue",
    "wkz.k.pruefung.titel": "Open reviews",
    "wkz.k.pruefung.bedeutung": "Contributions whose current version is waiting for approval.",
    "wkz.k.pruefung.nenner": "All contributions visible to you in review, each counted once.",
    "wkz.k.revalidierung.titel": "Revalidation due",
    "wkz.k.revalidierung.bedeutung":
      "Contributions where someone asked “Is this still true?” and nobody has confirmed yet.",
    "wkz.k.revalidierung.nenner": "All contributions visible to you with a running revalidation.",
    "wkz.k.konflikt.titel": "Unresolved conflicts",
    "wkz.k.konflikt.bedeutung":
      "Contradictions between two contributions that still need a decision.",
    "wkz.k.konflikt.nenner": "Conflict pairs where you may see both sides.",
    "wkz.k.duplikat.titel": "Open duplicates",
    "wkz.k.duplikat.bedeutung":
      "Contributions that probably say the same and should be merged or separated.",
    "wkz.k.duplikat.nenner": "Duplicate pairs where you may see both sides.",
    "wkz.k.luecke.titel": "Open knowledge gaps",
    "wkz.k.luecke.bedeutung":
      "Questions the knowledge base could not answer and that nobody has closed yet.",
    "wkz.k.luecke.nenner": "All open gaps; the same question counts as one gap.",
    "wkz.k.rueckmeldung.titel": "New feedback",
    "wkz.k.rueckmeldung.bedeutung":
      "Evidenced reports “answer wrong” or “source does not fit” that nobody has taken over yet.",
    "wkz.k.rueckmeldung.nenner": "Reports on contributions you may see.",
    "wkz.k.rueckmeldung_unklar.titel": "Feedback without a closing signal",
    "wkz.k.rueckmeldung_unklar.bedeutung":
      "Taken-over reports with neither a running revalidation nor a confirmation on record.",
    "wkz.k.rueckmeldung_unklar.nenner": "Taken-over reports on contributions you may see.",
    "wkz.k.fragen.titel": "Questions asked",
    "wkz.k.fragen.bedeutung": "How often a question was put to the knowledge base in the period.",
    "wkz.k.fragen.nenner":
      "All “question asked” entries in the audit log, across all spaces; no question text.",
    "wkz.k.beantwortet.titel": "Answered without a gap",
    "wkz.k.beantwortet.bedeutung":
      "Questions in the period for which the knowledge base had an evidenced answer.",
    "wkz.k.beantwortet.nenner": "The same questions as above, of which the answered ones.",
    "wkz.k.antwortquote.titel": "Answer rate",
    "wkz.k.antwortquote.bedeutung":
      "Share of questions answered without a knowledge gap. It says nothing about time saved.",
    "wkz.k.antwortquote.nenner":
      "Numerator: answered without a gap · Denominator: questions asked in the period.",
    "wkz.k.neue_luecken.titel": "New knowledge gaps",
    "wkz.k.neue_luecken.bedeutung": "Gaps that first arose in the period — open or already closed.",
    "wkz.k.neue_luecken.nenner": "All gaps created within the period.",
    "wkz.bedarf.titel": "Frequently asked, still open",
    "wkz.bedarf.erklaerung":
      "Open knowledge gaps by how often the same question came up. Each row is the existing case of that gap — no new task is created here.",
    "wkz.bedarf.haeufigkeit": "asked {{anzahl}}×",
    "wkz.bedarf.ohneZaehlung": "Frequency not counted",
    "wkz.bedarf.zugeordnet": "assigned",
    "wkz.bedarf.niemand": "nobody assigned",
    "wkz.bedarf.oeffnen": "Work on gap",
    "wkz.bedarf.leer": "No open knowledge gaps.",
    "wkz.bedarf.gesamt": "{{gezeigt}} of {{offen}} open gaps",
    "wkz.bedarf.altbestand": "{{anzahl}} of them without a counted frequency (older records)",
    "wkz.bedarf.nicht_erhoben":
      "Gaps carry no space — with a space or team filter the question demand cannot be evaluated.",
    "wkz.bedarf.unbekannt": "The knowledge gaps are currently unavailable.",
    "wkz.suche.titel": "Your searches without results",
    "wkz.suche.text":
      "Only your own searches: unsuccessful searches are kept per person, and a view of other people's search terms is deliberately not built. At most {{deckel}} terms are shown with the count since first recorded and the last time — no count per period, no trend, no space.",
    "wkz.suche.nicht_erhoben":
      "Searches carry no space — with a space or team filter they cannot be evaluated.",
    "wkz.suche.unbekannt": "Your searches without results are currently unavailable.",
    "wkz.suche.leer": "No searches of yours without results.",
    "wkz.suche.anzahl": "searched {{anzahl}}×, last {{zeit}}",
    "wkz.suche.eingegrenzt": "Searched with filter: {{filter}}",
    "wkz.suche.vorgang": "Work on open gap",
    "wkz.suche.vorgangLabel": "Work on the open gap for “{{begriff}}”",
    "wkz.suche.ohneVorgang": "No open gap for this whose question you may see",
    "wkz.suche.zuordnungUnbekannt": "Assignment currently unknown — gaps unavailable",
    "wkz.export.knopf": "Export as CSV",
    "wkz.export.hinweis":
      "The export contains exactly this selection and this data status — figures only, no titles or question texts.",
    "wkz.export.stand": "As of",
    "wkz.export.zeitraum": "Period",
    "wkz.export.tage": "Days",
    "wkz.export.bereich": "Section",
    "wkz.export.kennzahl": "Metric",
    "wkz.export.wert": "Value",
    "wkz.export.lage": "Status",
    "wkz.export.zaehler": "Numerator",
    "wkz.export.nenner": "Denominator",
    "wkz.export.erhobenSeit": "Collected since",
    "wkz.export.trend": "Trend",
    "wkz.wert.details": "How the score is formed",
    "wkz.wert.erklaerung":
      "It starts from the validation rate. Deducted are outdated knowledge (× 0.4), single sources (× 0.3), open gaps (4 each, at most 20) and open conflicts (5 each, at most 20). From 70 the score counts as good, from 40 as medium.",
    "wkz.wert.unbelegt":
      "“Rating unproven” means: it is not evidenced that conflicts were searched for completely. That is why the worse figure is shown large and no band.",
    "wkz.bestand.titel": "Inventory figures",
    "wkz.bestand.erklaerung":
      "Whole inventory without period and without space or team filter, visible content only. As of {{zeit}}.",
    "wkz.bestand.total": "All visible knowledge objects",
    "wkz.bestand.offen": "Status open, of all visible",
    "wkz.bestand.validiert": "Status validated, of all visible",
    "wkz.bestand.categories": "Distinct categories in the visible inventory",
    "wkz.bestand.avgTrust": "Average trust (0–100) across all loaded objects",
    "wkz.bestand.validationRate": "Validated ÷ all visible objects",
    "wkz.bestand.openTasks": "Open reviewer assignments of all reviewers",
    "wkz.bestand.doneTasks": "Completed reviewer assignments of all reviewers",
    "wkz.bestand.impactValidated": "Validated objects in the visible inventory",
    "wkz.bestand.impactAsk": "All logged questions since the log began, all spaces",
    "wkz.bestand.impactAnswered": "Of which answered without a knowledge gap",
    "wkz.bestand.impactRate": "Answered without a gap ÷ all questions; not time saved",
    "wkz.bestand.keineGrundmenge": "Empty base — not computable",
    "wkz.bestand.fragenTitel": "Questions and validated knowledge in total",
    "wkz.bestand.fragenHilfe":
      "Totals since the log began: validated objects, questions asked, questions answered without a gap and the resulting answer rate. They describe usage and inventory — not measured time or money savings. Comparisons across periods are shown above under “Questions and gaps in the period”.",
  },
  nl: {
    "wkz.titel": "Actie nodig en kenniskengetallen",
    "wkz.leitsatz":
      "Eerst wat nu open staat; daaronder vragen en lacunes in de gekozen periode. Elk getal noemt betekenis, basis, periode en datastand.",
    "wkz.laedt": "Kengetallen worden geladen …",
    "wkz.fehler": "De kengetallen konden niet worden geladen.",
    "wkz.recht": "Deze kengetallen zijn voorbehouden aan beheer.",
    "wkz.erneut": "Opnieuw laden",
    "wkz.aktualisieren": "Vernieuwen",
    "wkz.stand": "Stand {{zeit}}",
    "wkz.zeitraum": "Periode: {{von}} tot {{bis}}",
    "wkz.vorperiode": "Vergeleken met {{von}} tot {{bis}}",
    "wkz.filter.titel": "Selectie",
    "wkz.filter.zeitraum": "Periode",
    "wkz.filter.tage": "Laatste {{anzahl}} dagen",
    "wkz.filter.space": "Space",
    "wkz.filter.team": "Team",
    "wkz.filter.alle": "Alle",
    "wkz.filter.zuruecksetzen": "Selectie wissen",
    "wkz.filter.hinweis":
      "Space en team beperken tot inhoud in die spaces. Bronnen zonder space (vragen en lacunes) staan dan als „niet verzameld”.",
    "wkz.filter.ungueltig":
      "Deze selectie is niet beschikbaar — u kunt deze space of dit team niet kiezen.",
    "wkz.quelle.teilweise":
      "Niet alle bronnen van zaken waren bereikbaar. Betrokken getallen staan als „onbekend”, niet als 0.",
    "wkz.handlungsbedarf.titel": "Nu open",
    "wkz.handlungsbedarf.erklaerung":
      "Momentopname op de datastand. Een verloop ontbreekt bewust: eerdere standen worden niet opgeslagen en daarom niet nagebootst.",
    "wkz.nutzung.titel": "Vragen en lacunes in de periode",
    "wkz.nutzung.erklaerung":
      "Geteld uit het vragenlogboek en de kennislacunes. De getallen beschrijven gebruik — het zijn geen gemeten tijd- of geldbesparingen.",
    "wkz.anzeige.zahl": "Gemeten",
    "wkz.anzeige.nicht_berechenbar": "Niet te berekenen: noemer 0",
    "wkz.anzeige.unvollstaendig": "Onvolledig verzameld",
    "wkz.anzeige.nicht_erhoben": "Niet verzameld",
    "wkz.anzeige.unbekannt": "Onbekend – bron niet bereikbaar",
    "wkz.anzeige.nichtErhobenGrund":
      "Deze bron kent geen space. Met een space- of teamfilter staat hier geen getal — een ongefilterd getal zou voor iets anders staan.",
    "wkz.erhoben.seit": "Verzameld sinds {{datum}}",
    "wkz.erhoben.keins":
      "Nog geen gebeurtenis gelogd — het begin van de verzameling is niet aangetoond.",
    "wkz.trend.verglichen": "{{differenz}} ten opzichte van de vorige periode ({{vorher}})",
    "wkz.trend.prozentpunkte": "{{zahl}} procentpunten",
    "wkz.trend.momentaufnahme": "Geen verloop: alleen de huidige stand is verzameld.",
    "wkz.trend.vorperiode_unvollstaendig":
      "Geen trend: de vorige periode is niet volledig verzameld.",
    "wkz.trend.nenner_null": "Geen trend: in een van de perioden waren er geen vragen.",
    "wkz.trend.nicht_erhoben": "Geen trend: voor deze selectie niet verzameld.",
    "wkz.trend.unbekannt": "Geen trend: bron niet bereikbaar.",
    "wkz.details.zusammenfassung": "Zo geteld",
    "wkz.details.bedeutung": "Betekenis",
    "wkz.details.nenner": "Basis",
    "wkz.details.zeitraum": "Periode",
    "wkz.details.datenstand": "Datastand",
    "wkz.details.momentaufnahme":
      "Momentopname op de datastand — de gekozen periode geldt niet voor dit getal.",
    "wkz.details.zeitraumWert": "{{von}} tot {{bis}}",
    "wkz.details.quote": "{{zaehler}} van {{nenner}}",
    "wkz.liste.zusammenfassung": "{{anzahl}} zaken tonen",
    "wkz.liste.leer": "Geen open zaken in deze selectie.",
    "wkz.liste.oeffnen": "Bewerken",
    "wkz.liste.oeffnenLabel": "Bewerken: {{titel}}",
    "wkz.liste.arbeitsliste": "In de werklijst openen",
    "wkz.liste.nurHier":
      "Met een teamfilter staat de lijst alleen hier — de werklijst filtert op space, niet op team.",
    "wkz.liste.nurHierZeitraum":
      "De werklijst kent geen perioden en geen gesloten lacunes — daarom staat precies deze set alleen hier.",
    "wkz.liste.zurueckgehalten": "Vraagtekst alleen zichtbaar voor de verantwoordelijken",
    "wkz.liste.ueberfaellig": "verlopen",
    "wkz.k.pruefung.titel": "Open controles",
    "wkz.k.pruefung.bedeutung": "Bijdragen waarvan de huidige versie op vrijgave wacht.",
    "wkz.k.pruefung.nenner": "Alle voor u zichtbare bijdragen in controle, elk één keer.",
    "wkz.k.revalidierung.titel": "Hervalidatie nodig",
    "wkz.k.revalidierung.bedeutung":
      "Bijdragen waarbij iemand „Klopt dit nog?” heeft gevraagd en nog niemand heeft bevestigd.",
    "wkz.k.revalidierung.nenner": "Alle voor u zichtbare bijdragen met een lopende hervalidatie.",
    "wkz.k.konflikt.titel": "Onopgeloste conflicten",
    "wkz.k.konflikt.bedeutung":
      "Tegenstrijdigheden tussen twee bijdragen waarover nog besloten moet worden.",
    "wkz.k.konflikt.nenner": "Conflictparen waarvan u beide kanten mag zien.",
    "wkz.k.duplikat.titel": "Open duplicaten",
    "wkz.k.duplikat.bedeutung":
      "Bijdragen die waarschijnlijk hetzelfde zeggen en samengevoegd of gescheiden moeten worden.",
    "wkz.k.duplikat.nenner": "Duplicaatparen waarvan u beide kanten mag zien.",
    "wkz.k.luecke.titel": "Open kennislacunes",
    "wkz.k.luecke.bedeutung":
      "Vragen waarop de kennisbank geen antwoord had en die nog niemand heeft gesloten.",
    "wkz.k.luecke.nenner": "Alle open lacunes; dezelfde vraag telt als één lacune.",
    "wkz.k.rueckmeldung.titel": "Nieuwe feedback",
    "wkz.k.rueckmeldung.bedeutung":
      "Vastgelegde meldingen „antwoord fout” of „bron past niet” die nog niemand heeft overgenomen.",
    "wkz.k.rueckmeldung.nenner": "Meldingen over bijdragen die u mag zien.",
    "wkz.k.rueckmeldung_unklar.titel": "Feedback zonder afsluitend signaal",
    "wkz.k.rueckmeldung_unklar.bedeutung":
      "Overgenomen meldingen zonder lopende hervalidatie en zonder vastgelegde bevestiging.",
    "wkz.k.rueckmeldung_unklar.nenner": "Overgenomen meldingen over bijdragen die u mag zien.",
    "wkz.k.fragen.titel": "Gestelde vragen",
    "wkz.k.fragen.bedeutung": "Hoe vaak in de periode een vraag aan de kennisbank is gesteld.",
    "wkz.k.fragen.nenner":
      "Alle vermeldingen „vraag gesteld” in het auditlogboek, over alle spaces; zonder vraagtekst.",
    "wkz.k.beantwortet.titel": "Zonder lacune beantwoord",
    "wkz.k.beantwortet.bedeutung":
      "Vragen in de periode waarvoor de kennisbank een onderbouwd antwoord had.",
    "wkz.k.beantwortet.nenner": "Dezelfde vragen als hierboven, waarvan de beantwoorde.",
    "wkz.k.antwortquote.titel": "Antwoordpercentage",
    "wkz.k.antwortquote.bedeutung":
      "Aandeel vragen dat zonder kennislacune is beantwoord. Het zegt niets over bespaarde tijd.",
    "wkz.k.antwortquote.nenner":
      "Teller: zonder lacune beantwoord · Noemer: gestelde vragen in de periode.",
    "wkz.k.neue_luecken.titel": "Nieuwe kennislacunes",
    "wkz.k.neue_luecken.bedeutung":
      "Lacunes die in de periode voor het eerst zijn ontstaan — open of al gesloten.",
    "wkz.k.neue_luecken.nenner": "Alle lacunes die binnen de periode zijn ontstaan.",
    "wkz.bedarf.titel": "Vaak gevraagd, nog open",
    "wkz.bedarf.erklaerung":
      "Open kennislacunes naar hoe vaak dezelfde vraag kwam. Elke regel is de bestaande zaak van die lacune — hier ontstaat geen nieuwe taak.",
    "wkz.bedarf.haeufigkeit": "{{anzahl}}× gevraagd",
    "wkz.bedarf.ohneZaehlung": "Frequentie niet geteld",
    "wkz.bedarf.zugeordnet": "toegewezen",
    "wkz.bedarf.niemand": "niemand toegewezen",
    "wkz.bedarf.oeffnen": "Lacune bewerken",
    "wkz.bedarf.leer": "Geen open kennislacunes.",
    "wkz.bedarf.gesamt": "{{gezeigt}} van {{offen}} open lacunes",
    "wkz.bedarf.altbestand": "{{anzahl}} daarvan zonder getelde frequentie (oudere gegevens)",
    "wkz.bedarf.nicht_erhoben":
      "Lacunes hebben geen space — met een space- of teamfilter is de vraag niet te evalueren.",
    "wkz.bedarf.unbekannt": "De kennislacunes zijn nu niet bereikbaar.",
    "wkz.suche.titel": "Uw zoekopdrachten zonder resultaat",
    "wkz.suche.text":
      "Alleen uw eigen zoekopdrachten: zoekopdrachten zonder resultaat worden per persoon bijgehouden, een overzicht van zoektermen van anderen is bewust niet gebouwd. Getoond worden hoogstens {{deckel}} termen met het aantal sinds de eerste registratie en het laatste tijdstip — geen aantal per periode, geen trend, geen space.",
    "wkz.suche.nicht_erhoben":
      "Zoekopdrachten hebben geen space — met een space- of teamfilter zijn ze niet te evalueren.",
    "wkz.suche.unbekannt": "Uw zoekopdrachten zonder resultaat zijn nu niet bereikbaar.",
    "wkz.suche.leer": "Geen eigen zoekopdrachten zonder resultaat.",
    "wkz.suche.anzahl": "{{anzahl}}× gezocht, laatst {{zeit}}",
    "wkz.suche.eingegrenzt": "Gezocht met filter: {{filter}}",
    "wkz.suche.vorgang": "Open lacune bewerken",
    "wkz.suche.vorgangLabel": "Open lacune bij „{{begriff}}” bewerken",
    "wkz.suche.ohneVorgang": "Geen open lacune hierbij waarvan u de vraag mag zien",
    "wkz.suche.zuordnungUnbekannt": "Koppeling momenteel onbekend — lacunes niet bereikbaar",
    "wkz.export.knopf": "Als CSV exporteren",
    "wkz.export.hinweis":
      "De export bevat precies deze selectie en deze datastand — alleen getallen, geen titels of vraagteksten.",
    "wkz.export.stand": "Stand",
    "wkz.export.zeitraum": "Periode",
    "wkz.export.tage": "Dagen",
    "wkz.export.bereich": "Onderdeel",
    "wkz.export.kennzahl": "Kengetal",
    "wkz.export.wert": "Waarde",
    "wkz.export.lage": "Status",
    "wkz.export.zaehler": "Teller",
    "wkz.export.nenner": "Noemer",
    "wkz.export.erhobenSeit": "Verzameld sinds",
    "wkz.export.trend": "Trend",
    "wkz.wert.details": "Hoe de waarde ontstaat",
    "wkz.wert.erklaerung":
      "Uitgangspunt is het validatiepercentage. Afgetrokken worden verouderde kennis (× 0,4), enkele bronnen (× 0,3), open lacunes (elk 4, hoogstens 20) en open conflicten (elk 5, hoogstens 20). Vanaf 70 geldt de waarde als goed, vanaf 40 als middel.",
    "wkz.wert.unbelegt":
      "„Indeling niet onderbouwd” betekent: niet aangetoond is dat volledig naar conflicten is gezocht. Daarom staat het slechtere getal groot en geen band.",
    "wkz.bestand.titel": "Bestandscijfers",
    "wkz.bestand.erklaerung":
      "Hele bestand zonder periode en zonder space- of teamfilter, alleen zichtbare inhoud. Stand {{zeit}}.",
    "wkz.bestand.total": "Alle zichtbare kennisobjecten",
    "wkz.bestand.offen": "Status open, van alle zichtbare",
    "wkz.bestand.validiert": "Status gevalideerd, van alle zichtbare",
    "wkz.bestand.categories": "Verschillende categorieën in het zichtbare bestand",
    "wkz.bestand.avgTrust": "Gemiddeld vertrouwen (0–100) over alle geladen objecten",
    "wkz.bestand.validationRate": "Gevalideerd ÷ alle zichtbare objecten",
    "wkz.bestand.openTasks": "Open controletoewijzingen van alle controleurs",
    "wkz.bestand.doneTasks": "Afgeronde controletoewijzingen van alle controleurs",
    "wkz.bestand.impactValidated": "Gevalideerde objecten in het zichtbare bestand",
    "wkz.bestand.impactAsk": "Alle gelogde vragen sinds het begin van het logboek, alle spaces",
    "wkz.bestand.impactAnswered": "Waarvan beantwoord zonder kennislacune",
    "wkz.bestand.impactRate": "Zonder lacune beantwoord ÷ alle vragen; geen tijdsbesparing",
    "wkz.bestand.keineGrundmenge": "Lege basis — niet te berekenen",
    "wkz.bestand.fragenTitel": "Vragen en gevalideerde kennis in totaal",
    "wkz.bestand.fragenHilfe":
      "Totalen sinds het begin van het logboek: gevalideerde objecten, gestelde vragen, zonder lacune beantwoorde vragen en het antwoordpercentage daaruit. Ze beschrijven gebruik en bestand — geen gemeten tijd- of geldbesparing. Vergelijkingen over perioden staan hierboven onder „Vragen en lacunes in de periode”.",
  },
} satisfies Textmodul;
